// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package tirdad

// Generated from OpenAPI doc version 1.0 and generator version 2.917.0

import (
	"context"
	"fmt"
	"github.com/tirdad-billing/go-sdk/v2/internal/config"
	"github.com/tirdad-billing/go-sdk/v2/internal/hooks"
	"github.com/tirdad-billing/go-sdk/v2/internal/utils"
	"github.com/tirdad-billing/go-sdk/v2/models/types"
	"github.com/tirdad-billing/go-sdk/v2/retry"
	"net/http"
	"time"
)

// ServerList contains the list of servers available to the SDK
var ServerList = []string{
	// US Region
	"https://api.tirdad.ai/v1",
	// India Region
	"https://api.cloud.flexprice.io/v1",
}

// HTTPClient provides an interface for supplying the SDK with a custom HTTP client
type HTTPClient interface {
	Do(req *http.Request) (*http.Response, error)
}

// String provides a helper function to return a pointer to a string
func String(s string) *string { return &s }

// Bool provides a helper function to return a pointer to a bool
func Bool(b bool) *bool { return &b }

// Int provides a helper function to return a pointer to an int
func Int(i int) *int { return &i }

// Int64 provides a helper function to return a pointer to an int64
func Int64(i int64) *int64 { return &i }

// Float32 provides a helper function to return a pointer to a float32
func Float32(f float32) *float32 { return &f }

// Float64 provides a helper function to return a pointer to a float64
func Float64(f float64) *float64 { return &f }

// Pointer provides a helper function to return a pointer to a type
func Pointer[T any](v T) *T { return &v }

// Tirdad - Flexprice API: Flexprice API Service
type Tirdad struct {
	SDKVersion         string
	Addons             *Addons
	CreditGrants       *CreditGrants
	Entitlements       *Entitlements
	Alerts             *Alerts
	AlertSettings      *AlertSettings
	Checkout           *Checkout
	Costs              *Costs
	Coupons            *Coupons
	CouponAssociations *CouponAssociations
	CreditNotes        *CreditNotes
	Customers          *Customers
	Wallets            *Wallets
	Invoices           *Invoices
	Environments       *Environments
	Events             *Events
	Features           *Features
	Groups             *Groups
	Integrations       *Integrations
	Payments           *Payments
	Plans              *Plans
	Prices             *Prices
	PriceUnits         *PriceUnits
	Rbac               *Rbac
	Secrets            *Secrets
	Subscriptions      *Subscriptions
	Tasks              *Tasks
	ScheduledTasks     *ScheduledTasks
	TaxAssociations    *TaxAssociations
	TaxRates           *TaxRates
	Tenants            *Tenants
	Users              *Users
	WebhookEvents      *WebhookEvents
	Workflows          *Workflows

	sdkConfiguration config.SDKConfiguration
	hooks            *hooks.Hooks
}

type SDKOption func(*Tirdad)

// WithServerURL allows providing an alternative server URL
func WithServerURL(serverURL string) SDKOption {
	return func(sdk *Tirdad) {
		sdk.sdkConfiguration.ServerURL = serverURL
	}
}

// WithTemplatedServerURL allows the overriding of the default server URL with a templated URL populated with the provided parameters
func WithTemplatedServerURL(serverURL string, params map[string]string) SDKOption {
	return func(sdk *Tirdad) {
		if params != nil {
			serverURL = utils.ReplaceParameters(serverURL, params)
		}

		sdk.sdkConfiguration.ServerURL = serverURL
	}
}

// WithServerIndex allows the overriding of the default server by index
func WithServerIndex(serverIndex int) SDKOption {
	return func(sdk *Tirdad) {
		if serverIndex < 0 || serverIndex >= len(ServerList) {
			panic(fmt.Errorf("server index %d out of range", serverIndex))
		}

		sdk.sdkConfiguration.ServerIndex = serverIndex
	}
}

// WithClient allows the overriding of the default HTTP client used by the SDK
func WithClient(client HTTPClient) SDKOption {
	return func(sdk *Tirdad) {
		sdk.sdkConfiguration.Client = client
	}
}

// WithSecurity configures the SDK to use the provided security details
func WithSecurity(apiKeyAuth string) SDKOption {
	return func(sdk *Tirdad) {
		security := types.Security{APIKeyAuth: apiKeyAuth}
		sdk.sdkConfiguration.Security = utils.AsSecuritySource(&security)
	}
}

// WithSecuritySource configures the SDK to invoke the Security Source function on each method call to determine authentication
func WithSecuritySource(security func(context.Context) (types.Security, error)) SDKOption {
	return func(sdk *Tirdad) {
		sdk.sdkConfiguration.Security = func(ctx context.Context) (interface{}, error) {
			return security(ctx)
		}
	}
}

func WithRetryConfig(retryConfig retry.Config) SDKOption {
	return func(sdk *Tirdad) {
		sdk.sdkConfiguration.RetryConfig = &retryConfig
	}
}

// WithTimeout Optional request timeout applied to each operation
func WithTimeout(timeout time.Duration) SDKOption {
	return func(sdk *Tirdad) {
		sdk.sdkConfiguration.Timeout = &timeout
	}
}

// New creates a new instance of the SDK with the provided options
func New(opts ...SDKOption) *Tirdad {
	sdk := &Tirdad{
		SDKVersion: "2.1.21",
		sdkConfiguration: config.SDKConfiguration{
			UserAgent:  "speakeasy-sdk/go 2.1.21 2.917.0 1.0 github.com/tirdad-billing/go-sdk/v2",
			ServerList: ServerList,
		},
		hooks: hooks.New(),
	}
	for _, opt := range opts {
		opt(sdk)
	}

	// Use WithClient to override the default client if you would like to customize the timeout
	if sdk.sdkConfiguration.Client == nil {
		sdk.sdkConfiguration.Client = &http.Client{Timeout: 60 * time.Second}
	}

	sdk.sdkConfiguration = sdk.hooks.SDKInit(sdk.sdkConfiguration)

	sdk.Addons = newAddons(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.CreditGrants = newCreditGrants(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.Entitlements = newEntitlements(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.Alerts = newAlerts(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.AlertSettings = newAlertSettings(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.Checkout = newCheckout(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.Costs = newCosts(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.Coupons = newCoupons(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.CouponAssociations = newCouponAssociations(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.CreditNotes = newCreditNotes(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.Customers = newCustomers(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.Wallets = newWallets(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.Invoices = newInvoices(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.Environments = newEnvironments(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.Events = newEvents(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.Features = newFeatures(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.Groups = newGroups(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.Integrations = newIntegrations(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.Payments = newPayments(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.Plans = newPlans(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.Prices = newPrices(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.PriceUnits = newPriceUnits(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.Rbac = newRbac(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.Secrets = newSecrets(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.Subscriptions = newSubscriptions(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.Tasks = newTasks(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.ScheduledTasks = newScheduledTasks(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.TaxAssociations = newTaxAssociations(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.TaxRates = newTaxRates(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.Tenants = newTenants(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.Users = newUsers(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.WebhookEvents = newWebhookEvents(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.Workflows = newWorkflows(sdk, sdk.sdkConfiguration, sdk.hooks)

	return sdk
}
