// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package dtos

import (
	"github.com/tirdad-billing/go-sdk/v2/internal/utils"
	"github.com/tirdad-billing/go-sdk/v2/models/types"
)

type CancelSubscriptionScheduleRequest struct {
	// Schedule ID (optional if using request body)
	ScheduleID string `pathParam:"style=simple,explode=false,name=schedule_id"`
	// Cancel request (optional if using path parameter)
	Body *types.CancelScheduleRequest `request:"mediaType=application/json"`
}

func (c CancelSubscriptionScheduleRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CancelSubscriptionScheduleRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, []string{"schedule_id"}); err != nil {
		return err
	}
	return nil
}

func (c *CancelSubscriptionScheduleRequest) GetScheduleID() string {
	if c == nil {
		return ""
	}
	return c.ScheduleID
}

func (c *CancelSubscriptionScheduleRequest) GetBody() *types.CancelScheduleRequest {
	if c == nil {
		return nil
	}
	return c.Body
}

type CancelSubscriptionScheduleResponse struct {
	HTTPMeta types.HTTPMetadata `json:"-"`
	// OK
	CancelScheduleResponse *types.CancelScheduleResponse
}

func (c CancelSubscriptionScheduleResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CancelSubscriptionScheduleResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, []string{"HttpMeta"}); err != nil {
		return err
	}
	return nil
}

func (c *CancelSubscriptionScheduleResponse) GetHTTPMeta() types.HTTPMetadata {
	if c == nil {
		return types.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *CancelSubscriptionScheduleResponse) GetCancelScheduleResponse() *types.CancelScheduleResponse {
	if c == nil {
		return nil
	}
	return c.CancelScheduleResponse
}
