// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package dtos

import (
	"github.com/tirdad-billing/go-sdk/v2/internal/utils"
	"github.com/tirdad-billing/go-sdk/v2/models/types"
)

type CancelSubscriptionRequest struct {
	// Subscription ID
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// Cancel Subscription Request
	Body types.CancelSubscriptionRequest `request:"mediaType=application/json"`
}

func (c CancelSubscriptionRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CancelSubscriptionRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, []string{"id", "body"}); err != nil {
		return err
	}
	return nil
}

func (c *CancelSubscriptionRequest) GetID() string {
	if c == nil {
		return ""
	}
	return c.ID
}

func (c *CancelSubscriptionRequest) GetBody() types.CancelSubscriptionRequest {
	if c == nil {
		return types.CancelSubscriptionRequest{}
	}
	return c.Body
}

type CancelSubscriptionResponse struct {
	HTTPMeta types.HTTPMetadata `json:"-"`
	// OK
	CancelSubscriptionResponse *types.CancelSubscriptionResponse
}

func (c CancelSubscriptionResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CancelSubscriptionResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, []string{"HttpMeta"}); err != nil {
		return err
	}
	return nil
}

func (c *CancelSubscriptionResponse) GetHTTPMeta() types.HTTPMetadata {
	if c == nil {
		return types.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *CancelSubscriptionResponse) GetCancelSubscriptionResponse() *types.CancelSubscriptionResponse {
	if c == nil {
		return nil
	}
	return c.CancelSubscriptionResponse
}
