// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package dtos

import (
	"github.com/tirdad-billing/go-sdk/v2/internal/utils"
	"github.com/tirdad-billing/go-sdk/v2/models/types"
)

type CloneEnvironmentRequest struct {
	// Source Environment ID
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// Clone configuration
	Body types.CloneEnvironmentRequest `request:"mediaType=application/json"`
}

func (c CloneEnvironmentRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CloneEnvironmentRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, []string{"id", "body"}); err != nil {
		return err
	}
	return nil
}

func (c *CloneEnvironmentRequest) GetID() string {
	if c == nil {
		return ""
	}
	return c.ID
}

func (c *CloneEnvironmentRequest) GetBody() types.CloneEnvironmentRequest {
	if c == nil {
		return types.CloneEnvironmentRequest{}
	}
	return c.Body
}

type CloneEnvironmentResponse struct {
	HTTPMeta types.HTTPMetadata `json:"-"`
	// Accepted
	ModelsTemporalWorkflowResult *types.ModelsTemporalWorkflowResult
}

func (c CloneEnvironmentResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CloneEnvironmentResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, []string{"HttpMeta"}); err != nil {
		return err
	}
	return nil
}

func (c *CloneEnvironmentResponse) GetHTTPMeta() types.HTTPMetadata {
	if c == nil {
		return types.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *CloneEnvironmentResponse) GetModelsTemporalWorkflowResult() *types.ModelsTemporalWorkflowResult {
	if c == nil {
		return nil
	}
	return c.ModelsTemporalWorkflowResult
}
