// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package dtos

import (
	"github.com/tirdad-billing/go-sdk/v2/internal/utils"
	"github.com/tirdad-billing/go-sdk/v2/models/types"
)

type CreateWalletResponse struct {
	HTTPMeta types.HTTPMetadata `json:"-"`
	// OK
	WalletResponse *types.WalletResponse
}

func (c CreateWalletResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateWalletResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, []string{"HttpMeta"}); err != nil {
		return err
	}
	return nil
}

func (c *CreateWalletResponse) GetHTTPMeta() types.HTTPMetadata {
	if c == nil {
		return types.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *CreateWalletResponse) GetWalletResponse() *types.WalletResponse {
	if c == nil {
		return nil
	}
	return c.WalletResponse
}
