// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package dtos

import (
	"github.com/tirdad-billing/go-sdk/v2/internal/utils"
	"github.com/tirdad-billing/go-sdk/v2/models/types"
)

type CreateCreditGrantResponse struct {
	HTTPMeta types.HTTPMetadata `json:"-"`
	// Created
	CreditGrantResponse *types.CreditGrantResponse
}

func (c CreateCreditGrantResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateCreditGrantResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, []string{"HttpMeta"}); err != nil {
		return err
	}
	return nil
}

func (c *CreateCreditGrantResponse) GetHTTPMeta() types.HTTPMetadata {
	if c == nil {
		return types.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *CreateCreditGrantResponse) GetCreditGrantResponse() *types.CreditGrantResponse {
	if c == nil {
		return nil
	}
	return c.CreditGrantResponse
}
