// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package dtos

import (
	"github.com/tirdad-billing/go-sdk/v2/internal/utils"
	"github.com/tirdad-billing/go-sdk/v2/models/types"
)

type CreateInvoiceResponse struct {
	HTTPMeta types.HTTPMetadata `json:"-"`
	// Created
	InvoiceResponse *types.InvoiceResponse
}

func (c CreateInvoiceResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateInvoiceResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, []string{"HttpMeta"}); err != nil {
		return err
	}
	return nil
}

func (c *CreateInvoiceResponse) GetHTTPMeta() types.HTTPMetadata {
	if c == nil {
		return types.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *CreateInvoiceResponse) GetInvoiceResponse() *types.InvoiceResponse {
	if c == nil {
		return nil
	}
	return c.InvoiceResponse
}
