// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package dtos

import (
	"github.com/tirdad-billing/go-sdk/v2/internal/utils"
	"github.com/tirdad-billing/go-sdk/v2/models/types"
)

type DeleteCostsheetRequest struct {
	// Costsheet ID
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (d DeleteCostsheetRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DeleteCostsheetRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, []string{"id"}); err != nil {
		return err
	}
	return nil
}

func (d *DeleteCostsheetRequest) GetID() string {
	if d == nil {
		return ""
	}
	return d.ID
}

type DeleteCostsheetResponse struct {
	HTTPMeta types.HTTPMetadata `json:"-"`
	// Costsheet deleted
	DeleteCostsheetResponse *types.DeleteCostsheetResponse
}

func (d DeleteCostsheetResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DeleteCostsheetResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, []string{"HttpMeta"}); err != nil {
		return err
	}
	return nil
}

func (d *DeleteCostsheetResponse) GetHTTPMeta() types.HTTPMetadata {
	if d == nil {
		return types.HTTPMetadata{}
	}
	return d.HTTPMeta
}

func (d *DeleteCostsheetResponse) GetDeleteCostsheetResponse() *types.DeleteCostsheetResponse {
	if d == nil {
		return nil
	}
	return d.DeleteCostsheetResponse
}
