// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package dtos

import (
	"github.com/tirdad-billing/go-sdk/v2/internal/utils"
	"github.com/tirdad-billing/go-sdk/v2/models/types"
)

type DeleteAddonRequest struct {
	// Addon ID
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (d DeleteAddonRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DeleteAddonRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, []string{"id"}); err != nil {
		return err
	}
	return nil
}

func (d *DeleteAddonRequest) GetID() string {
	if d == nil {
		return ""
	}
	return d.ID
}

type DeleteAddonResponse struct {
	HTTPMeta types.HTTPMetadata `json:"-"`
	// OK
	SuccessResponse *types.SuccessResponse
}

func (d DeleteAddonResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DeleteAddonResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, []string{"HttpMeta"}); err != nil {
		return err
	}
	return nil
}

func (d *DeleteAddonResponse) GetHTTPMeta() types.HTTPMetadata {
	if d == nil {
		return types.HTTPMetadata{}
	}
	return d.HTTPMeta
}

func (d *DeleteAddonResponse) GetSuccessResponse() *types.SuccessResponse {
	if d == nil {
		return nil
	}
	return d.SuccessResponse
}
