// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package dtos

import (
	"github.com/tirdad-billing/go-sdk/v2/internal/utils"
	"github.com/tirdad-billing/go-sdk/v2/models/types"
)

type ExecuteSubscriptionModifyRequest struct {
	// Subscription ID
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// Modification request
	Body types.ExecuteSubscriptionModifyRequest `request:"mediaType=application/json"`
}

func (e ExecuteSubscriptionModifyRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *ExecuteSubscriptionModifyRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, []string{"id", "body"}); err != nil {
		return err
	}
	return nil
}

func (e *ExecuteSubscriptionModifyRequest) GetID() string {
	if e == nil {
		return ""
	}
	return e.ID
}

func (e *ExecuteSubscriptionModifyRequest) GetBody() types.ExecuteSubscriptionModifyRequest {
	if e == nil {
		return types.ExecuteSubscriptionModifyRequest{}
	}
	return e.Body
}

type ExecuteSubscriptionModifyResponse struct {
	HTTPMeta types.HTTPMetadata `json:"-"`
	// OK
	SubscriptionModifyResponse *types.SubscriptionModifyResponse
}

func (e ExecuteSubscriptionModifyResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *ExecuteSubscriptionModifyResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, []string{"HttpMeta"}); err != nil {
		return err
	}
	return nil
}

func (e *ExecuteSubscriptionModifyResponse) GetHTTPMeta() types.HTTPMetadata {
	if e == nil {
		return types.HTTPMetadata{}
	}
	return e.HTTPMeta
}

func (e *ExecuteSubscriptionModifyResponse) GetSubscriptionModifyResponse() *types.SubscriptionModifyResponse {
	if e == nil {
		return nil
	}
	return e.SubscriptionModifyResponse
}
