// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package dtos

import (
	"github.com/tirdad-billing/go-sdk/v2/internal/utils"
	"github.com/tirdad-billing/go-sdk/v2/models/types"
)

type ExecuteSubscriptionChangeRequest struct {
	// Subscription ID
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// Subscription change request
	Body types.SubscriptionChangeRequest `request:"mediaType=application/json"`
}

func (e ExecuteSubscriptionChangeRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *ExecuteSubscriptionChangeRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, []string{"id", "body"}); err != nil {
		return err
	}
	return nil
}

func (e *ExecuteSubscriptionChangeRequest) GetID() string {
	if e == nil {
		return ""
	}
	return e.ID
}

func (e *ExecuteSubscriptionChangeRequest) GetBody() types.SubscriptionChangeRequest {
	if e == nil {
		return types.SubscriptionChangeRequest{}
	}
	return e.Body
}

type ExecuteSubscriptionChangeResponse struct {
	HTTPMeta types.HTTPMetadata `json:"-"`
	// OK
	SubscriptionChangeExecuteResponse *types.SubscriptionChangeExecuteResponse
}

func (e ExecuteSubscriptionChangeResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *ExecuteSubscriptionChangeResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, []string{"HttpMeta"}); err != nil {
		return err
	}
	return nil
}

func (e *ExecuteSubscriptionChangeResponse) GetHTTPMeta() types.HTTPMetadata {
	if e == nil {
		return types.HTTPMetadata{}
	}
	return e.HTTPMeta
}

func (e *ExecuteSubscriptionChangeResponse) GetSubscriptionChangeExecuteResponse() *types.SubscriptionChangeExecuteResponse {
	if e == nil {
		return nil
	}
	return e.SubscriptionChangeExecuteResponse
}
