// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package dtos

import (
	"github.com/tirdad-billing/go-sdk/v2/internal/utils"
	"github.com/tirdad-billing/go-sdk/v2/models/types"
)

type GetAddonCreditGrantsRequest struct {
	// Addon ID
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (g GetAddonCreditGrantsRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetAddonCreditGrantsRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, []string{"id"}); err != nil {
		return err
	}
	return nil
}

func (g *GetAddonCreditGrantsRequest) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

type GetAddonCreditGrantsResponse struct {
	HTTPMeta types.HTTPMetadata `json:"-"`
	// OK
	ListCreditGrantsResponse *types.ListCreditGrantsResponse
}

func (g GetAddonCreditGrantsResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetAddonCreditGrantsResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, []string{"HttpMeta"}); err != nil {
		return err
	}
	return nil
}

func (g *GetAddonCreditGrantsResponse) GetHTTPMeta() types.HTTPMetadata {
	if g == nil {
		return types.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetAddonCreditGrantsResponse) GetListCreditGrantsResponse() *types.ListCreditGrantsResponse {
	if g == nil {
		return nil
	}
	return g.ListCreditGrantsResponse
}
