// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package dtos

import (
	"github.com/tirdad-billing/go-sdk/v2/internal/utils"
	"github.com/tirdad-billing/go-sdk/v2/models/types"
)

type GetCreditNoteRequest struct {
	// Credit note ID
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (g GetCreditNoteRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetCreditNoteRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, []string{"id"}); err != nil {
		return err
	}
	return nil
}

func (g *GetCreditNoteRequest) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

type GetCreditNoteResponse struct {
	HTTPMeta types.HTTPMetadata `json:"-"`
	// OK
	CreditNoteResponse *types.CreditNoteResponse
}

func (g GetCreditNoteResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetCreditNoteResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, []string{"HttpMeta"}); err != nil {
		return err
	}
	return nil
}

func (g *GetCreditNoteResponse) GetHTTPMeta() types.HTTPMetadata {
	if g == nil {
		return types.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetCreditNoteResponse) GetCreditNoteResponse() *types.CreditNoteResponse {
	if g == nil {
		return nil
	}
	return g.CreditNoteResponse
}
