// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package dtos

import (
	"github.com/tirdad-billing/go-sdk/v2/internal/utils"
	"github.com/tirdad-billing/go-sdk/v2/models/types"
)

type GetCustomerByExternalIDRequest struct {
	// Customer External ID
	ExternalID string `pathParam:"style=simple,explode=false,name=external_id"`
}

func (g GetCustomerByExternalIDRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetCustomerByExternalIDRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, []string{"external_id"}); err != nil {
		return err
	}
	return nil
}

func (g *GetCustomerByExternalIDRequest) GetExternalID() string {
	if g == nil {
		return ""
	}
	return g.ExternalID
}

type GetCustomerByExternalIDResponse struct {
	HTTPMeta types.HTTPMetadata `json:"-"`
	// OK
	CustomerResponse *types.CustomerResponse
}

func (g GetCustomerByExternalIDResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetCustomerByExternalIDResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, []string{"HttpMeta"}); err != nil {
		return err
	}
	return nil
}

func (g *GetCustomerByExternalIDResponse) GetHTTPMeta() types.HTTPMetadata {
	if g == nil {
		return types.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetCustomerByExternalIDResponse) GetCustomerResponse() *types.CustomerResponse {
	if g == nil {
		return nil
	}
	return g.CustomerResponse
}
