// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package dtos

import (
	"github.com/tirdad-billing/go-sdk/v2/internal/utils"
	"github.com/tirdad-billing/go-sdk/v2/models/types"
)

type GetEntityIntegrationMappingsRequest struct {
	// Entity type (customer, plan, invoice, subscription, payment, credit_note, addon, item, item_price, price)
	EntityType string `queryParam:"style=form,explode=true,name=entity_type"`
	// Entity ID
	EntityID string `queryParam:"style=form,explode=true,name=entity_id"`
}

func (g GetEntityIntegrationMappingsRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetEntityIntegrationMappingsRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, []string{"entity_type", "entity_id"}); err != nil {
		return err
	}
	return nil
}

func (g *GetEntityIntegrationMappingsRequest) GetEntityType() string {
	if g == nil {
		return ""
	}
	return g.EntityType
}

func (g *GetEntityIntegrationMappingsRequest) GetEntityID() string {
	if g == nil {
		return ""
	}
	return g.EntityID
}

type GetEntityIntegrationMappingsResponse struct {
	HTTPMeta types.HTTPMetadata `json:"-"`
	// OK
	ListEntityIntegrationMappingsResponse *types.ListEntityIntegrationMappingsResponse
}

func (g GetEntityIntegrationMappingsResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetEntityIntegrationMappingsResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, []string{"HttpMeta"}); err != nil {
		return err
	}
	return nil
}

func (g *GetEntityIntegrationMappingsResponse) GetHTTPMeta() types.HTTPMetadata {
	if g == nil {
		return types.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetEntityIntegrationMappingsResponse) GetListEntityIntegrationMappingsResponse() *types.ListEntityIntegrationMappingsResponse {
	if g == nil {
		return nil
	}
	return g.ListEntityIntegrationMappingsResponse
}
