// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package dtos

import (
	"github.com/tirdad-billing/go-sdk/v2/internal/utils"
	"github.com/tirdad-billing/go-sdk/v2/models/types"
)

type GetInvoiceRequest struct {
	// Invoice ID
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// Include source-level price breakdown for usage line items (legacy)
	ExpandBySource *bool `queryParam:"style=form,explode=true,name=expand_by_source"`
	// Group usage breakdown by specified fields (e.g., source, feature_id, properties.org_id)
	GroupBy []string `queryParam:"style=form,explode=false,name=group_by"`
	// Comma-separated related fields to include. Supports 'tax_applied.tax_rate' to attach rate details to each applied tax.
	Expand *string `queryParam:"style=form,explode=true,name=expand"`
}

func (g GetInvoiceRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetInvoiceRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, []string{"id"}); err != nil {
		return err
	}
	return nil
}

func (g *GetInvoiceRequest) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

func (g *GetInvoiceRequest) GetExpandBySource() *bool {
	if g == nil {
		return nil
	}
	return g.ExpandBySource
}

func (g *GetInvoiceRequest) GetGroupBy() []string {
	if g == nil {
		return nil
	}
	return g.GroupBy
}

func (g *GetInvoiceRequest) GetExpand() *string {
	if g == nil {
		return nil
	}
	return g.Expand
}

type GetInvoiceResponse struct {
	HTTPMeta types.HTTPMetadata `json:"-"`
	// OK
	InvoiceResponse *types.InvoiceResponse
}

func (g GetInvoiceResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetInvoiceResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, []string{"HttpMeta"}); err != nil {
		return err
	}
	return nil
}

func (g *GetInvoiceResponse) GetHTTPMeta() types.HTTPMetadata {
	if g == nil {
		return types.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetInvoiceResponse) GetInvoiceResponse() *types.InvoiceResponse {
	if g == nil {
		return nil
	}
	return g.InvoiceResponse
}
