// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package dtos

import (
	"github.com/tirdad-billing/go-sdk/v2/internal/utils"
	"github.com/tirdad-billing/go-sdk/v2/models/types"
)

type GetPaymentRequest struct {
	// Payment ID
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (g GetPaymentRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetPaymentRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, []string{"id"}); err != nil {
		return err
	}
	return nil
}

func (g *GetPaymentRequest) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

type GetPaymentResponse struct {
	HTTPMeta types.HTTPMetadata `json:"-"`
	// Payment details
	PaymentResponse *types.PaymentResponse
}

func (g GetPaymentResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetPaymentResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, []string{"HttpMeta"}); err != nil {
		return err
	}
	return nil
}

func (g *GetPaymentResponse) GetHTTPMeta() types.HTTPMetadata {
	if g == nil {
		return types.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetPaymentResponse) GetPaymentResponse() *types.PaymentResponse {
	if g == nil {
		return nil
	}
	return g.PaymentResponse
}
