// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package dtos

import (
	"github.com/tirdad-billing/go-sdk/v2/internal/utils"
	"github.com/tirdad-billing/go-sdk/v2/models/types"
)

type GetRbacRoleRequest struct {
	// Role ID
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (g GetRbacRoleRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetRbacRoleRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, []string{"id"}); err != nil {
		return err
	}
	return nil
}

func (g *GetRbacRoleRequest) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

type GetRbacRoleResponse struct {
	HTTPMeta types.HTTPMetadata `json:"-"`
	// Role details
	Object map[string]any
}

func (g GetRbacRoleResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetRbacRoleResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, []string{"HttpMeta"}); err != nil {
		return err
	}
	return nil
}

func (g *GetRbacRoleResponse) GetHTTPMeta() types.HTTPMetadata {
	if g == nil {
		return types.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetRbacRoleResponse) GetObject() map[string]any {
	if g == nil {
		return nil
	}
	return g.Object
}
