// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package dtos

import (
	"github.com/tirdad-billing/go-sdk/v2/internal/utils"
	"github.com/tirdad-billing/go-sdk/v2/models/types"
)

type GetSubscriptionUpcomingGrantsRequest struct {
	// Subscription ID
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (g GetSubscriptionUpcomingGrantsRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetSubscriptionUpcomingGrantsRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, []string{"id"}); err != nil {
		return err
	}
	return nil
}

func (g *GetSubscriptionUpcomingGrantsRequest) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

type GetSubscriptionUpcomingGrantsResponse struct {
	HTTPMeta types.HTTPMetadata `json:"-"`
	// OK
	ListCreditGrantApplicationsResponse *types.ListCreditGrantApplicationsResponse
}

func (g GetSubscriptionUpcomingGrantsResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetSubscriptionUpcomingGrantsResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, []string{"HttpMeta"}); err != nil {
		return err
	}
	return nil
}

func (g *GetSubscriptionUpcomingGrantsResponse) GetHTTPMeta() types.HTTPMetadata {
	if g == nil {
		return types.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetSubscriptionUpcomingGrantsResponse) GetListCreditGrantApplicationsResponse() *types.ListCreditGrantApplicationsResponse {
	if g == nil {
		return nil
	}
	return g.ListCreditGrantApplicationsResponse
}
