// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package dtos

import (
	"github.com/tirdad-billing/go-sdk/v2/internal/utils"
	"github.com/tirdad-billing/go-sdk/v2/models/types"
)

type GetSubscriptionRequest struct {
	// Subscription ID
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (g GetSubscriptionRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetSubscriptionRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, []string{"id"}); err != nil {
		return err
	}
	return nil
}

func (g *GetSubscriptionRequest) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

type GetSubscriptionResponse struct {
	HTTPMeta types.HTTPMetadata `json:"-"`
	// OK
	SubscriptionResponse *types.SubscriptionResponse
}

func (g GetSubscriptionResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetSubscriptionResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, []string{"HttpMeta"}); err != nil {
		return err
	}
	return nil
}

func (g *GetSubscriptionResponse) GetHTTPMeta() types.HTTPMetadata {
	if g == nil {
		return types.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetSubscriptionResponse) GetSubscriptionResponse() *types.SubscriptionResponse {
	if g == nil {
		return nil
	}
	return g.SubscriptionResponse
}
