// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package dtos

import (
	"github.com/tirdad-billing/go-sdk/v2/internal/utils"
	"github.com/tirdad-billing/go-sdk/v2/models/types"
)

type GetSubscriptionV2Request struct {
	// Subscription ID
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// Comma-separated list of fields to expand (e.g., 'subscription_line_items,prices,plan')
	Expand *string `queryParam:"style=form,explode=true,name=expand"`
}

func (g GetSubscriptionV2Request) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetSubscriptionV2Request) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, []string{"id"}); err != nil {
		return err
	}
	return nil
}

func (g *GetSubscriptionV2Request) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

func (g *GetSubscriptionV2Request) GetExpand() *string {
	if g == nil {
		return nil
	}
	return g.Expand
}

// #region class-body-getsubscriptionv2request
// #endregion class-body-getsubscriptionv2request

type GetSubscriptionV2Response struct {
	HTTPMeta types.HTTPMetadata `json:"-"`
	// OK
	SubscriptionResponseV2 *types.SubscriptionResponseV2
}

func (g GetSubscriptionV2Response) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetSubscriptionV2Response) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, []string{"HttpMeta"}); err != nil {
		return err
	}
	return nil
}

func (g *GetSubscriptionV2Response) GetHTTPMeta() types.HTTPMetadata {
	if g == nil {
		return types.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetSubscriptionV2Response) GetSubscriptionResponseV2() *types.SubscriptionResponseV2 {
	if g == nil {
		return nil
	}
	return g.SubscriptionResponseV2
}

// #region class-body-getsubscriptionv2response
// #endregion class-body-getsubscriptionv2response
