// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package dtos

import (
	"github.com/tirdad-billing/go-sdk/v2/internal/utils"
	"github.com/tirdad-billing/go-sdk/v2/models/types"
)

type GetSubscriptionScheduleRequest struct {
	// Schedule ID
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (g GetSubscriptionScheduleRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetSubscriptionScheduleRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, []string{"id"}); err != nil {
		return err
	}
	return nil
}

func (g *GetSubscriptionScheduleRequest) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

type GetSubscriptionScheduleResponse struct {
	HTTPMeta types.HTTPMetadata `json:"-"`
	// OK
	SubscriptionScheduleResponse *types.SubscriptionScheduleResponse
}

func (g GetSubscriptionScheduleResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetSubscriptionScheduleResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, []string{"HttpMeta"}); err != nil {
		return err
	}
	return nil
}

func (g *GetSubscriptionScheduleResponse) GetHTTPMeta() types.HTTPMetadata {
	if g == nil {
		return types.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetSubscriptionScheduleResponse) GetSubscriptionScheduleResponse() *types.SubscriptionScheduleResponse {
	if g == nil {
		return nil
	}
	return g.SubscriptionScheduleResponse
}
