// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package dtos

import (
	"github.com/tirdad-billing/go-sdk/v2/internal/utils"
	"github.com/tirdad-billing/go-sdk/v2/models/types"
)

type GetTaskRequest struct {
	// Task ID
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (g GetTaskRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetTaskRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, []string{"id"}); err != nil {
		return err
	}
	return nil
}

func (g *GetTaskRequest) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

type GetTaskResponse struct {
	HTTPMeta types.HTTPMetadata `json:"-"`
	// OK
	TaskResponse *types.TaskResponse
}

func (g GetTaskResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetTaskResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, []string{"HttpMeta"}); err != nil {
		return err
	}
	return nil
}

func (g *GetTaskResponse) GetHTTPMeta() types.HTTPMetadata {
	if g == nil {
		return types.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetTaskResponse) GetTaskResponse() *types.TaskResponse {
	if g == nil {
		return nil
	}
	return g.TaskResponse
}
