// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package dtos

import (
	"github.com/tirdad-billing/go-sdk/v2/internal/utils"
	"github.com/tirdad-billing/go-sdk/v2/models/types"
)

type GetTenantByIDRequest struct {
	// Tenant ID
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (g GetTenantByIDRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetTenantByIDRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, []string{"id"}); err != nil {
		return err
	}
	return nil
}

func (g *GetTenantByIDRequest) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

type GetTenantByIDResponse struct {
	HTTPMeta types.HTTPMetadata `json:"-"`
	// Tenant details
	TenantResponse *types.TenantResponse
}

func (g GetTenantByIDResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetTenantByIDResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, []string{"HttpMeta"}); err != nil {
		return err
	}
	return nil
}

func (g *GetTenantByIDResponse) GetHTTPMeta() types.HTTPMetadata {
	if g == nil {
		return types.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetTenantByIDResponse) GetTenantResponse() *types.TenantResponse {
	if g == nil {
		return nil
	}
	return g.TenantResponse
}
