// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package dtos

import (
	"github.com/tirdad-billing/go-sdk/v2/internal/utils"
	"github.com/tirdad-billing/go-sdk/v2/models/types"
)

type GetWalletsByCustomerIDRequest struct {
	// Customer ID
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (g GetWalletsByCustomerIDRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetWalletsByCustomerIDRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, []string{"id"}); err != nil {
		return err
	}
	return nil
}

func (g *GetWalletsByCustomerIDRequest) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

type GetWalletsByCustomerIDResponse struct {
	HTTPMeta types.HTTPMetadata `json:"-"`
	// OK
	WalletResponses []types.WalletResponse
}

func (g GetWalletsByCustomerIDResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetWalletsByCustomerIDResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, []string{"HttpMeta"}); err != nil {
		return err
	}
	return nil
}

func (g *GetWalletsByCustomerIDResponse) GetHTTPMeta() types.HTTPMetadata {
	if g == nil {
		return types.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetWalletsByCustomerIDResponse) GetWalletResponses() []types.WalletResponse {
	if g == nil {
		return nil
	}
	return g.WalletResponses
}
