// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package dtos

import (
	"encoding/json"
	"fmt"
	"github.com/tirdad-billing/go-sdk/v2/internal/utils"
	"github.com/tirdad-billing/go-sdk/v2/models/types"
)

type EntityType string

const (
	EntityTypeEvents    EntityType = "EVENTS"
	EntityTypePrices    EntityType = "PRICES"
	EntityTypeCustomers EntityType = "CUSTOMERS"
	EntityTypeFeatures  EntityType = "FEATURES"
)

func (e EntityType) ToPointer() *EntityType {
	return &e
}
func (e *EntityType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "EVENTS":
		fallthrough
	case "PRICES":
		fallthrough
	case "CUSTOMERS":
		fallthrough
	case "FEATURES":
		*e = EntityType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for EntityType: %v", v)
	}
}

type ListTasksOrder string

const (
	ListTasksOrderAsc  ListTasksOrder = "asc"
	ListTasksOrderDesc ListTasksOrder = "desc"
)

func (e ListTasksOrder) ToPointer() *ListTasksOrder {
	return &e
}
func (e *ListTasksOrder) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "asc":
		fallthrough
	case "desc":
		*e = ListTasksOrder(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ListTasksOrder: %v", v)
	}
}

type ListTasksStatus string

const (
	ListTasksStatusPublished ListTasksStatus = "published"
	ListTasksStatusDeleted   ListTasksStatus = "deleted"
	ListTasksStatusArchived  ListTasksStatus = "archived"
)

func (e ListTasksStatus) ToPointer() *ListTasksStatus {
	return &e
}
func (e *ListTasksStatus) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "published":
		fallthrough
	case "deleted":
		fallthrough
	case "archived":
		*e = ListTasksStatus(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ListTasksStatus: %v", v)
	}
}

type TaskStatus string

const (
	TaskStatusPending    TaskStatus = "PENDING"
	TaskStatusProcessing TaskStatus = "PROCESSING"
	TaskStatusCompleted  TaskStatus = "COMPLETED"
	TaskStatusFailed     TaskStatus = "FAILED"
)

func (e TaskStatus) ToPointer() *TaskStatus {
	return &e
}
func (e *TaskStatus) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "PENDING":
		fallthrough
	case "PROCESSING":
		fallthrough
	case "COMPLETED":
		fallthrough
	case "FAILED":
		*e = TaskStatus(v)
		return nil
	default:
		return fmt.Errorf("invalid value for TaskStatus: %v", v)
	}
}

type TaskType string

const (
	TaskTypeImport TaskType = "IMPORT"
	TaskTypeExport TaskType = "EXPORT"
)

func (e TaskType) ToPointer() *TaskType {
	return &e
}
func (e *TaskType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "IMPORT":
		fallthrough
	case "EXPORT":
		*e = TaskType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for TaskType: %v", v)
	}
}

type ListTasksRequest struct {
	CreatedBy       *string          `queryParam:"style=form,explode=true,name=created_by"`
	EndTime         *string          `queryParam:"style=form,explode=true,name=end_time"`
	EntityType      *EntityType      `queryParam:"style=form,explode=true,name=entity_type"`
	Expand          *string          `queryParam:"style=form,explode=true,name=expand"`
	Limit           *int64           `queryParam:"style=form,explode=true,name=limit"`
	Offset          *int64           `queryParam:"style=form,explode=true,name=offset"`
	Order           *ListTasksOrder  `queryParam:"style=form,explode=true,name=order"`
	ScheduledTaskID *string          `queryParam:"style=form,explode=true,name=scheduled_task_id"`
	Sort            *string          `queryParam:"style=form,explode=true,name=sort"`
	StartTime       *string          `queryParam:"style=form,explode=true,name=start_time"`
	Status          *ListTasksStatus `queryParam:"style=form,explode=true,name=status"`
	TaskStatus      *TaskStatus      `queryParam:"style=form,explode=true,name=task_status"`
	TaskType        *TaskType        `queryParam:"style=form,explode=true,name=task_type"`
}

func (l ListTasksRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListTasksRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListTasksRequest) GetCreatedBy() *string {
	if l == nil {
		return nil
	}
	return l.CreatedBy
}

func (l *ListTasksRequest) GetEndTime() *string {
	if l == nil {
		return nil
	}
	return l.EndTime
}

func (l *ListTasksRequest) GetEntityType() *EntityType {
	if l == nil {
		return nil
	}
	return l.EntityType
}

func (l *ListTasksRequest) GetExpand() *string {
	if l == nil {
		return nil
	}
	return l.Expand
}

func (l *ListTasksRequest) GetLimit() *int64 {
	if l == nil {
		return nil
	}
	return l.Limit
}

func (l *ListTasksRequest) GetOffset() *int64 {
	if l == nil {
		return nil
	}
	return l.Offset
}

func (l *ListTasksRequest) GetOrder() *ListTasksOrder {
	if l == nil {
		return nil
	}
	return l.Order
}

func (l *ListTasksRequest) GetScheduledTaskID() *string {
	if l == nil {
		return nil
	}
	return l.ScheduledTaskID
}

func (l *ListTasksRequest) GetSort() *string {
	if l == nil {
		return nil
	}
	return l.Sort
}

func (l *ListTasksRequest) GetStartTime() *string {
	if l == nil {
		return nil
	}
	return l.StartTime
}

func (l *ListTasksRequest) GetStatus() *ListTasksStatus {
	if l == nil {
		return nil
	}
	return l.Status
}

func (l *ListTasksRequest) GetTaskStatus() *TaskStatus {
	if l == nil {
		return nil
	}
	return l.TaskStatus
}

func (l *ListTasksRequest) GetTaskType() *TaskType {
	if l == nil {
		return nil
	}
	return l.TaskType
}

type ListTasksResponse struct {
	HTTPMeta types.HTTPMetadata `json:"-"`
	// OK
	ListTasksResponse *types.ListTasksResponse
}

func (l ListTasksResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListTasksResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, []string{"HttpMeta"}); err != nil {
		return err
	}
	return nil
}

func (l *ListTasksResponse) GetHTTPMeta() types.HTTPMetadata {
	if l == nil {
		return types.HTTPMetadata{}
	}
	return l.HTTPMeta
}

func (l *ListTasksResponse) GetListTasksResponse() *types.ListTasksResponse {
	if l == nil {
		return nil
	}
	return l.ListTasksResponse
}
