// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package dtos

import (
	"github.com/tirdad-billing/go-sdk/v2/internal/utils"
	"github.com/tirdad-billing/go-sdk/v2/models/types"
)

type ListCouponAssociationsRequest struct {
	// Filter by subscription IDs (max 100)
	SubscriptionIds []string `queryParam:"style=form,explode=false,name=subscription_ids"`
	// Filter by coupon IDs (max 100)
	CouponIds []string `queryParam:"style=form,explode=false,name=coupon_ids"`
	// Return only currently active associations
	ActiveOnly *bool `queryParam:"style=form,explode=true,name=active_only"`
	// Page size
	Limit *int64 `queryParam:"style=form,explode=true,name=limit"`
	// Page offset
	Offset *int64 `queryParam:"style=form,explode=true,name=offset"`
}

func (l ListCouponAssociationsRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListCouponAssociationsRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListCouponAssociationsRequest) GetSubscriptionIds() []string {
	if l == nil {
		return nil
	}
	return l.SubscriptionIds
}

func (l *ListCouponAssociationsRequest) GetCouponIds() []string {
	if l == nil {
		return nil
	}
	return l.CouponIds
}

func (l *ListCouponAssociationsRequest) GetActiveOnly() *bool {
	if l == nil {
		return nil
	}
	return l.ActiveOnly
}

func (l *ListCouponAssociationsRequest) GetLimit() *int64 {
	if l == nil {
		return nil
	}
	return l.Limit
}

func (l *ListCouponAssociationsRequest) GetOffset() *int64 {
	if l == nil {
		return nil
	}
	return l.Offset
}

type ListCouponAssociationsResponse struct {
	HTTPMeta types.HTTPMetadata `json:"-"`
	// OK
	ListCouponAssociationsResponse *types.ListCouponAssociationsResponse
}

func (l ListCouponAssociationsResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListCouponAssociationsResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, []string{"HttpMeta"}); err != nil {
		return err
	}
	return nil
}

func (l *ListCouponAssociationsResponse) GetHTTPMeta() types.HTTPMetadata {
	if l == nil {
		return types.HTTPMetadata{}
	}
	return l.HTTPMeta
}

func (l *ListCouponAssociationsResponse) GetListCouponAssociationsResponse() *types.ListCouponAssociationsResponse {
	if l == nil {
		return nil
	}
	return l.ListCouponAssociationsResponse
}
