// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package dtos

import (
	"github.com/tirdad-billing/go-sdk/v2/internal/utils"
	"github.com/tirdad-billing/go-sdk/v2/models/types"
)

type ListAllSubscriptionSchedulesRequest struct {
	// Filter to pending schedules only
	PendingOnly *bool `queryParam:"style=form,explode=true,name=pending_only"`
	// Filter by subscription ID
	SubscriptionID *string `queryParam:"style=form,explode=true,name=subscription_id"`
	// Limit results
	Limit *int64 `queryParam:"style=form,explode=true,name=limit"`
	// Offset for pagination
	Offset *int64 `queryParam:"style=form,explode=true,name=offset"`
}

func (l ListAllSubscriptionSchedulesRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListAllSubscriptionSchedulesRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListAllSubscriptionSchedulesRequest) GetPendingOnly() *bool {
	if l == nil {
		return nil
	}
	return l.PendingOnly
}

func (l *ListAllSubscriptionSchedulesRequest) GetSubscriptionID() *string {
	if l == nil {
		return nil
	}
	return l.SubscriptionID
}

func (l *ListAllSubscriptionSchedulesRequest) GetLimit() *int64 {
	if l == nil {
		return nil
	}
	return l.Limit
}

func (l *ListAllSubscriptionSchedulesRequest) GetOffset() *int64 {
	if l == nil {
		return nil
	}
	return l.Offset
}

type ListAllSubscriptionSchedulesResponse struct {
	HTTPMeta types.HTTPMetadata `json:"-"`
	// OK
	GetPendingSchedulesResponse *types.GetPendingSchedulesResponse
}

func (l ListAllSubscriptionSchedulesResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListAllSubscriptionSchedulesResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, []string{"HttpMeta"}); err != nil {
		return err
	}
	return nil
}

func (l *ListAllSubscriptionSchedulesResponse) GetHTTPMeta() types.HTTPMetadata {
	if l == nil {
		return types.HTTPMetadata{}
	}
	return l.HTTPMeta
}

func (l *ListAllSubscriptionSchedulesResponse) GetGetPendingSchedulesResponse() *types.GetPendingSchedulesResponse {
	if l == nil {
		return nil
	}
	return l.GetPendingSchedulesResponse
}
