// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package dtos

import (
	"github.com/tirdad-billing/go-sdk/v2/internal/utils"
	"github.com/tirdad-billing/go-sdk/v2/models/types"
)

type PostWebhookEventsSubscriptionPlanChangedResponse struct {
	HTTPMeta types.HTTPMetadata `json:"-"`
	// Webhook payload
	WebhookDtoSubscriptionWebhookPayload *types.WebhookDtoSubscriptionWebhookPayload
}

func (p PostWebhookEventsSubscriptionPlanChangedResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PostWebhookEventsSubscriptionPlanChangedResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, []string{"HttpMeta"}); err != nil {
		return err
	}
	return nil
}

func (p *PostWebhookEventsSubscriptionPlanChangedResponse) GetHTTPMeta() types.HTTPMetadata {
	if p == nil {
		return types.HTTPMetadata{}
	}
	return p.HTTPMeta
}

func (p *PostWebhookEventsSubscriptionPlanChangedResponse) GetWebhookDtoSubscriptionWebhookPayload() *types.WebhookDtoSubscriptionWebhookPayload {
	if p == nil {
		return nil
	}
	return p.WebhookDtoSubscriptionWebhookPayload
}
