// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package dtos

import (
	"github.com/tirdad-billing/go-sdk/v2/internal/utils"
	"github.com/tirdad-billing/go-sdk/v2/models/types"
)

type PostWebhookEventsInvoiceCommunicationTriggeredResponse struct {
	HTTPMeta types.HTTPMetadata `json:"-"`
	// Webhook payload
	WebhookDtoCommunicationWebhookPayload *types.WebhookDtoCommunicationWebhookPayload
}

func (p PostWebhookEventsInvoiceCommunicationTriggeredResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PostWebhookEventsInvoiceCommunicationTriggeredResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, []string{"HttpMeta"}); err != nil {
		return err
	}
	return nil
}

func (p *PostWebhookEventsInvoiceCommunicationTriggeredResponse) GetHTTPMeta() types.HTTPMetadata {
	if p == nil {
		return types.HTTPMetadata{}
	}
	return p.HTTPMeta
}

func (p *PostWebhookEventsInvoiceCommunicationTriggeredResponse) GetWebhookDtoCommunicationWebhookPayload() *types.WebhookDtoCommunicationWebhookPayload {
	if p == nil {
		return nil
	}
	return p.WebhookDtoCommunicationWebhookPayload
}
