// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package dtos

import (
	"github.com/tirdad-billing/go-sdk/v2/internal/utils"
	"github.com/tirdad-billing/go-sdk/v2/models/types"
)

type PostWebhookEventsCheckoutSessionExpiredResponse struct {
	HTTPMeta types.HTTPMetadata `json:"-"`
	// Webhook payload
	WebhookDtoCheckoutSessionWebhookPayload *types.WebhookDtoCheckoutSessionWebhookPayload
}

func (p PostWebhookEventsCheckoutSessionExpiredResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PostWebhookEventsCheckoutSessionExpiredResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, []string{"HttpMeta"}); err != nil {
		return err
	}
	return nil
}

func (p *PostWebhookEventsCheckoutSessionExpiredResponse) GetHTTPMeta() types.HTTPMetadata {
	if p == nil {
		return types.HTTPMetadata{}
	}
	return p.HTTPMeta
}

func (p *PostWebhookEventsCheckoutSessionExpiredResponse) GetWebhookDtoCheckoutSessionWebhookPayload() *types.WebhookDtoCheckoutSessionWebhookPayload {
	if p == nil {
		return nil
	}
	return p.WebhookDtoCheckoutSessionWebhookPayload
}
