// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package dtos

import (
	"github.com/tirdad-billing/go-sdk/v2/internal/utils"
	"github.com/tirdad-billing/go-sdk/v2/models/types"
)

type PostWebhookEventsInvoiceUpdatePaymentResponse struct {
	HTTPMeta types.HTTPMetadata `json:"-"`
	// Webhook payload
	WebhookDtoInvoiceWebhookPayload *types.WebhookDtoInvoiceWebhookPayload
}

func (p PostWebhookEventsInvoiceUpdatePaymentResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PostWebhookEventsInvoiceUpdatePaymentResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, []string{"HttpMeta"}); err != nil {
		return err
	}
	return nil
}

func (p *PostWebhookEventsInvoiceUpdatePaymentResponse) GetHTTPMeta() types.HTTPMetadata {
	if p == nil {
		return types.HTTPMetadata{}
	}
	return p.HTTPMeta
}

func (p *PostWebhookEventsInvoiceUpdatePaymentResponse) GetWebhookDtoInvoiceWebhookPayload() *types.WebhookDtoInvoiceWebhookPayload {
	if p == nil {
		return nil
	}
	return p.WebhookDtoInvoiceWebhookPayload
}
