// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package dtos

import (
	"github.com/tirdad-billing/go-sdk/v2/internal/utils"
	"github.com/tirdad-billing/go-sdk/v2/models/types"
)

type PostWebhookEventsFeatureWalletBalanceAlertResponse struct {
	HTTPMeta types.HTTPMetadata `json:"-"`
	// Webhook payload
	WebhookDtoAlertWebhookPayload *types.WebhookDtoAlertWebhookPayload
}

func (p PostWebhookEventsFeatureWalletBalanceAlertResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PostWebhookEventsFeatureWalletBalanceAlertResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, []string{"HttpMeta"}); err != nil {
		return err
	}
	return nil
}

func (p *PostWebhookEventsFeatureWalletBalanceAlertResponse) GetHTTPMeta() types.HTTPMetadata {
	if p == nil {
		return types.HTTPMetadata{}
	}
	return p.HTTPMeta
}

func (p *PostWebhookEventsFeatureWalletBalanceAlertResponse) GetWebhookDtoAlertWebhookPayload() *types.WebhookDtoAlertWebhookPayload {
	if p == nil {
		return nil
	}
	return p.WebhookDtoAlertWebhookPayload
}
