// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package dtos

import (
	"github.com/tirdad-billing/go-sdk/v2/internal/utils"
	"github.com/tirdad-billing/go-sdk/v2/models/types"
)

type PostWebhookEventsCreditNoteUpdatedResponse struct {
	HTTPMeta types.HTTPMetadata `json:"-"`
	// Webhook payload
	WebhookDtoCreditNoteWebhookPayload *types.WebhookDtoCreditNoteWebhookPayload
}

func (p PostWebhookEventsCreditNoteUpdatedResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PostWebhookEventsCreditNoteUpdatedResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, []string{"HttpMeta"}); err != nil {
		return err
	}
	return nil
}

func (p *PostWebhookEventsCreditNoteUpdatedResponse) GetHTTPMeta() types.HTTPMetadata {
	if p == nil {
		return types.HTTPMetadata{}
	}
	return p.HTTPMeta
}

func (p *PostWebhookEventsCreditNoteUpdatedResponse) GetWebhookDtoCreditNoteWebhookPayload() *types.WebhookDtoCreditNoteWebhookPayload {
	if p == nil {
		return nil
	}
	return p.WebhookDtoCreditNoteWebhookPayload
}
