// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package dtos

import (
	"github.com/tirdad-billing/go-sdk/v2/internal/utils"
	"github.com/tirdad-billing/go-sdk/v2/models/types"
)

type PostWebhookEventsWalletOngoingBalanceDroppedResponse struct {
	HTTPMeta types.HTTPMetadata `json:"-"`
	// Webhook payload
	WebhookDtoWalletWebhookPayload *types.WebhookDtoWalletWebhookPayload
}

func (p PostWebhookEventsWalletOngoingBalanceDroppedResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PostWebhookEventsWalletOngoingBalanceDroppedResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, []string{"HttpMeta"}); err != nil {
		return err
	}
	return nil
}

func (p *PostWebhookEventsWalletOngoingBalanceDroppedResponse) GetHTTPMeta() types.HTTPMetadata {
	if p == nil {
		return types.HTTPMetadata{}
	}
	return p.HTTPMeta
}

func (p *PostWebhookEventsWalletOngoingBalanceDroppedResponse) GetWebhookDtoWalletWebhookPayload() *types.WebhookDtoWalletWebhookPayload {
	if p == nil {
		return nil
	}
	return p.WebhookDtoWalletWebhookPayload
}
