// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package dtos

import (
	"github.com/tirdad-billing/go-sdk/v2/internal/utils"
	"github.com/tirdad-billing/go-sdk/v2/models/types"
)

type PostWebhookEventsSubscriptionSpendThresholdReachedResponse struct {
	HTTPMeta types.HTTPMetadata `json:"-"`
	// Webhook payload
	WebhookDtoSpendAlertEvent *types.WebhookDtoSpendAlertEvent
}

func (p PostWebhookEventsSubscriptionSpendThresholdReachedResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PostWebhookEventsSubscriptionSpendThresholdReachedResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, []string{"HttpMeta"}); err != nil {
		return err
	}
	return nil
}

func (p *PostWebhookEventsSubscriptionSpendThresholdReachedResponse) GetHTTPMeta() types.HTTPMetadata {
	if p == nil {
		return types.HTTPMetadata{}
	}
	return p.HTTPMeta
}

func (p *PostWebhookEventsSubscriptionSpendThresholdReachedResponse) GetWebhookDtoSpendAlertEvent() *types.WebhookDtoSpendAlertEvent {
	if p == nil {
		return nil
	}
	return p.WebhookDtoSpendAlertEvent
}
