// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package dtos

import (
	"github.com/tirdad-billing/go-sdk/v2/internal/utils"
	"github.com/tirdad-billing/go-sdk/v2/models/types"
)

type ProcessCreditNoteRequest struct {
	// Credit note ID
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (p ProcessCreditNoteRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *ProcessCreditNoteRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, []string{"id"}); err != nil {
		return err
	}
	return nil
}

func (p *ProcessCreditNoteRequest) GetID() string {
	if p == nil {
		return ""
	}
	return p.ID
}

type ProcessCreditNoteResponse struct {
	HTTPMeta types.HTTPMetadata `json:"-"`
	// OK
	CreditNoteResponse *types.CreditNoteResponse
}

func (p ProcessCreditNoteResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *ProcessCreditNoteResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, []string{"HttpMeta"}); err != nil {
		return err
	}
	return nil
}

func (p *ProcessCreditNoteResponse) GetHTTPMeta() types.HTTPMetadata {
	if p == nil {
		return types.HTTPMetadata{}
	}
	return p.HTTPMeta
}

func (p *ProcessCreditNoteResponse) GetCreditNoteResponse() *types.CreditNoteResponse {
	if p == nil {
		return nil
	}
	return p.CreditNoteResponse
}
