// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package dtos

import (
	"github.com/tirdad-billing/go-sdk/v2/internal/utils"
	"github.com/tirdad-billing/go-sdk/v2/models/types"
)

type QueryWalletResponse struct {
	HTTPMeta types.HTTPMetadata `json:"-"`
	// OK
	ListResponseDtoWalletResponse *types.ListResponseDtoWalletResponse
}

func (q QueryWalletResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(q, "", false)
}

func (q *QueryWalletResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &q, "", false, []string{"HttpMeta"}); err != nil {
		return err
	}
	return nil
}

func (q *QueryWalletResponse) GetHTTPMeta() types.HTTPMetadata {
	if q == nil {
		return types.HTTPMetadata{}
	}
	return q.HTTPMeta
}

func (q *QueryWalletResponse) GetListResponseDtoWalletResponse() *types.ListResponseDtoWalletResponse {
	if q == nil {
		return nil
	}
	return q.ListResponseDtoWalletResponse
}
