// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package dtos

import (
	"github.com/tirdad-billing/go-sdk/v2/internal/utils"
	"github.com/tirdad-billing/go-sdk/v2/models/types"
)

type QueryPlanResponse struct {
	HTTPMeta types.HTTPMetadata `json:"-"`
	// OK
	ListPlansResponse *types.ListPlansResponse
}

func (q QueryPlanResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(q, "", false)
}

func (q *QueryPlanResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &q, "", false, []string{"HttpMeta"}); err != nil {
		return err
	}
	return nil
}

func (q *QueryPlanResponse) GetHTTPMeta() types.HTTPMetadata {
	if q == nil {
		return types.HTTPMetadata{}
	}
	return q.HTTPMeta
}

func (q *QueryPlanResponse) GetListPlansResponse() *types.ListPlansResponse {
	if q == nil {
		return nil
	}
	return q.ListPlansResponse
}
