// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package dtos

import (
	"github.com/tirdad-billing/go-sdk/v2/internal/utils"
	"github.com/tirdad-billing/go-sdk/v2/models/types"
)

type QuerySubscriptionResponse struct {
	HTTPMeta types.HTTPMetadata `json:"-"`
	// OK
	ListSubscriptionsResponse *types.ListSubscriptionsResponse
}

func (q QuerySubscriptionResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(q, "", false)
}

func (q *QuerySubscriptionResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &q, "", false, []string{"HttpMeta"}); err != nil {
		return err
	}
	return nil
}

func (q *QuerySubscriptionResponse) GetHTTPMeta() types.HTTPMetadata {
	if q == nil {
		return types.HTTPMetadata{}
	}
	return q.HTTPMeta
}

func (q *QuerySubscriptionResponse) GetListSubscriptionsResponse() *types.ListSubscriptionsResponse {
	if q == nil {
		return nil
	}
	return q.ListSubscriptionsResponse
}
