// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package dtos

import (
	"github.com/tirdad-billing/go-sdk/v2/internal/utils"
	"github.com/tirdad-billing/go-sdk/v2/models/types"
)

type QueryWorkflowResponse struct {
	HTTPMeta types.HTTPMetadata `json:"-"`
	// OK
	ListWorkflowsResponse *types.ListWorkflowsResponse
}

func (q QueryWorkflowResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(q, "", false)
}

func (q *QueryWorkflowResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &q, "", false, []string{"HttpMeta"}); err != nil {
		return err
	}
	return nil
}

func (q *QueryWorkflowResponse) GetHTTPMeta() types.HTTPMetadata {
	if q == nil {
		return types.HTTPMetadata{}
	}
	return q.HTTPMeta
}

func (q *QueryWorkflowResponse) GetListWorkflowsResponse() *types.ListWorkflowsResponse {
	if q == nil {
		return nil
	}
	return q.ListWorkflowsResponse
}
