// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package dtos

import (
	"github.com/tirdad-billing/go-sdk/v2/internal/utils"
	"github.com/tirdad-billing/go-sdk/v2/models/types"
)

type QueryUserResponse struct {
	HTTPMeta types.HTTPMetadata `json:"-"`
	// OK
	ListUsersResponse *types.ListUsersResponse
}

func (q QueryUserResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(q, "", false)
}

func (q *QueryUserResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &q, "", false, []string{"HttpMeta"}); err != nil {
		return err
	}
	return nil
}

func (q *QueryUserResponse) GetHTTPMeta() types.HTTPMetadata {
	if q == nil {
		return types.HTTPMetadata{}
	}
	return q.HTTPMeta
}

func (q *QueryUserResponse) GetListUsersResponse() *types.ListUsersResponse {
	if q == nil {
		return nil
	}
	return q.ListUsersResponse
}
