// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package dtos

import (
	"github.com/tirdad-billing/go-sdk/v2/internal/utils"
	"github.com/tirdad-billing/go-sdk/v2/models/types"
)

type QueryWalletTransactionResponse struct {
	HTTPMeta types.HTTPMetadata `json:"-"`
	// OK
	ListWalletTransactionsResponse *types.ListWalletTransactionsResponse
}

func (q QueryWalletTransactionResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(q, "", false)
}

func (q *QueryWalletTransactionResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &q, "", false, []string{"HttpMeta"}); err != nil {
		return err
	}
	return nil
}

func (q *QueryWalletTransactionResponse) GetHTTPMeta() types.HTTPMetadata {
	if q == nil {
		return types.HTTPMetadata{}
	}
	return q.HTTPMeta
}

func (q *QueryWalletTransactionResponse) GetListWalletTransactionsResponse() *types.ListWalletTransactionsResponse {
	if q == nil {
		return nil
	}
	return q.ListWalletTransactionsResponse
}
