// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package dtos

import (
	"github.com/tirdad-billing/go-sdk/v2/internal/utils"
	"github.com/tirdad-billing/go-sdk/v2/models/types"
)

type RetryRefundRequest struct {
	// Refund ID
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (r RetryRefundRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *RetryRefundRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, []string{"id"}); err != nil {
		return err
	}
	return nil
}

func (r *RetryRefundRequest) GetID() string {
	if r == nil {
		return ""
	}
	return r.ID
}

type RetryRefundResponse struct {
	HTTPMeta types.HTTPMetadata `json:"-"`
	// OK
	RefundResponse *types.RefundResponse
}

func (r RetryRefundResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *RetryRefundResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, []string{"HttpMeta"}); err != nil {
		return err
	}
	return nil
}

func (r *RetryRefundResponse) GetHTTPMeta() types.HTTPMetadata {
	if r == nil {
		return types.HTTPMetadata{}
	}
	return r.HTTPMeta
}

func (r *RetryRefundResponse) GetRefundResponse() *types.RefundResponse {
	if r == nil {
		return nil
	}
	return r.RefundResponse
}
