// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package dtos

import (
	"github.com/tirdad-billing/go-sdk/v2/internal/utils"
	"github.com/tirdad-billing/go-sdk/v2/models/types"
)

type UpdateInvoicePaymentStatusRequest struct {
	// Invoice ID
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// Payment Status Update Request
	Body types.UpdatePaymentStatusRequest `request:"mediaType=application/json"`
}

func (u UpdateInvoicePaymentStatusRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdateInvoicePaymentStatusRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, []string{"id", "body"}); err != nil {
		return err
	}
	return nil
}

func (u *UpdateInvoicePaymentStatusRequest) GetID() string {
	if u == nil {
		return ""
	}
	return u.ID
}

func (u *UpdateInvoicePaymentStatusRequest) GetBody() types.UpdatePaymentStatusRequest {
	if u == nil {
		return types.UpdatePaymentStatusRequest{}
	}
	return u.Body
}

type UpdateInvoicePaymentStatusResponse struct {
	HTTPMeta types.HTTPMetadata `json:"-"`
	// OK
	InvoiceResponse *types.InvoiceResponse
}

func (u UpdateInvoicePaymentStatusResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdateInvoicePaymentStatusResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, []string{"HttpMeta"}); err != nil {
		return err
	}
	return nil
}

func (u *UpdateInvoicePaymentStatusResponse) GetHTTPMeta() types.HTTPMetadata {
	if u == nil {
		return types.HTTPMetadata{}
	}
	return u.HTTPMeta
}

func (u *UpdateInvoicePaymentStatusResponse) GetInvoiceResponse() *types.InvoiceResponse {
	if u == nil {
		return nil
	}
	return u.InvoiceResponse
}
