// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package dtos

import (
	"github.com/tirdad-billing/go-sdk/v2/internal/utils"
	"github.com/tirdad-billing/go-sdk/v2/models/types"
)

type UpdatePriceRequest struct {
	// Price ID
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// Price configuration
	Body types.UpdatePriceRequest `request:"mediaType=application/json"`
}

func (u UpdatePriceRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdatePriceRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, []string{"id", "body"}); err != nil {
		return err
	}
	return nil
}

func (u *UpdatePriceRequest) GetID() string {
	if u == nil {
		return ""
	}
	return u.ID
}

func (u *UpdatePriceRequest) GetBody() types.UpdatePriceRequest {
	if u == nil {
		return types.UpdatePriceRequest{}
	}
	return u.Body
}

type UpdatePriceResponse struct {
	HTTPMeta types.HTTPMetadata `json:"-"`
	// OK
	PriceResponse *types.PriceResponse
}

func (u UpdatePriceResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdatePriceResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, []string{"HttpMeta"}); err != nil {
		return err
	}
	return nil
}

func (u *UpdatePriceResponse) GetHTTPMeta() types.HTTPMetadata {
	if u == nil {
		return types.HTTPMetadata{}
	}
	return u.HTTPMeta
}

func (u *UpdatePriceResponse) GetPriceResponse() *types.PriceResponse {
	if u == nil {
		return nil
	}
	return u.PriceResponse
}
