// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/tirdad-billing/go-sdk/v2/internal/utils"
)

type AggregatedEntitlementBucket struct {
	EntitlementID      *string                       `json:"entitlement_id,omitzero"`
	GrantDurationUnit  *EntitlementGrantDurationUnit `json:"grant_duration_unit,omitzero"`
	GrantDurationValue *int64                        `json:"grant_duration_value,omitzero"`
	GrantMeasure       *EntitlementGrantMeasure      `json:"grant_measure,omitzero"`
	GrantQuota         *string                       `json:"grant_quota,omitzero"`
	SourceEntityID     *string                       `json:"source_entity_id,omitzero"`
	UsageLimit         *int64                        `json:"usage_limit,omitzero"`
}

func (a AggregatedEntitlementBucket) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AggregatedEntitlementBucket) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AggregatedEntitlementBucket) GetEntitlementID() *string {
	if a == nil {
		return nil
	}
	return a.EntitlementID
}

func (a *AggregatedEntitlementBucket) GetGrantDurationUnit() *EntitlementGrantDurationUnit {
	if a == nil {
		return nil
	}
	return a.GrantDurationUnit
}

func (a *AggregatedEntitlementBucket) GetGrantDurationValue() *int64 {
	if a == nil {
		return nil
	}
	return a.GrantDurationValue
}

func (a *AggregatedEntitlementBucket) GetGrantMeasure() *EntitlementGrantMeasure {
	if a == nil {
		return nil
	}
	return a.GrantMeasure
}

func (a *AggregatedEntitlementBucket) GetGrantQuota() *string {
	if a == nil {
		return nil
	}
	return a.GrantQuota
}

func (a *AggregatedEntitlementBucket) GetSourceEntityID() *string {
	if a == nil {
		return nil
	}
	return a.SourceEntityID
}

func (a *AggregatedEntitlementBucket) GetUsageLimit() *int64 {
	if a == nil {
		return nil
	}
	return a.UsageLimit
}
