// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/tirdad-billing/go-sdk/v2/internal/utils"
)

type AlertSettings struct {
	AlertEnabled *bool           `json:"alert_enabled,omitzero"`
	Critical     *AlertThreshold `json:"critical,omitzero"`
	Info         *AlertThreshold `json:"info,omitzero"`
	Warning      *AlertThreshold `json:"warning,omitzero"`
}

func (a AlertSettings) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AlertSettings) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AlertSettings) GetAlertEnabled() *bool {
	if a == nil {
		return nil
	}
	return a.AlertEnabled
}

func (a *AlertSettings) GetCritical() *AlertThreshold {
	if a == nil {
		return nil
	}
	return a.Critical
}

func (a *AlertSettings) GetInfo() *AlertThreshold {
	if a == nil {
		return nil
	}
	return a.Info
}

func (a *AlertSettings) GetWarning() *AlertThreshold {
	if a == nil {
		return nil
	}
	return a.Warning
}
