// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/tirdad-billing/go-sdk/v2/internal/utils"
	"time"
)

type AlertLogResponse struct {
	AlertInfo   *AlertInfo  `json:"alert_info,omitzero"`
	AlertStatus *AlertState `json:"alert_status,omitzero"`
	AlertType   *AlertType  `json:"alert_type,omitzero"`
	CreatedAt   *time.Time  `json:"created_at,omitzero"`
	CreatedBy   *string     `json:"created_by,omitzero"`
	// Customer response object containing all customer information
	Customer         *CustomerResponse `json:"customer,omitzero"`
	CustomerID       *string           `json:"customer_id,omitzero"`
	EntityID         *string           `json:"entity_id,omitzero"`
	EntityType       *AlertEntityType  `json:"entity_type,omitzero"`
	EnvironmentID    *string           `json:"environment_id,omitzero"`
	Feature          *FeatureResponse  `json:"feature,omitzero"`
	ID               *string           `json:"id,omitzero"`
	ParentEntityID   *string           `json:"parent_entity_id,omitzero"`
	ParentEntityType *string           `json:"parent_entity_type,omitzero"`
	Status           *string           `json:"status,omitzero"`
	TenantID         *string           `json:"tenant_id,omitzero"`
	UpdatedAt        *time.Time        `json:"updated_at,omitzero"`
	UpdatedBy        *string           `json:"updated_by,omitzero"`
	Wallet           *WalletResponse   `json:"wallet,omitzero"`
}

func (a AlertLogResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AlertLogResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AlertLogResponse) GetAlertInfo() *AlertInfo {
	if a == nil {
		return nil
	}
	return a.AlertInfo
}

func (a *AlertLogResponse) GetAlertStatus() *AlertState {
	if a == nil {
		return nil
	}
	return a.AlertStatus
}

func (a *AlertLogResponse) GetAlertType() *AlertType {
	if a == nil {
		return nil
	}
	return a.AlertType
}

func (a *AlertLogResponse) GetCreatedAt() *time.Time {
	if a == nil {
		return nil
	}
	return a.CreatedAt
}

func (a *AlertLogResponse) GetCreatedBy() *string {
	if a == nil {
		return nil
	}
	return a.CreatedBy
}

func (a *AlertLogResponse) GetCustomer() *CustomerResponse {
	if a == nil {
		return nil
	}
	return a.Customer
}

func (a *AlertLogResponse) GetCustomerID() *string {
	if a == nil {
		return nil
	}
	return a.CustomerID
}

func (a *AlertLogResponse) GetEntityID() *string {
	if a == nil {
		return nil
	}
	return a.EntityID
}

func (a *AlertLogResponse) GetEntityType() *AlertEntityType {
	if a == nil {
		return nil
	}
	return a.EntityType
}

func (a *AlertLogResponse) GetEnvironmentID() *string {
	if a == nil {
		return nil
	}
	return a.EnvironmentID
}

func (a *AlertLogResponse) GetFeature() *FeatureResponse {
	if a == nil {
		return nil
	}
	return a.Feature
}

func (a *AlertLogResponse) GetID() *string {
	if a == nil {
		return nil
	}
	return a.ID
}

func (a *AlertLogResponse) GetParentEntityID() *string {
	if a == nil {
		return nil
	}
	return a.ParentEntityID
}

func (a *AlertLogResponse) GetParentEntityType() *string {
	if a == nil {
		return nil
	}
	return a.ParentEntityType
}

func (a *AlertLogResponse) GetStatus() *string {
	if a == nil {
		return nil
	}
	return a.Status
}

func (a *AlertLogResponse) GetTenantID() *string {
	if a == nil {
		return nil
	}
	return a.TenantID
}

func (a *AlertLogResponse) GetUpdatedAt() *time.Time {
	if a == nil {
		return nil
	}
	return a.UpdatedAt
}

func (a *AlertLogResponse) GetUpdatedBy() *string {
	if a == nil {
		return nil
	}
	return a.UpdatedBy
}

func (a *AlertLogResponse) GetWallet() *WalletResponse {
	if a == nil {
		return nil
	}
	return a.Wallet
}
