// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/tirdad-billing/go-sdk/v2/internal/utils"
)

type AnalyticsQueryResult struct {
	Columns []AnalyticsColumn   `json:"columns,omitzero"`
	Meta    *AnalyticsQueryMeta `json:"meta,omitzero"`
	Rows    [][]string          `json:"rows,omitzero"`
}

func (a AnalyticsQueryResult) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AnalyticsQueryResult) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AnalyticsQueryResult) GetColumns() []AnalyticsColumn {
	if a == nil {
		return nil
	}
	return a.Columns
}

func (a *AnalyticsQueryResult) GetMeta() *AnalyticsQueryMeta {
	if a == nil {
		return nil
	}
	return a.Meta
}

func (a *AnalyticsQueryResult) GetRows() [][]string {
	if a == nil {
		return nil
	}
	return a.Rows
}
