// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/tirdad-billing/go-sdk/v2/internal/utils"
	"time"
)

type BillingPeriodConfig struct {
	BillingAnchor      *time.Time     `json:"billing_anchor,omitzero"`
	BillingCycle       *BillingCycle  `json:"billing_cycle,omitzero"`
	BillingPeriodCount *int64         `json:"billing_period_count,omitzero"`
	BillingPeriodUnit  *BillingPeriod `json:"billing_period_unit,omitzero"`
}

func (b BillingPeriodConfig) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(b, "", false)
}

func (b *BillingPeriodConfig) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &b, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (b *BillingPeriodConfig) GetBillingAnchor() *time.Time {
	if b == nil {
		return nil
	}
	return b.BillingAnchor
}

func (b *BillingPeriodConfig) GetBillingCycle() *BillingCycle {
	if b == nil {
		return nil
	}
	return b.BillingCycle
}

func (b *BillingPeriodConfig) GetBillingPeriodCount() *int64 {
	if b == nil {
		return nil
	}
	return b.BillingPeriodCount
}

func (b *BillingPeriodConfig) GetBillingPeriodUnit() *BillingPeriod {
	if b == nil {
		return nil
	}
	return b.BillingPeriodUnit
}
