// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/tirdad-billing/go-sdk/v2/internal/utils"
)

type BucketSummary struct {
	BaseCharge       *string `json:"base_charge,omitzero"`
	BucketID         *string `json:"bucket_id,omitzero"`
	CommitmentType   *string `json:"commitment_type,omitzero"`
	CommitmentValue  *string `json:"commitment_value,omitzero"`
	ComputedOverage  *string `json:"computed_overage,omitzero"`
	ComputedTrueUp   *string `json:"computed_true_up,omitzero"`
	ComputedUtilized *string `json:"computed_utilized,omitzero"`
	End              *Bucket `json:"end,omitzero"`
	// PriceID is the bucket's own price (the line item's price for the
	// out-of-bucket row).
	PriceID *string `json:"price_id,omitzero"`
	Start   *Bucket `json:"start,omitzero"`
	// SubscriptionLineItemID is the line item this bucket is configured on.
	SubscriptionLineItemID *string `json:"subscription_line_item_id,omitzero"`
	TotalUsage             *string `json:"total_usage,omitzero"`
}

func (b BucketSummary) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(b, "", false)
}

func (b *BucketSummary) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &b, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (b *BucketSummary) GetBaseCharge() *string {
	if b == nil {
		return nil
	}
	return b.BaseCharge
}

func (b *BucketSummary) GetBucketID() *string {
	if b == nil {
		return nil
	}
	return b.BucketID
}

func (b *BucketSummary) GetCommitmentType() *string {
	if b == nil {
		return nil
	}
	return b.CommitmentType
}

func (b *BucketSummary) GetCommitmentValue() *string {
	if b == nil {
		return nil
	}
	return b.CommitmentValue
}

func (b *BucketSummary) GetComputedOverage() *string {
	if b == nil {
		return nil
	}
	return b.ComputedOverage
}

func (b *BucketSummary) GetComputedTrueUp() *string {
	if b == nil {
		return nil
	}
	return b.ComputedTrueUp
}

func (b *BucketSummary) GetComputedUtilized() *string {
	if b == nil {
		return nil
	}
	return b.ComputedUtilized
}

func (b *BucketSummary) GetEnd() *Bucket {
	if b == nil {
		return nil
	}
	return b.End
}

func (b *BucketSummary) GetPriceID() *string {
	if b == nil {
		return nil
	}
	return b.PriceID
}

func (b *BucketSummary) GetStart() *Bucket {
	if b == nil {
		return nil
	}
	return b.Start
}

func (b *BucketSummary) GetSubscriptionLineItemID() *string {
	if b == nil {
		return nil
	}
	return b.SubscriptionLineItemID
}

func (b *BucketSummary) GetTotalUsage() *string {
	if b == nil {
		return nil
	}
	return b.TotalUsage
}
