// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/tirdad-billing/go-sdk/v2/internal/utils"
)

type Bucket struct {
	Hour   *int64 `json:"hour,omitzero"`
	Minute *int64 `json:"minute,omitzero"`
}

func (b Bucket) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(b, "", false)
}

func (b *Bucket) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &b, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (b *Bucket) GetHour() *int64 {
	if b == nil {
		return nil
	}
	return b.Hour
}

func (b *Bucket) GetMinute() *int64 {
	if b == nil {
		return nil
	}
	return b.Minute
}
