// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/tirdad-billing/go-sdk/v2/internal/utils"
	"time"
)

type ChangedLineItem struct {
	// created | updated | ended
	ChangeAction *ChangedLineItemAction `json:"change_action,omitzero"`
	EndDate      *time.Time             `json:"end_date,omitzero"`
	ID           *string                `json:"id,omitzero"`
	PriceID      *string                `json:"price_id,omitzero"`
	Quantity     *string                `json:"quantity,omitzero"`
	StartDate    *time.Time             `json:"start_date,omitzero"`
}

func (c ChangedLineItem) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ChangedLineItem) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *ChangedLineItem) GetChangeAction() *ChangedLineItemAction {
	if c == nil {
		return nil
	}
	return c.ChangeAction
}

func (c *ChangedLineItem) GetEndDate() *time.Time {
	if c == nil {
		return nil
	}
	return c.EndDate
}

func (c *ChangedLineItem) GetID() *string {
	if c == nil {
		return nil
	}
	return c.ID
}

func (c *ChangedLineItem) GetPriceID() *string {
	if c == nil {
		return nil
	}
	return c.PriceID
}

func (c *ChangedLineItem) GetQuantity() *string {
	if c == nil {
		return nil
	}
	return c.Quantity
}

func (c *ChangedLineItem) GetStartDate() *time.Time {
	if c == nil {
		return nil
	}
	return c.StartDate
}
