// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/tirdad-billing/go-sdk/v2/internal/utils"
	"time"
)

type ChangedAddonAssociation struct {
	AddonID     *string      `json:"addon_id,omitzero"`
	AddonStatus *AddonStatus `json:"addon_status,omitzero"`
	// created | ended
	ChangeAction *ChangedAddonAssociationAction `json:"change_action,omitzero"`
	EndDate      *time.Time                     `json:"end_date,omitzero"`
	ID           *string                        `json:"id,omitzero"`
	StartDate    *time.Time                     `json:"start_date,omitzero"`
}

func (c ChangedAddonAssociation) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ChangedAddonAssociation) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *ChangedAddonAssociation) GetAddonID() *string {
	if c == nil {
		return nil
	}
	return c.AddonID
}

func (c *ChangedAddonAssociation) GetAddonStatus() *AddonStatus {
	if c == nil {
		return nil
	}
	return c.AddonStatus
}

func (c *ChangedAddonAssociation) GetChangeAction() *ChangedAddonAssociationAction {
	if c == nil {
		return nil
	}
	return c.ChangeAction
}

func (c *ChangedAddonAssociation) GetEndDate() *time.Time {
	if c == nil {
		return nil
	}
	return c.EndDate
}

func (c *ChangedAddonAssociation) GetID() *string {
	if c == nil {
		return nil
	}
	return c.ID
}

func (c *ChangedAddonAssociation) GetStartDate() *time.Time {
	if c == nil {
		return nil
	}
	return c.StartDate
}
