// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

// ChangedInvoiceStatus - preview | issued | INITIATED | PENDING | PROCESSING | SUCCEEDED | OVERPAID | FAILED | REFUNDED | PARTIALLY_REFUNDED
type ChangedInvoiceStatus string

const (
	ChangedInvoiceStatusPreview ChangedInvoiceStatus = "preview"
	ChangedInvoiceStatusIssued  ChangedInvoiceStatus = "issued"
)

func (e ChangedInvoiceStatus) ToPointer() *ChangedInvoiceStatus {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *ChangedInvoiceStatus) IsExact() bool {
	if e != nil {
		switch *e {
		case "preview", "issued":
			return true
		}
	}
	return false
}
