// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

type CheckoutPaymentProvider string

const (
	CheckoutPaymentProviderRazorpay  CheckoutPaymentProvider = "razorpay"
	CheckoutPaymentProviderChargebee CheckoutPaymentProvider = "chargebee"
)

func (e CheckoutPaymentProvider) ToPointer() *CheckoutPaymentProvider {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *CheckoutPaymentProvider) IsExact() bool {
	if e != nil {
		switch *e {
		case "razorpay", "chargebee":
			return true
		}
	}
	return false
}
