// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"encoding/json"
	"fmt"
	"github.com/tirdad-billing/go-sdk/v2/internal/utils"
)

type CouponFilterOrder string

const (
	CouponFilterOrderAsc  CouponFilterOrder = "asc"
	CouponFilterOrderDesc CouponFilterOrder = "desc"
)

func (e CouponFilterOrder) ToPointer() *CouponFilterOrder {
	return &e
}
func (e *CouponFilterOrder) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "asc":
		fallthrough
	case "desc":
		*e = CouponFilterOrder(v)
		return nil
	default:
		return fmt.Errorf("invalid value for CouponFilterOrder: %v", v)
	}
}

type CouponFilter struct {
	CouponIds []string           `json:"coupon_ids,omitzero"`
	Expand    *string            `json:"expand,omitzero"`
	Filters   []FilterCondition  `json:"filters,omitzero"`
	Limit     *int64             `json:"limit,omitzero"`
	Offset    *int64             `json:"offset,omitzero"`
	Order     *CouponFilterOrder `json:"order,omitzero"`
	Sort      []SortCondition    `json:"sort,omitzero"`
	Status    *Status            `json:"status,omitzero"`
}

func (c CouponFilter) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CouponFilter) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CouponFilter) GetCouponIds() []string {
	if c == nil {
		return nil
	}
	return c.CouponIds
}

func (c *CouponFilter) GetExpand() *string {
	if c == nil {
		return nil
	}
	return c.Expand
}

func (c *CouponFilter) GetFilters() []FilterCondition {
	if c == nil {
		return nil
	}
	return c.Filters
}

func (c *CouponFilter) GetLimit() *int64 {
	if c == nil {
		return nil
	}
	return c.Limit
}

func (c *CouponFilter) GetOffset() *int64 {
	if c == nil {
		return nil
	}
	return c.Offset
}

func (c *CouponFilter) GetOrder() *CouponFilterOrder {
	if c == nil {
		return nil
	}
	return c.Order
}

func (c *CouponFilter) GetSort() []SortCondition {
	if c == nil {
		return nil
	}
	return c.Sort
}

func (c *CouponFilter) GetStatus() *Status {
	if c == nil {
		return nil
	}
	return c.Status
}
