// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/tirdad-billing/go-sdk/v2/internal/utils"
	"time"
)

type CouponApplicationResponse struct {
	AppliedAt           *time.Time        `json:"applied_at,omitzero"`
	CouponAssociationID *string           `json:"coupon_association_id,omitzero"`
	CouponID            *string           `json:"coupon_id,omitzero"`
	CouponSnapshot      map[string]any    `json:"coupon_snapshot,omitzero"`
	CreatedAt           *time.Time        `json:"created_at,omitzero"`
	CreatedBy           *string           `json:"created_by,omitzero"`
	Currency            *string           `json:"currency,omitzero"`
	DiscountPercentage  *string           `json:"discount_percentage,omitzero"`
	DiscountType        *CouponType       `json:"discount_type,omitzero"`
	DiscountedAmount    *string           `json:"discounted_amount,omitzero"`
	EnvironmentID       *string           `json:"environment_id,omitzero"`
	FinalPrice          *string           `json:"final_price,omitzero"`
	ID                  *string           `json:"id,omitzero"`
	InvoiceID           *string           `json:"invoice_id,omitzero"`
	InvoiceLineItemID   *string           `json:"invoice_line_item_id,omitzero"`
	Metadata            map[string]string `json:"metadata,omitzero"`
	OriginalPrice       *string           `json:"original_price,omitzero"`
	Status              *Status           `json:"status,omitzero"`
	SubscriptionID      *string           `json:"subscription_id,omitzero"`
	TenantID            *string           `json:"tenant_id,omitzero"`
	UpdatedAt           *time.Time        `json:"updated_at,omitzero"`
	UpdatedBy           *string           `json:"updated_by,omitzero"`
}

func (c CouponApplicationResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CouponApplicationResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CouponApplicationResponse) GetAppliedAt() *time.Time {
	if c == nil {
		return nil
	}
	return c.AppliedAt
}

func (c *CouponApplicationResponse) GetCouponAssociationID() *string {
	if c == nil {
		return nil
	}
	return c.CouponAssociationID
}

func (c *CouponApplicationResponse) GetCouponID() *string {
	if c == nil {
		return nil
	}
	return c.CouponID
}

func (c *CouponApplicationResponse) GetCouponSnapshot() map[string]any {
	if c == nil {
		return nil
	}
	return c.CouponSnapshot
}

func (c *CouponApplicationResponse) GetCreatedAt() *time.Time {
	if c == nil {
		return nil
	}
	return c.CreatedAt
}

func (c *CouponApplicationResponse) GetCreatedBy() *string {
	if c == nil {
		return nil
	}
	return c.CreatedBy
}

func (c *CouponApplicationResponse) GetCurrency() *string {
	if c == nil {
		return nil
	}
	return c.Currency
}

func (c *CouponApplicationResponse) GetDiscountPercentage() *string {
	if c == nil {
		return nil
	}
	return c.DiscountPercentage
}

func (c *CouponApplicationResponse) GetDiscountType() *CouponType {
	if c == nil {
		return nil
	}
	return c.DiscountType
}

func (c *CouponApplicationResponse) GetDiscountedAmount() *string {
	if c == nil {
		return nil
	}
	return c.DiscountedAmount
}

func (c *CouponApplicationResponse) GetEnvironmentID() *string {
	if c == nil {
		return nil
	}
	return c.EnvironmentID
}

func (c *CouponApplicationResponse) GetFinalPrice() *string {
	if c == nil {
		return nil
	}
	return c.FinalPrice
}

func (c *CouponApplicationResponse) GetID() *string {
	if c == nil {
		return nil
	}
	return c.ID
}

func (c *CouponApplicationResponse) GetInvoiceID() *string {
	if c == nil {
		return nil
	}
	return c.InvoiceID
}

func (c *CouponApplicationResponse) GetInvoiceLineItemID() *string {
	if c == nil {
		return nil
	}
	return c.InvoiceLineItemID
}

func (c *CouponApplicationResponse) GetMetadata() map[string]string {
	if c == nil {
		return nil
	}
	return c.Metadata
}

func (c *CouponApplicationResponse) GetOriginalPrice() *string {
	if c == nil {
		return nil
	}
	return c.OriginalPrice
}

func (c *CouponApplicationResponse) GetStatus() *Status {
	if c == nil {
		return nil
	}
	return c.Status
}

func (c *CouponApplicationResponse) GetSubscriptionID() *string {
	if c == nil {
		return nil
	}
	return c.SubscriptionID
}

func (c *CouponApplicationResponse) GetTenantID() *string {
	if c == nil {
		return nil
	}
	return c.TenantID
}

func (c *CouponApplicationResponse) GetUpdatedAt() *time.Time {
	if c == nil {
		return nil
	}
	return c.UpdatedAt
}

func (c *CouponApplicationResponse) GetUpdatedBy() *string {
	if c == nil {
		return nil
	}
	return c.UpdatedBy
}
