// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/tirdad-billing/go-sdk/v2/internal/utils"
	"time"
)

type CreateSubscriptionLineItemRequest struct {
	// Commitment fields
	CommitmentAmount        *float64                        `json:"commitment_amount,omitzero"`
	CommitmentDuration      *BillingPeriod                  `json:"commitment_duration,omitzero"`
	CommitmentOverageFactor *float64                        `json:"commitment_overage_factor,omitzero"`
	CommitmentQuantity      *float64                        `json:"commitment_quantity,omitzero"`
	CommitmentTimeBuckets   []CommitmentBucketRequest       `json:"commitment_time_buckets,omitzero"`
	CommitmentTrueUpEnabled *bool                           `json:"commitment_true_up_enabled,omitzero"`
	CommitmentType          *CommitmentType                 `json:"commitment_type,omitzero"`
	CommitmentWindowed      *bool                           `json:"commitment_windowed,omitzero"`
	DisplayName             *string                         `json:"display_name,omitzero"`
	EndDate                 *time.Time                      `json:"end_date,omitzero"`
	Metadata                map[string]string               `json:"metadata,omitzero"`
	Price                   *SubscriptionPriceCreateRequest `json:"price,omitzero"`
	// PriceID references an existing price (plan, addon, or subscription-scoped). Exactly one of price_id or price must be set.
	PriceID             *string            `json:"price_id,omitzero"`
	ProrationBehavior   *ProrationBehavior `json:"proration_behavior,omitzero"`
	Quantity            *float64           `json:"quantity,omitzero"`
	StartDate           *time.Time         `json:"start_date,omitzero"`
	SubscriptionPhaseID *string            `json:"subscription_phase_id,omitzero"`
}

func (c CreateSubscriptionLineItemRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateSubscriptionLineItemRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateSubscriptionLineItemRequest) GetCommitmentAmount() *float64 {
	if c == nil {
		return nil
	}
	return c.CommitmentAmount
}

func (c *CreateSubscriptionLineItemRequest) GetCommitmentDuration() *BillingPeriod {
	if c == nil {
		return nil
	}
	return c.CommitmentDuration
}

func (c *CreateSubscriptionLineItemRequest) GetCommitmentOverageFactor() *float64 {
	if c == nil {
		return nil
	}
	return c.CommitmentOverageFactor
}

func (c *CreateSubscriptionLineItemRequest) GetCommitmentQuantity() *float64 {
	if c == nil {
		return nil
	}
	return c.CommitmentQuantity
}

func (c *CreateSubscriptionLineItemRequest) GetCommitmentTimeBuckets() []CommitmentBucketRequest {
	if c == nil {
		return nil
	}
	return c.CommitmentTimeBuckets
}

func (c *CreateSubscriptionLineItemRequest) GetCommitmentTrueUpEnabled() *bool {
	if c == nil {
		return nil
	}
	return c.CommitmentTrueUpEnabled
}

func (c *CreateSubscriptionLineItemRequest) GetCommitmentType() *CommitmentType {
	if c == nil {
		return nil
	}
	return c.CommitmentType
}

func (c *CreateSubscriptionLineItemRequest) GetCommitmentWindowed() *bool {
	if c == nil {
		return nil
	}
	return c.CommitmentWindowed
}

func (c *CreateSubscriptionLineItemRequest) GetDisplayName() *string {
	if c == nil {
		return nil
	}
	return c.DisplayName
}

func (c *CreateSubscriptionLineItemRequest) GetEndDate() *time.Time {
	if c == nil {
		return nil
	}
	return c.EndDate
}

func (c *CreateSubscriptionLineItemRequest) GetMetadata() map[string]string {
	if c == nil {
		return nil
	}
	return c.Metadata
}

func (c *CreateSubscriptionLineItemRequest) GetPrice() *SubscriptionPriceCreateRequest {
	if c == nil {
		return nil
	}
	return c.Price
}

func (c *CreateSubscriptionLineItemRequest) GetPriceID() *string {
	if c == nil {
		return nil
	}
	return c.PriceID
}

func (c *CreateSubscriptionLineItemRequest) GetProrationBehavior() *ProrationBehavior {
	if c == nil {
		return nil
	}
	return c.ProrationBehavior
}

func (c *CreateSubscriptionLineItemRequest) GetQuantity() *float64 {
	if c == nil {
		return nil
	}
	return c.Quantity
}

func (c *CreateSubscriptionLineItemRequest) GetStartDate() *time.Time {
	if c == nil {
		return nil
	}
	return c.StartDate
}

func (c *CreateSubscriptionLineItemRequest) GetSubscriptionPhaseID() *string {
	if c == nil {
		return nil
	}
	return c.SubscriptionPhaseID
}
