// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/tirdad-billing/go-sdk/v2/internal/utils"
)

type CreatePlanRequest struct {
	Description  *string           `json:"description,omitzero"`
	DisplayOrder *int64            `json:"display_order,omitzero"`
	LookupKey    *string           `json:"lookup_key,omitzero"`
	Metadata     map[string]string `json:"metadata,omitzero"`
	Name         string            `json:"name"`
}

func (c CreatePlanRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreatePlanRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, []string{"name"}); err != nil {
		return err
	}
	return nil
}

func (c *CreatePlanRequest) GetDescription() *string {
	if c == nil {
		return nil
	}
	return c.Description
}

func (c *CreatePlanRequest) GetDisplayOrder() *int64 {
	if c == nil {
		return nil
	}
	return c.DisplayOrder
}

func (c *CreatePlanRequest) GetLookupKey() *string {
	if c == nil {
		return nil
	}
	return c.LookupKey
}

func (c *CreatePlanRequest) GetMetadata() map[string]string {
	if c == nil {
		return nil
	}
	return c.Metadata
}

func (c *CreatePlanRequest) GetName() string {
	if c == nil {
		return ""
	}
	return c.Name
}
