// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/tirdad-billing/go-sdk/v2/internal/utils"
	"time"
)

type CreateAddonResponse struct {
	CreatedAt     *time.Time            `json:"created_at,omitzero"`
	CreatedBy     *string               `json:"created_by,omitzero"`
	CreditGrants  []CreditGrantResponse `json:"credit_grants,omitzero"`
	Description   *string               `json:"description,omitzero"`
	Entitlements  []EntitlementResponse `json:"entitlements,omitzero"`
	EnvironmentID *string               `json:"environment_id,omitzero"`
	ID            *string               `json:"id,omitzero"`
	LookupKey     *string               `json:"lookup_key,omitzero"`
	Metadata      map[string]any        `json:"metadata,omitzero"`
	Name          *string               `json:"name,omitzero"`
	// Optional expanded fields
	Prices    []PriceResponse `json:"prices,omitzero"`
	Status    *Status         `json:"status,omitzero"`
	TenantID  *string         `json:"tenant_id,omitzero"`
	UpdatedAt *time.Time      `json:"updated_at,omitzero"`
	UpdatedBy *string         `json:"updated_by,omitzero"`
}

func (c CreateAddonResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateAddonResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateAddonResponse) GetCreatedAt() *time.Time {
	if c == nil {
		return nil
	}
	return c.CreatedAt
}

func (c *CreateAddonResponse) GetCreatedBy() *string {
	if c == nil {
		return nil
	}
	return c.CreatedBy
}

func (c *CreateAddonResponse) GetCreditGrants() []CreditGrantResponse {
	if c == nil {
		return nil
	}
	return c.CreditGrants
}

func (c *CreateAddonResponse) GetDescription() *string {
	if c == nil {
		return nil
	}
	return c.Description
}

func (c *CreateAddonResponse) GetEntitlements() []EntitlementResponse {
	if c == nil {
		return nil
	}
	return c.Entitlements
}

func (c *CreateAddonResponse) GetEnvironmentID() *string {
	if c == nil {
		return nil
	}
	return c.EnvironmentID
}

func (c *CreateAddonResponse) GetID() *string {
	if c == nil {
		return nil
	}
	return c.ID
}

func (c *CreateAddonResponse) GetLookupKey() *string {
	if c == nil {
		return nil
	}
	return c.LookupKey
}

func (c *CreateAddonResponse) GetMetadata() map[string]any {
	if c == nil {
		return nil
	}
	return c.Metadata
}

func (c *CreateAddonResponse) GetName() *string {
	if c == nil {
		return nil
	}
	return c.Name
}

func (c *CreateAddonResponse) GetPrices() []PriceResponse {
	if c == nil {
		return nil
	}
	return c.Prices
}

func (c *CreateAddonResponse) GetStatus() *Status {
	if c == nil {
		return nil
	}
	return c.Status
}

func (c *CreateAddonResponse) GetTenantID() *string {
	if c == nil {
		return nil
	}
	return c.TenantID
}

func (c *CreateAddonResponse) GetUpdatedAt() *time.Time {
	if c == nil {
		return nil
	}
	return c.UpdatedAt
}

func (c *CreateAddonResponse) GetUpdatedBy() *string {
	if c == nil {
		return nil
	}
	return c.UpdatedBy
}
