// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/tirdad-billing/go-sdk/v2/internal/utils"
	"time"
)

type CreateEntitlementRequest struct {
	AggregationMode         *EntitlementAggregationMode         `json:"aggregation_mode,omitzero"`
	ConfigValue             map[string]any                      `json:"config_value,omitzero"`
	EndDate                 *time.Time                          `json:"end_date,omitzero"`
	EntityID                *string                             `json:"entity_id,omitzero"`
	EntityType              *EntitlementEntityType              `json:"entity_type,omitzero"`
	FeatureID               string                              `json:"feature_id"`
	FeatureType             FeatureType                         `json:"feature_type"`
	GrantAllocationBehavior *EntitlementGrantAllocationBehavior `json:"grant_allocation_behavior,omitzero"`
	GrantDurationUnit       *EntitlementGrantDurationUnit       `json:"grant_duration_unit,omitzero"`
	GrantDurationValue      *int64                              `json:"grant_duration_value,omitzero"`
	GrantMeasure            *EntitlementGrantMeasure            `json:"grant_measure,omitzero"`
	GrantQuota              *string                             `json:"grant_quota,omitzero"`
	IsEnabled               *bool                               `json:"is_enabled,omitzero"`
	IsSoftLimit             *bool                               `json:"is_soft_limit,omitzero"`
	ParentEntitlementID     *string                             `json:"parent_entitlement_id,omitzero"`
	PlanID                  *string                             `json:"plan_id,omitzero"`
	StartDate               *time.Time                          `json:"start_date,omitzero"`
	StaticValue             *string                             `json:"static_value,omitzero"`
	UsageLimit              *int64                              `json:"usage_limit,omitzero"`
	UsageResetPeriod        *EntitlementUsageResetPeriod        `json:"usage_reset_period,omitzero"`
}

func (c CreateEntitlementRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateEntitlementRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, []string{"feature_id", "feature_type"}); err != nil {
		return err
	}
	return nil
}

func (c *CreateEntitlementRequest) GetAggregationMode() *EntitlementAggregationMode {
	if c == nil {
		return nil
	}
	return c.AggregationMode
}

func (c *CreateEntitlementRequest) GetConfigValue() map[string]any {
	if c == nil {
		return nil
	}
	return c.ConfigValue
}

func (c *CreateEntitlementRequest) GetEndDate() *time.Time {
	if c == nil {
		return nil
	}
	return c.EndDate
}

func (c *CreateEntitlementRequest) GetEntityID() *string {
	if c == nil {
		return nil
	}
	return c.EntityID
}

func (c *CreateEntitlementRequest) GetEntityType() *EntitlementEntityType {
	if c == nil {
		return nil
	}
	return c.EntityType
}

func (c *CreateEntitlementRequest) GetFeatureID() string {
	if c == nil {
		return ""
	}
	return c.FeatureID
}

func (c *CreateEntitlementRequest) GetFeatureType() FeatureType {
	if c == nil {
		return FeatureType("")
	}
	return c.FeatureType
}

func (c *CreateEntitlementRequest) GetGrantAllocationBehavior() *EntitlementGrantAllocationBehavior {
	if c == nil {
		return nil
	}
	return c.GrantAllocationBehavior
}

func (c *CreateEntitlementRequest) GetGrantDurationUnit() *EntitlementGrantDurationUnit {
	if c == nil {
		return nil
	}
	return c.GrantDurationUnit
}

func (c *CreateEntitlementRequest) GetGrantDurationValue() *int64 {
	if c == nil {
		return nil
	}
	return c.GrantDurationValue
}

func (c *CreateEntitlementRequest) GetGrantMeasure() *EntitlementGrantMeasure {
	if c == nil {
		return nil
	}
	return c.GrantMeasure
}

func (c *CreateEntitlementRequest) GetGrantQuota() *string {
	if c == nil {
		return nil
	}
	return c.GrantQuota
}

func (c *CreateEntitlementRequest) GetIsEnabled() *bool {
	if c == nil {
		return nil
	}
	return c.IsEnabled
}

func (c *CreateEntitlementRequest) GetIsSoftLimit() *bool {
	if c == nil {
		return nil
	}
	return c.IsSoftLimit
}

func (c *CreateEntitlementRequest) GetParentEntitlementID() *string {
	if c == nil {
		return nil
	}
	return c.ParentEntitlementID
}

func (c *CreateEntitlementRequest) GetPlanID() *string {
	if c == nil {
		return nil
	}
	return c.PlanID
}

func (c *CreateEntitlementRequest) GetStartDate() *time.Time {
	if c == nil {
		return nil
	}
	return c.StartDate
}

func (c *CreateEntitlementRequest) GetStaticValue() *string {
	if c == nil {
		return nil
	}
	return c.StaticValue
}

func (c *CreateEntitlementRequest) GetUsageLimit() *int64 {
	if c == nil {
		return nil
	}
	return c.UsageLimit
}

func (c *CreateEntitlementRequest) GetUsageResetPeriod() *EntitlementUsageResetPeriod {
	if c == nil {
		return nil
	}
	return c.UsageResetPeriod
}
