// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/tirdad-billing/go-sdk/v2/internal/utils"
	"time"
)

type CreateFXRateRequest struct {
	EndDate      *time.Time        `json:"end_date,omitzero"`
	FromCurrency string            `json:"from_currency"`
	Metadata     map[string]string `json:"metadata,omitzero"`
	Rate         *string           `json:"rate,omitzero"`
	Scope        FXRateScope       `json:"scope"`
	ScopeID      *string           `json:"scope_id,omitzero"`
	Source       *FXRateSource     `json:"source,omitzero"`
	StartDate    *time.Time        `json:"start_date,omitzero"`
	ToCurrency   string            `json:"to_currency"`
}

func (c CreateFXRateRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateFXRateRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, []string{"from_currency", "scope", "to_currency"}); err != nil {
		return err
	}
	return nil
}

func (c *CreateFXRateRequest) GetEndDate() *time.Time {
	if c == nil {
		return nil
	}
	return c.EndDate
}

func (c *CreateFXRateRequest) GetFromCurrency() string {
	if c == nil {
		return ""
	}
	return c.FromCurrency
}

func (c *CreateFXRateRequest) GetMetadata() map[string]string {
	if c == nil {
		return nil
	}
	return c.Metadata
}

func (c *CreateFXRateRequest) GetRate() *string {
	if c == nil {
		return nil
	}
	return c.Rate
}

func (c *CreateFXRateRequest) GetScope() FXRateScope {
	if c == nil {
		return FXRateScope("")
	}
	return c.Scope
}

func (c *CreateFXRateRequest) GetScopeID() *string {
	if c == nil {
		return nil
	}
	return c.ScopeID
}

func (c *CreateFXRateRequest) GetSource() *FXRateSource {
	if c == nil {
		return nil
	}
	return c.Source
}

func (c *CreateFXRateRequest) GetStartDate() *time.Time {
	if c == nil {
		return nil
	}
	return c.StartDate
}

func (c *CreateFXRateRequest) GetToCurrency() string {
	if c == nil {
		return ""
	}
	return c.ToCurrency
}
