// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/tirdad-billing/go-sdk/v2/internal/utils"
)

type CreateCreditNoteLineItemRequest struct {
	// amount is the monetary amount to be credited for this line item
	Amount string `json:"amount"`
	// display_name is an optional human-readable name for this credit note line item
	DisplayName *string `json:"display_name,omitzero"`
	// invoice_line_item_id is the unique identifier of the invoice line item being credited
	InvoiceLineItemID string            `json:"invoice_line_item_id"`
	Metadata          map[string]string `json:"metadata,omitzero"`
}

func (c CreateCreditNoteLineItemRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateCreditNoteLineItemRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, []string{"amount", "invoice_line_item_id"}); err != nil {
		return err
	}
	return nil
}

func (c *CreateCreditNoteLineItemRequest) GetAmount() string {
	if c == nil {
		return ""
	}
	return c.Amount
}

func (c *CreateCreditNoteLineItemRequest) GetDisplayName() *string {
	if c == nil {
		return nil
	}
	return c.DisplayName
}

func (c *CreateCreditNoteLineItemRequest) GetInvoiceLineItemID() string {
	if c == nil {
		return ""
	}
	return c.InvoiceLineItemID
}

func (c *CreateCreditNoteLineItemRequest) GetMetadata() map[string]string {
	if c == nil {
		return nil
	}
	return c.Metadata
}
