// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/tirdad-billing/go-sdk/v2/internal/utils"
)

type CreateScheduledTaskRequest struct {
	ConnectionID string                  `json:"connection_id"`
	Enabled      *bool                   `json:"enabled,omitzero"`
	EntityType   ScheduledTaskEntityType `json:"entity_type"`
	Interval     ScheduledTaskInterval   `json:"interval"`
	JobConfig    S3JobConfig             `json:"job_config"`
}

func (c CreateScheduledTaskRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateScheduledTaskRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, []string{"connection_id", "entity_type", "interval", "job_config"}); err != nil {
		return err
	}
	return nil
}

func (c *CreateScheduledTaskRequest) GetConnectionID() string {
	if c == nil {
		return ""
	}
	return c.ConnectionID
}

func (c *CreateScheduledTaskRequest) GetEnabled() *bool {
	if c == nil {
		return nil
	}
	return c.Enabled
}

func (c *CreateScheduledTaskRequest) GetEntityType() ScheduledTaskEntityType {
	if c == nil {
		return ScheduledTaskEntityType("")
	}
	return c.EntityType
}

func (c *CreateScheduledTaskRequest) GetInterval() ScheduledTaskInterval {
	if c == nil {
		return ScheduledTaskInterval("")
	}
	return c.Interval
}

func (c *CreateScheduledTaskRequest) GetJobConfig() S3JobConfig {
	if c == nil {
		return S3JobConfig{}
	}
	return c.JobConfig
}
