// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/tirdad-billing/go-sdk/v2/internal/utils"
)

type CreateUserRequest struct {
	// Required when type is "user"
	Email *string `json:"email,omitzero"`
	// Display name; optional for service accounts
	Name *string `json:"name,omitzero"`
	// Required when type is "service_account"
	Roles []string `json:"roles,omitzero"`
	Type  UserType `json:"type"`
}

func (c CreateUserRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateUserRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, []string{"type"}); err != nil {
		return err
	}
	return nil
}

func (c *CreateUserRequest) GetEmail() *string {
	if c == nil {
		return nil
	}
	return c.Email
}

func (c *CreateUserRequest) GetName() *string {
	if c == nil {
		return nil
	}
	return c.Name
}

func (c *CreateUserRequest) GetRoles() []string {
	if c == nil {
		return nil
	}
	return c.Roles
}

func (c *CreateUserRequest) GetType() UserType {
	if c == nil {
		return UserType("")
	}
	return c.Type
}
