// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/tirdad-billing/go-sdk/v2/internal/utils"
)

type CreateCreditNoteRequest struct {
	// credit_note_number is an optional human-readable identifier for the credit note
	CreditNoteNumber *string `json:"credit_note_number,omitzero"`
	// idempotency_key is an optional key used to prevent duplicate credit note creation
	IdempotencyKey *string `json:"idempotency_key,omitzero"`
	// invoice_id is the unique identifier of the invoice this credit note is applied to
	InvoiceID string `json:"invoice_id"`
	// line_items contains the individual line items that make up this credit note (minimum 1 required)
	LineItems []CreateCreditNoteLineItemRequest `json:"line_items,omitzero"`
	// memo is an optional free-text field for additional notes about the credit note
	Memo     *string           `json:"memo,omitzero"`
	Metadata map[string]string `json:"metadata,omitzero"`
	// process_credit_note is a flag to process the credit note after creation
	ProcessCreditNote *bool            `default:"true" json:"process_credit_note"`
	Reason            CreditNoteReason `json:"reason"`
}

func (c CreateCreditNoteRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateCreditNoteRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, []string{"invoice_id", "reason"}); err != nil {
		return err
	}
	return nil
}

func (c *CreateCreditNoteRequest) GetCreditNoteNumber() *string {
	if c == nil {
		return nil
	}
	return c.CreditNoteNumber
}

func (c *CreateCreditNoteRequest) GetIdempotencyKey() *string {
	if c == nil {
		return nil
	}
	return c.IdempotencyKey
}

func (c *CreateCreditNoteRequest) GetInvoiceID() string {
	if c == nil {
		return ""
	}
	return c.InvoiceID
}

func (c *CreateCreditNoteRequest) GetLineItems() []CreateCreditNoteLineItemRequest {
	if c == nil {
		return nil
	}
	return c.LineItems
}

func (c *CreateCreditNoteRequest) GetMemo() *string {
	if c == nil {
		return nil
	}
	return c.Memo
}

func (c *CreateCreditNoteRequest) GetMetadata() map[string]string {
	if c == nil {
		return nil
	}
	return c.Metadata
}

func (c *CreateCreditNoteRequest) GetProcessCreditNote() *bool {
	if c == nil {
		return nil
	}
	return c.ProcessCreditNote
}

func (c *CreateCreditNoteRequest) GetReason() CreditNoteReason {
	if c == nil {
		return CreditNoteReason("")
	}
	return c.Reason
}
