// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/tirdad-billing/go-sdk/v2/internal/utils"
	"time"
)

type CreateInvoiceRequest struct {
	// amount_due is the total amount that needs to be paid for this invoice
	AmountDue string `json:"amount_due"`
	// amount_paid is the amount that has been paid towards this invoice
	AmountPaid *string `json:"amount_paid,omitzero"`
	// billing_period is the period this invoice covers (e.g., "monthly", "yearly")
	BillingPeriod *string               `json:"billing_period,omitzero"`
	BillingReason *InvoiceBillingReason `json:"billing_reason,omitzero"`
	// coupons
	Coupons []string `json:"coupons,omitzero"`
	// currency is the three-letter ISO currency code (e.g., USD, EUR) for the invoice
	Currency string `json:"currency"`
	// customer_id is the unique identifier of the customer this invoice belongs to
	CustomerID string `json:"customer_id"`
	// description is an optional text description of the invoice
	Description *string `json:"description,omitzero"`
	// due_date is the date by which payment is expected
	DueDate *time.Time `json:"due_date,omitzero"`
	// idempotency_key is an optional key used to prevent duplicate invoice creation
	IdempotencyKey *string `json:"idempotency_key,omitzero"`
	// Invoice Coupons
	InvoiceCoupons []InvoiceCoupon `json:"invoice_coupons,omitzero"`
	// invoice_number is an optional human-readable identifier for the invoice
	InvoiceNumber *string `json:"invoice_number,omitzero"`
	// invoice_pdf_url is the URL where customers can download the PDF version of this invoice
	InvoicePdfURL *string        `json:"invoice_pdf_url,omitzero"`
	InvoiceStatus *InvoiceStatus `json:"invoice_status,omitzero"`
	InvoiceType   *InvoiceType   `json:"invoice_type,omitzero"`
	// issue_date overrides the user-facing date of the invoice.
	// Defaults to created_at if not provided.
	IssueDate *time.Time `json:"issue_date,omitzero"`
	// Invoice Line Item Coupons
	LineItemCoupons []InvoiceLineItemCoupon `json:"line_item_coupons,omitzero"`
	// line_items contains the individual items that make up this invoice
	LineItems     []CreateInvoiceLineItemRequest `json:"line_items,omitzero"`
	Metadata      map[string]string              `json:"metadata,omitzero"`
	PaymentStatus *PaymentStatus                 `json:"payment_status,omitzero"`
	// period_end is the end date of the billing period
	PeriodEnd *time.Time `json:"period_end,omitzero"`
	// period_start is the start date of the billing period
	PeriodStart *time.Time `json:"period_start,omitzero"`
	// prepared_tax_rates contains the tax rates pre-resolved by the caller (e.g., billing service)
	PreparedTaxRates []TaxRateResponse `json:"prepared_tax_rates,omitzero"`
	// subscription_id is the optional unique identifier of the subscription associated with this invoice
	SubscriptionID *string `json:"subscription_id,omitzero"`
	// subtotal is the amount before taxes and discounts are applied
	Subtotal string `json:"subtotal"`
	// tax_rate_overrides is the tax rate overrides to be applied to the invoice
	TaxRateOverrides []TaxRateOverride `json:"tax_rate_overrides,omitzero"`
	// tax_rates
	TaxRates []string `json:"tax_rates,omitzero"`
	// total is the total amount of the invoice including taxes and discounts
	Total string `json:"total"`
	// total_prepaid_applied is the total amount of prepaid applied to this invoice.
	TotalPrepaidApplied *string `json:"total_prepaid_applied,omitzero"`
}

func (c CreateInvoiceRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateInvoiceRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, []string{"amount_due", "currency", "customer_id", "subtotal", "total"}); err != nil {
		return err
	}
	return nil
}

func (c *CreateInvoiceRequest) GetAmountDue() string {
	if c == nil {
		return ""
	}
	return c.AmountDue
}

func (c *CreateInvoiceRequest) GetAmountPaid() *string {
	if c == nil {
		return nil
	}
	return c.AmountPaid
}

func (c *CreateInvoiceRequest) GetBillingPeriod() *string {
	if c == nil {
		return nil
	}
	return c.BillingPeriod
}

func (c *CreateInvoiceRequest) GetBillingReason() *InvoiceBillingReason {
	if c == nil {
		return nil
	}
	return c.BillingReason
}

func (c *CreateInvoiceRequest) GetCoupons() []string {
	if c == nil {
		return nil
	}
	return c.Coupons
}

func (c *CreateInvoiceRequest) GetCurrency() string {
	if c == nil {
		return ""
	}
	return c.Currency
}

func (c *CreateInvoiceRequest) GetCustomerID() string {
	if c == nil {
		return ""
	}
	return c.CustomerID
}

func (c *CreateInvoiceRequest) GetDescription() *string {
	if c == nil {
		return nil
	}
	return c.Description
}

func (c *CreateInvoiceRequest) GetDueDate() *time.Time {
	if c == nil {
		return nil
	}
	return c.DueDate
}

func (c *CreateInvoiceRequest) GetIdempotencyKey() *string {
	if c == nil {
		return nil
	}
	return c.IdempotencyKey
}

func (c *CreateInvoiceRequest) GetInvoiceCoupons() []InvoiceCoupon {
	if c == nil {
		return nil
	}
	return c.InvoiceCoupons
}

func (c *CreateInvoiceRequest) GetInvoiceNumber() *string {
	if c == nil {
		return nil
	}
	return c.InvoiceNumber
}

func (c *CreateInvoiceRequest) GetInvoicePdfURL() *string {
	if c == nil {
		return nil
	}
	return c.InvoicePdfURL
}

func (c *CreateInvoiceRequest) GetInvoiceStatus() *InvoiceStatus {
	if c == nil {
		return nil
	}
	return c.InvoiceStatus
}

func (c *CreateInvoiceRequest) GetInvoiceType() *InvoiceType {
	if c == nil {
		return nil
	}
	return c.InvoiceType
}

func (c *CreateInvoiceRequest) GetIssueDate() *time.Time {
	if c == nil {
		return nil
	}
	return c.IssueDate
}

func (c *CreateInvoiceRequest) GetLineItemCoupons() []InvoiceLineItemCoupon {
	if c == nil {
		return nil
	}
	return c.LineItemCoupons
}

func (c *CreateInvoiceRequest) GetLineItems() []CreateInvoiceLineItemRequest {
	if c == nil {
		return nil
	}
	return c.LineItems
}

func (c *CreateInvoiceRequest) GetMetadata() map[string]string {
	if c == nil {
		return nil
	}
	return c.Metadata
}

func (c *CreateInvoiceRequest) GetPaymentStatus() *PaymentStatus {
	if c == nil {
		return nil
	}
	return c.PaymentStatus
}

func (c *CreateInvoiceRequest) GetPeriodEnd() *time.Time {
	if c == nil {
		return nil
	}
	return c.PeriodEnd
}

func (c *CreateInvoiceRequest) GetPeriodStart() *time.Time {
	if c == nil {
		return nil
	}
	return c.PeriodStart
}

func (c *CreateInvoiceRequest) GetPreparedTaxRates() []TaxRateResponse {
	if c == nil {
		return nil
	}
	return c.PreparedTaxRates
}

func (c *CreateInvoiceRequest) GetSubscriptionID() *string {
	if c == nil {
		return nil
	}
	return c.SubscriptionID
}

func (c *CreateInvoiceRequest) GetSubtotal() string {
	if c == nil {
		return ""
	}
	return c.Subtotal
}

func (c *CreateInvoiceRequest) GetTaxRateOverrides() []TaxRateOverride {
	if c == nil {
		return nil
	}
	return c.TaxRateOverrides
}

func (c *CreateInvoiceRequest) GetTaxRates() []string {
	if c == nil {
		return nil
	}
	return c.TaxRates
}

func (c *CreateInvoiceRequest) GetTotal() string {
	if c == nil {
		return ""
	}
	return c.Total
}

func (c *CreateInvoiceRequest) GetTotalPrepaidApplied() *string {
	if c == nil {
		return nil
	}
	return c.TotalPrepaidApplied
}
