// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/tirdad-billing/go-sdk/v2/internal/utils"
	"time"
)

type CreditnoteCreditNoteLineItem struct {
	Amount            *string           `json:"amount,omitzero"`
	CreatedAt         *time.Time        `json:"created_at,omitzero"`
	CreatedBy         *string           `json:"created_by,omitzero"`
	CreditNoteID      *string           `json:"credit_note_id,omitzero"`
	Currency          *string           `json:"currency,omitzero"`
	DisplayName       *string           `json:"display_name,omitzero"`
	EnvironmentID     *string           `json:"environment_id,omitzero"`
	ID                *string           `json:"id,omitzero"`
	InvoiceLineItemID *string           `json:"invoice_line_item_id,omitzero"`
	Metadata          map[string]string `json:"metadata,omitzero"`
	Status            *Status           `json:"status,omitzero"`
	TenantID          *string           `json:"tenant_id,omitzero"`
	UpdatedAt         *time.Time        `json:"updated_at,omitzero"`
	UpdatedBy         *string           `json:"updated_by,omitzero"`
}

func (c CreditnoteCreditNoteLineItem) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreditnoteCreditNoteLineItem) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreditnoteCreditNoteLineItem) GetAmount() *string {
	if c == nil {
		return nil
	}
	return c.Amount
}

func (c *CreditnoteCreditNoteLineItem) GetCreatedAt() *time.Time {
	if c == nil {
		return nil
	}
	return c.CreatedAt
}

func (c *CreditnoteCreditNoteLineItem) GetCreatedBy() *string {
	if c == nil {
		return nil
	}
	return c.CreatedBy
}

func (c *CreditnoteCreditNoteLineItem) GetCreditNoteID() *string {
	if c == nil {
		return nil
	}
	return c.CreditNoteID
}

func (c *CreditnoteCreditNoteLineItem) GetCurrency() *string {
	if c == nil {
		return nil
	}
	return c.Currency
}

func (c *CreditnoteCreditNoteLineItem) GetDisplayName() *string {
	if c == nil {
		return nil
	}
	return c.DisplayName
}

func (c *CreditnoteCreditNoteLineItem) GetEnvironmentID() *string {
	if c == nil {
		return nil
	}
	return c.EnvironmentID
}

func (c *CreditnoteCreditNoteLineItem) GetID() *string {
	if c == nil {
		return nil
	}
	return c.ID
}

func (c *CreditnoteCreditNoteLineItem) GetInvoiceLineItemID() *string {
	if c == nil {
		return nil
	}
	return c.InvoiceLineItemID
}

func (c *CreditnoteCreditNoteLineItem) GetMetadata() map[string]string {
	if c == nil {
		return nil
	}
	return c.Metadata
}

func (c *CreditnoteCreditNoteLineItem) GetStatus() *Status {
	if c == nil {
		return nil
	}
	return c.Status
}

func (c *CreditnoteCreditNoteLineItem) GetTenantID() *string {
	if c == nil {
		return nil
	}
	return c.TenantID
}

func (c *CreditnoteCreditNoteLineItem) GetUpdatedAt() *time.Time {
	if c == nil {
		return nil
	}
	return c.UpdatedAt
}

func (c *CreditnoteCreditNoteLineItem) GetUpdatedBy() *string {
	if c == nil {
		return nil
	}
	return c.UpdatedBy
}
