// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/tirdad-billing/go-sdk/v2/internal/utils"
)

type CustomerInvoiceSummary struct {
	// currency is the three-letter ISO currency code for this summary
	Currency *string `json:"currency,omitzero"`
	// customer_id is the unique identifier of the customer
	CustomerID *string `json:"customer_id,omitzero"`
	// overdue_invoice_count is the number of overdue invoices for this customer in this currency
	OverdueInvoiceCount *int64 `json:"overdue_invoice_count,omitzero"`
	// total_invoice_count is the total number of invoices for this customer in this currency
	TotalInvoiceCount *int64 `json:"total_invoice_count,omitzero"`
	// total_overdue_amount is the total amount of overdue invoices in this currency
	TotalOverdueAmount *string `json:"total_overdue_amount,omitzero"`
	// total_revenue_amount is the total revenue generated from this customer in this currency
	TotalRevenueAmount *string `json:"total_revenue_amount,omitzero"`
	// total_unpaid_amount is the total amount of unpaid invoices in this currency
	TotalUnpaidAmount *string `json:"total_unpaid_amount,omitzero"`
	// unpaid_fixed_charges is the total amount of unpaid fixed charges in this currency
	UnpaidFixedCharges *string `json:"unpaid_fixed_charges,omitzero"`
	// unpaid_invoice_count is the number of unpaid invoices for this customer in this currency
	UnpaidInvoiceCount *int64 `json:"unpaid_invoice_count,omitzero"`
	// unpaid_usage_charges is the total amount of unpaid usage-based charges in this currency
	UnpaidUsageCharges *string `json:"unpaid_usage_charges,omitzero"`
}

func (c CustomerInvoiceSummary) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CustomerInvoiceSummary) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CustomerInvoiceSummary) GetCurrency() *string {
	if c == nil {
		return nil
	}
	return c.Currency
}

func (c *CustomerInvoiceSummary) GetCustomerID() *string {
	if c == nil {
		return nil
	}
	return c.CustomerID
}

func (c *CustomerInvoiceSummary) GetOverdueInvoiceCount() *int64 {
	if c == nil {
		return nil
	}
	return c.OverdueInvoiceCount
}

func (c *CustomerInvoiceSummary) GetTotalInvoiceCount() *int64 {
	if c == nil {
		return nil
	}
	return c.TotalInvoiceCount
}

func (c *CustomerInvoiceSummary) GetTotalOverdueAmount() *string {
	if c == nil {
		return nil
	}
	return c.TotalOverdueAmount
}

func (c *CustomerInvoiceSummary) GetTotalRevenueAmount() *string {
	if c == nil {
		return nil
	}
	return c.TotalRevenueAmount
}

func (c *CustomerInvoiceSummary) GetTotalUnpaidAmount() *string {
	if c == nil {
		return nil
	}
	return c.TotalUnpaidAmount
}

func (c *CustomerInvoiceSummary) GetUnpaidFixedCharges() *string {
	if c == nil {
		return nil
	}
	return c.UnpaidFixedCharges
}

func (c *CustomerInvoiceSummary) GetUnpaidInvoiceCount() *int64 {
	if c == nil {
		return nil
	}
	return c.UnpaidInvoiceCount
}

func (c *CustomerInvoiceSummary) GetUnpaidUsageCharges() *string {
	if c == nil {
		return nil
	}
	return c.UnpaidUsageCharges
}
