// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/tirdad-billing/go-sdk/v2/internal/utils"
)

type CustomAnalyticItem struct {
	// Name of the feature this applies to
	FeatureName *string `json:"feature_name,omitzero"`
	ID          *string `json:"id,omitzero"`
	// Calculation name (e.g., "Revenue per Minute")
	Name *string `json:"name,omitzero"`
	// "feature", "meter", "event_name"
	Type  *string `json:"type,omitzero"`
	Value *string `json:"value,omitzero"`
}

func (c CustomAnalyticItem) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CustomAnalyticItem) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CustomAnalyticItem) GetFeatureName() *string {
	if c == nil {
		return nil
	}
	return c.FeatureName
}

func (c *CustomAnalyticItem) GetID() *string {
	if c == nil {
		return nil
	}
	return c.ID
}

func (c *CustomAnalyticItem) GetName() *string {
	if c == nil {
		return nil
	}
	return c.Name
}

func (c *CustomAnalyticItem) GetType() *string {
	if c == nil {
		return nil
	}
	return c.Type
}

func (c *CustomAnalyticItem) GetValue() *string {
	if c == nil {
		return nil
	}
	return c.Value
}
