// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

type DebugTrackerStatus string

const (
	DebugTrackerStatusUnprocessed DebugTrackerStatus = "unprocessed"
	DebugTrackerStatusNotFound    DebugTrackerStatus = "not_found"
	DebugTrackerStatusFound       DebugTrackerStatus = "found"
	DebugTrackerStatusError       DebugTrackerStatus = "error"
)

func (e DebugTrackerStatus) ToPointer() *DebugTrackerStatus {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *DebugTrackerStatus) IsExact() bool {
	if e != nil {
		switch *e {
		case "unprocessed", "not_found", "found", "error":
			return true
		}
	}
	return false
}
