// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/tirdad-billing/go-sdk/v2/internal/utils"
)

type DeleteCostsheetResponse struct {
	ID      *string `json:"id,omitzero"`
	Message *string `json:"message,omitzero"`
}

func (d DeleteCostsheetResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DeleteCostsheetResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (d *DeleteCostsheetResponse) GetID() *string {
	if d == nil {
		return nil
	}
	return d.ID
}

func (d *DeleteCostsheetResponse) GetMessage() *string {
	if d == nil {
		return nil
	}
	return d.Message
}
