// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

type EntitlementGrantAllocationBehavior string

const (
	EntitlementGrantAllocationBehaviorFirstUsage EntitlementGrantAllocationBehavior = "first_usage"
	EntitlementGrantAllocationBehaviorUnitStart  EntitlementGrantAllocationBehavior = "unit_start"
)

func (e EntitlementGrantAllocationBehavior) ToPointer() *EntitlementGrantAllocationBehavior {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *EntitlementGrantAllocationBehavior) IsExact() bool {
	if e != nil {
		switch *e {
		case "first_usage", "unit_start":
			return true
		}
	}
	return false
}
