// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/tirdad-billing/go-sdk/v2/internal/utils"
)

type EntityCreationOptions struct {
	EntityCreationConflictPolicies *EntityCreationConflictPolicies `json:"entity_creation_conflict_policies,omitzero"`
}

func (e EntityCreationOptions) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *EntityCreationOptions) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (e *EntityCreationOptions) GetEntityCreationConflictPolicies() *EntityCreationConflictPolicies {
	if e == nil {
		return nil
	}
	return e.EntityCreationConflictPolicies
}
