// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

type EntitlementGrantMeasure string

const (
	EntitlementGrantMeasureQuantity EntitlementGrantMeasure = "quantity"
	EntitlementGrantMeasureAmount   EntitlementGrantMeasure = "amount"
)

func (e EntitlementGrantMeasure) ToPointer() *EntitlementGrantMeasure {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *EntitlementGrantMeasure) IsExact() bool {
	if e != nil {
		switch *e {
		case "quantity", "amount":
			return true
		}
	}
	return false
}
