// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/tirdad-billing/go-sdk/v2/internal/utils"
)

type EntityChangePolicy struct {
	DefaultBehaviour *EntityChangeBehaviour `json:"default_behaviour,omitzero"`
	// Overrides is keyed by addon_associations.id (instance), not catalogue addon_id.
	Overrides map[string]EntityChangeBehaviour `json:"overrides,omitzero"`
}

func (e EntityChangePolicy) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *EntityChangePolicy) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (e *EntityChangePolicy) GetDefaultBehaviour() *EntityChangeBehaviour {
	if e == nil {
		return nil
	}
	return e.DefaultBehaviour
}

func (e *EntityChangePolicy) GetOverrides() map[string]EntityChangeBehaviour {
	if e == nil {
		return nil
	}
	return e.Overrides
}
