// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/tirdad-billing/go-sdk/v2/internal/utils"
)

type Event struct {
	CustomerID         *string        `json:"customer_id,omitzero"`
	EnvironmentID      *string        `json:"environment_id,omitzero"`
	EventName          *string        `json:"event_name,omitzero"`
	ExternalCustomerID *string        `json:"external_customer_id,omitzero"`
	ID                 *string        `json:"id,omitzero"`
	Properties         map[string]any `json:"properties,omitzero"`
	Source             *string        `json:"source,omitzero"`
	Timestamp          *string        `json:"timestamp,omitzero"`
}

func (e Event) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *Event) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (e *Event) GetCustomerID() *string {
	if e == nil {
		return nil
	}
	return e.CustomerID
}

func (e *Event) GetEnvironmentID() *string {
	if e == nil {
		return nil
	}
	return e.EnvironmentID
}

func (e *Event) GetEventName() *string {
	if e == nil {
		return nil
	}
	return e.EventName
}

func (e *Event) GetExternalCustomerID() *string {
	if e == nil {
		return nil
	}
	return e.ExternalCustomerID
}

func (e *Event) GetID() *string {
	if e == nil {
		return nil
	}
	return e.ID
}

func (e *Event) GetProperties() map[string]any {
	if e == nil {
		return nil
	}
	return e.Properties
}

func (e *Event) GetSource() *string {
	if e == nil {
		return nil
	}
	return e.Source
}

func (e *Event) GetTimestamp() *string {
	if e == nil {
		return nil
	}
	return e.Timestamp
}
