// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/tirdad-billing/go-sdk/v2/internal/utils"
)

type FailurePoint struct {
	Error            *ErrorResponse    `json:"error,omitzero"`
	FailurePointType *FailurePointType `json:"failure_point_type,omitzero"`
}

func (f FailurePoint) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(f, "", false)
}

func (f *FailurePoint) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &f, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (f *FailurePoint) GetError() *ErrorResponse {
	if f == nil {
		return nil
	}
	return f.Error
}

func (f *FailurePoint) GetFailurePointType() *FailurePointType {
	if f == nil {
		return nil
	}
	return f.FailurePointType
}
