// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/tirdad-billing/go-sdk/v2/internal/utils"
	"time"
)

type FxConversion struct {
	// BillingCurrency is the currency the invoice was issued in.
	BillingCurrency *string `json:"billing_currency,omitzero"`
	// ChargeCurrency is the invoice's original (draft) currency.
	ChargeCurrency *string `json:"charge_currency,omitzero"`
	// ConvertedAt is when the conversion ran.
	ConvertedAt *time.Time `json:"converted_at,omitzero"`
	// Rate is the frozen rate: billing per 1 charge unit.
	Rate *string `json:"rate,omitzero"`
	// RateID is the fx_rates row used, for reference only; never read again.
	RateID *string             `json:"rate_id,omitzero"`
	Scope  *FXRateScope        `json:"scope,omitzero"`
	Source *FxConversionSource `json:"source,omitzero"`
}

func (f FxConversion) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(f, "", false)
}

func (f *FxConversion) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &f, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (f *FxConversion) GetBillingCurrency() *string {
	if f == nil {
		return nil
	}
	return f.BillingCurrency
}

func (f *FxConversion) GetChargeCurrency() *string {
	if f == nil {
		return nil
	}
	return f.ChargeCurrency
}

func (f *FxConversion) GetConvertedAt() *time.Time {
	if f == nil {
		return nil
	}
	return f.ConvertedAt
}

func (f *FxConversion) GetRate() *string {
	if f == nil {
		return nil
	}
	return f.Rate
}

func (f *FxConversion) GetRateID() *string {
	if f == nil {
		return nil
	}
	return f.RateID
}

func (f *FxConversion) GetScope() *FXRateScope {
	if f == nil {
		return nil
	}
	return f.Scope
}

func (f *FxConversion) GetSource() *FxConversionSource {
	if f == nil {
		return nil
	}
	return f.Source
}
