// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"encoding/json"
	"fmt"
	"github.com/tirdad-billing/go-sdk/v2/internal/utils"
	"time"
)

type FXRateFilterOrder string

const (
	FXRateFilterOrderAsc  FXRateFilterOrder = "asc"
	FXRateFilterOrderDesc FXRateFilterOrder = "desc"
)

func (e FXRateFilterOrder) ToPointer() *FXRateFilterOrder {
	return &e
}
func (e *FXRateFilterOrder) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "asc":
		fallthrough
	case "desc":
		*e = FXRateFilterOrder(v)
		return nil
	default:
		return fmt.Errorf("invalid value for FXRateFilterOrder: %v", v)
	}
}

type FXRateFilter struct {
	EndTime      *time.Time         `json:"end_time,omitzero"`
	Expand       *string            `json:"expand,omitzero"`
	Filters      []FilterCondition  `json:"filters,omitzero"`
	FromCurrency *string            `json:"from_currency,omitzero"`
	FxRateIds    []string           `json:"fx_rate_ids,omitzero"`
	Limit        *int64             `json:"limit,omitzero"`
	Offset       *int64             `json:"offset,omitzero"`
	Order        *FXRateFilterOrder `json:"order,omitzero"`
	Scope        *FXRateScope       `json:"scope,omitzero"`
	ScopeID      *string            `json:"scope_id,omitzero"`
	Sort         []SortCondition    `json:"sort,omitzero"`
	StartTime    *time.Time         `json:"start_time,omitzero"`
	Status       *Status            `json:"status,omitzero"`
	ToCurrency   *string            `json:"to_currency,omitzero"`
}

func (f FXRateFilter) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(f, "", false)
}

func (f *FXRateFilter) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &f, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (f *FXRateFilter) GetEndTime() *time.Time {
	if f == nil {
		return nil
	}
	return f.EndTime
}

func (f *FXRateFilter) GetExpand() *string {
	if f == nil {
		return nil
	}
	return f.Expand
}

func (f *FXRateFilter) GetFilters() []FilterCondition {
	if f == nil {
		return nil
	}
	return f.Filters
}

func (f *FXRateFilter) GetFromCurrency() *string {
	if f == nil {
		return nil
	}
	return f.FromCurrency
}

func (f *FXRateFilter) GetFxRateIds() []string {
	if f == nil {
		return nil
	}
	return f.FxRateIds
}

func (f *FXRateFilter) GetLimit() *int64 {
	if f == nil {
		return nil
	}
	return f.Limit
}

func (f *FXRateFilter) GetOffset() *int64 {
	if f == nil {
		return nil
	}
	return f.Offset
}

func (f *FXRateFilter) GetOrder() *FXRateFilterOrder {
	if f == nil {
		return nil
	}
	return f.Order
}

func (f *FXRateFilter) GetScope() *FXRateScope {
	if f == nil {
		return nil
	}
	return f.Scope
}

func (f *FXRateFilter) GetScopeID() *string {
	if f == nil {
		return nil
	}
	return f.ScopeID
}

func (f *FXRateFilter) GetSort() []SortCondition {
	if f == nil {
		return nil
	}
	return f.Sort
}

func (f *FXRateFilter) GetStartTime() *time.Time {
	if f == nil {
		return nil
	}
	return f.StartTime
}

func (f *FXRateFilter) GetStatus() *Status {
	if f == nil {
		return nil
	}
	return f.Status
}

func (f *FXRateFilter) GetToCurrency() *string {
	if f == nil {
		return nil
	}
	return f.ToCurrency
}
