// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/tirdad-billing/go-sdk/v2/internal/utils"
)

type GetUsageAnalyticsResponse struct {
	Currency        *string              `json:"currency,omitzero"`
	CustomAnalytics []CustomAnalyticItem `json:"custom_analytics,omitzero"`
	Items           []UsageAnalyticItem  `json:"items,omitzero"`
	TotalCost       *string              `json:"total_cost,omitzero"`
}

func (g GetUsageAnalyticsResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetUsageAnalyticsResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetUsageAnalyticsResponse) GetCurrency() *string {
	if g == nil {
		return nil
	}
	return g.Currency
}

func (g *GetUsageAnalyticsResponse) GetCustomAnalytics() []CustomAnalyticItem {
	if g == nil {
		return nil
	}
	return g.CustomAnalytics
}

func (g *GetUsageAnalyticsResponse) GetItems() []UsageAnalyticItem {
	if g == nil {
		return nil
	}
	return g.Items
}

func (g *GetUsageAnalyticsResponse) GetTotalCost() *string {
	if g == nil {
		return nil
	}
	return g.TotalCost
}
