// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/tirdad-billing/go-sdk/v2/internal/utils"
	"time"
)

type GetUsageByMeterRequest struct {
	// BillingAnchor enables custom monthly billing periods for meter usage aggregation.
	//
	// Usage guidelines:
	// - Only effective when WindowSize = "MONTH"
	// - For other window sizes (DAY, HOUR, WEEK), this field is ignored
	// - When nil, uses standard calendar months (1st to 1st)
	// - When provided, creates custom monthly periods (e.g., 5th to 5th)
	//
	// Common use cases:
	// - Subscription billing periods that don't align with calendar months
	// - Customer-specific billing cycles (e.g., signed up on 15th)
	// - Multi-tenant systems with different billing anchor dates
	//
	// Example: If BillingAnchor = "2024-03-05T14:30:45Z" and WindowSize = "MONTH":
	//   - March period: 2024-03-05 14:30:45 to 2024-04-05 14:30:45
	//   - April period: 2024-04-05 14:30:45 to 2024-05-05 14:30:45
	BillingAnchor      *time.Time          `json:"billing_anchor,omitzero"`
	BucketSize         *WindowSize         `json:"bucket_size,omitzero"`
	CustomerID         *string             `json:"customer_id,omitzero"`
	EndTime            *time.Time          `json:"end_time,omitzero"`
	ExternalCustomerID *string             `json:"external_customer_id,omitzero"`
	Filters            map[string][]string `json:"filters,omitzero"`
	MeterID            string              `json:"meter_id"`
	StartTime          *time.Time          `json:"start_time,omitzero"`
	Timezone           *string             `json:"timezone,omitzero"`
	WindowSize         *WindowSize         `json:"window_size,omitzero"`
}

func (g GetUsageByMeterRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetUsageByMeterRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, []string{"meter_id"}); err != nil {
		return err
	}
	return nil
}

func (g *GetUsageByMeterRequest) GetBillingAnchor() *time.Time {
	if g == nil {
		return nil
	}
	return g.BillingAnchor
}

func (g *GetUsageByMeterRequest) GetBucketSize() *WindowSize {
	if g == nil {
		return nil
	}
	return g.BucketSize
}

func (g *GetUsageByMeterRequest) GetCustomerID() *string {
	if g == nil {
		return nil
	}
	return g.CustomerID
}

func (g *GetUsageByMeterRequest) GetEndTime() *time.Time {
	if g == nil {
		return nil
	}
	return g.EndTime
}

func (g *GetUsageByMeterRequest) GetExternalCustomerID() *string {
	if g == nil {
		return nil
	}
	return g.ExternalCustomerID
}

func (g *GetUsageByMeterRequest) GetFilters() map[string][]string {
	if g == nil {
		return nil
	}
	return g.Filters
}

func (g *GetUsageByMeterRequest) GetMeterID() string {
	if g == nil {
		return ""
	}
	return g.MeterID
}

func (g *GetUsageByMeterRequest) GetStartTime() *time.Time {
	if g == nil {
		return nil
	}
	return g.StartTime
}

func (g *GetUsageByMeterRequest) GetTimezone() *string {
	if g == nil {
		return nil
	}
	return g.Timezone
}

func (g *GetUsageByMeterRequest) GetWindowSize() *WindowSize {
	if g == nil {
		return nil
	}
	return g.WindowSize
}
