// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/tirdad-billing/go-sdk/v2/internal/utils"
)

type GroupedInvoicingChildRequest struct {
	ExternalCustomerID string `json:"external_customer_id"`
	PlanID             string `json:"plan_id"`
}

func (g GroupedInvoicingChildRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GroupedInvoicingChildRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, []string{"external_customer_id", "plan_id"}); err != nil {
		return err
	}
	return nil
}

func (g *GroupedInvoicingChildRequest) GetExternalCustomerID() string {
	if g == nil {
		return ""
	}
	return g.ExternalCustomerID
}

func (g *GroupedInvoicingChildRequest) GetPlanID() string {
	if g == nil {
		return ""
	}
	return g.PlanID
}
