// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/tirdad-billing/go-sdk/v2/internal/utils"
)

type IngestEventRequest struct {
	CustomerID         *string `json:"customer_id,omitzero"`
	EventID            *string `json:"event_id,omitzero"`
	EventName          string  `json:"event_name"`
	ExternalCustomerID string  `json:"external_customer_id"`
	// Handled separately for dynamic columns
	Properties map[string]string `json:"properties,omitzero"`
	Source     *string           `json:"source,omitzero"`
	// Handled separately due to parsing
	Timestamp *string `json:"timestamp,omitzero"`
}

func (i IngestEventRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(i, "", false)
}

func (i *IngestEventRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &i, "", false, []string{"event_name", "external_customer_id"}); err != nil {
		return err
	}
	return nil
}

func (i *IngestEventRequest) GetCustomerID() *string {
	if i == nil {
		return nil
	}
	return i.CustomerID
}

func (i *IngestEventRequest) GetEventID() *string {
	if i == nil {
		return nil
	}
	return i.EventID
}

func (i *IngestEventRequest) GetEventName() string {
	if i == nil {
		return ""
	}
	return i.EventName
}

func (i *IngestEventRequest) GetExternalCustomerID() string {
	if i == nil {
		return ""
	}
	return i.ExternalCustomerID
}

func (i *IngestEventRequest) GetProperties() map[string]string {
	if i == nil {
		return nil
	}
	return i.Properties
}

func (i *IngestEventRequest) GetSource() *string {
	if i == nil {
		return nil
	}
	return i.Source
}

func (i *IngestEventRequest) GetTimestamp() *string {
	if i == nil {
		return nil
	}
	return i.Timestamp
}
