// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/tirdad-billing/go-sdk/v2/internal/utils"
	"time"
)

type InlineFXRate struct {
	EndDate   *time.Time `json:"end_date,omitzero"`
	Rate      *string    `json:"rate,omitzero"`
	StartDate *time.Time `json:"start_date,omitzero"`
}

func (i InlineFXRate) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(i, "", false)
}

func (i *InlineFXRate) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &i, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (i *InlineFXRate) GetEndDate() *time.Time {
	if i == nil {
		return nil
	}
	return i.EndDate
}

func (i *InlineFXRate) GetRate() *string {
	if i == nil {
		return nil
	}
	return i.Rate
}

func (i *InlineFXRate) GetStartDate() *time.Time {
	if i == nil {
		return nil
	}
	return i.StartDate
}
