// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

type InvoiceCadence string

const (
	InvoiceCadenceArrear  InvoiceCadence = "ARREAR"
	InvoiceCadenceAdvance InvoiceCadence = "ADVANCE"
)

func (e InvoiceCadence) ToPointer() *InvoiceCadence {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *InvoiceCadence) IsExact() bool {
	if e != nil {
		switch *e {
		case "ARREAR", "ADVANCE":
			return true
		}
	}
	return false
}
