// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/tirdad-billing/go-sdk/v2/internal/utils"
	"time"
)

type InvoicePreview struct {
	// currency is the currency for all amounts
	Currency *string `json:"currency,omitzero"`
	// due_date is when the invoice would be due
	DueDate *time.Time `json:"due_date,omitzero"`
	// line_items contains preview of line items
	LineItems []InvoiceLineItemPreview `json:"line_items,omitzero"`
	// subtotal is the subtotal amount before taxes
	Subtotal *string `json:"subtotal,omitzero"`
	// tax_amount is the total tax amount
	TaxAmount *string `json:"tax_amount,omitzero"`
	// total is the total amount including taxes
	Total *string `json:"total,omitzero"`
}

func (i InvoicePreview) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(i, "", false)
}

func (i *InvoicePreview) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &i, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (i *InvoicePreview) GetCurrency() *string {
	if i == nil {
		return nil
	}
	return i.Currency
}

func (i *InvoicePreview) GetDueDate() *time.Time {
	if i == nil {
		return nil
	}
	return i.DueDate
}

func (i *InvoicePreview) GetLineItems() []InvoiceLineItemPreview {
	if i == nil {
		return nil
	}
	return i.LineItems
}

func (i *InvoicePreview) GetSubtotal() *string {
	if i == nil {
		return nil
	}
	return i.Subtotal
}

func (i *InvoicePreview) GetTaxAmount() *string {
	if i == nil {
		return nil
	}
	return i.TaxAmount
}

func (i *InvoicePreview) GetTotal() *string {
	if i == nil {
		return nil
	}
	return i.Total
}
