// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/tirdad-billing/go-sdk/v2/internal/utils"
	"time"
)

type LineItemChange struct {
	// Amount reprices the charge. Flat fee only for now.
	Amount        *string    `json:"amount,omitzero"`
	EffectiveDate *time.Time `json:"effective_date,omitzero"`
	ID            string     `json:"id"`
	Quantity      *string    `json:"quantity,omitzero"`
}

func (l LineItemChange) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *LineItemChange) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, []string{"id"}); err != nil {
		return err
	}
	return nil
}

func (l *LineItemChange) GetAmount() *string {
	if l == nil {
		return nil
	}
	return l.Amount
}

func (l *LineItemChange) GetEffectiveDate() *time.Time {
	if l == nil {
		return nil
	}
	return l.EffectiveDate
}

func (l *LineItemChange) GetID() string {
	if l == nil {
		return ""
	}
	return l.ID
}

func (l *LineItemChange) GetQuantity() *string {
	if l == nil {
		return nil
	}
	return l.Quantity
}
