// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/tirdad-billing/go-sdk/v2/internal/utils"
)

type ListGroupsResponse struct {
	Items      []GroupResponse     `json:"items,omitzero"`
	Pagination *PaginationResponse `json:"pagination,omitzero"`
}

func (l ListGroupsResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListGroupsResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListGroupsResponse) GetItems() []GroupResponse {
	if l == nil {
		return nil
	}
	return l.Items
}

func (l *ListGroupsResponse) GetPagination() *PaginationResponse {
	if l == nil {
		return nil
	}
	return l.Pagination
}
