// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/tirdad-billing/go-sdk/v2/internal/utils"
)

type ListInvoicesResponse struct {
	Items      []InvoiceResponse   `json:"items,omitzero"`
	Pagination *PaginationResponse `json:"pagination,omitzero"`
}

func (l ListInvoicesResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListInvoicesResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListInvoicesResponse) GetItems() []InvoiceResponse {
	if l == nil {
		return nil
	}
	return l.Items
}

func (l *ListInvoicesResponse) GetPagination() *PaginationResponse {
	if l == nil {
		return nil
	}
	return l.Pagination
}
