// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/tirdad-billing/go-sdk/v2/internal/utils"
)

type ModelsTemporalWorkflowResult struct {
	Message    *string `json:"message,omitzero"`
	RunID      *string `json:"run_id,omitzero"`
	WorkflowID *string `json:"workflow_id,omitzero"`
}

func (m ModelsTemporalWorkflowResult) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(m, "", false)
}

func (m *ModelsTemporalWorkflowResult) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &m, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (m *ModelsTemporalWorkflowResult) GetMessage() *string {
	if m == nil {
		return nil
	}
	return m.Message
}

func (m *ModelsTemporalWorkflowResult) GetRunID() *string {
	if m == nil {
		return nil
	}
	return m.RunID
}

func (m *ModelsTemporalWorkflowResult) GetWorkflowID() *string {
	if m == nil {
		return nil
	}
	return m.WorkflowID
}
