// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

type PauseStatus string

const (
	PauseStatusNone      PauseStatus = "none"
	PauseStatusActive    PauseStatus = "active"
	PauseStatusScheduled PauseStatus = "scheduled"
	PauseStatusCompleted PauseStatus = "completed"
	PauseStatusCancelled PauseStatus = "cancelled"
)

func (e PauseStatus) ToPointer() *PauseStatus {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *PauseStatus) IsExact() bool {
	if e != nil {
		switch *e {
		case "none", "active", "scheduled", "completed", "cancelled":
			return true
		}
	}
	return false
}
