// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/tirdad-billing/go-sdk/v2/internal/utils"
	"time"
)

type PaymentResponse struct {
	Amount                 *string                  `json:"amount,omitzero"`
	Attempts               []PaymentAttemptResponse `json:"attempts,omitzero"`
	CreatedAt              *time.Time               `json:"created_at,omitzero"`
	CreatedBy              *string                  `json:"created_by,omitzero"`
	Currency               *string                  `json:"currency,omitzero"`
	DestinationID          *string                  `json:"destination_id,omitzero"`
	DestinationType        *PaymentDestinationType  `json:"destination_type,omitzero"`
	ErrorMessage           *string                  `json:"error_message,omitzero"`
	FailedAt               *time.Time               `json:"failed_at,omitzero"`
	GatewayMetadata        map[string]string        `json:"gateway_metadata,omitzero"`
	GatewayPaymentID       *string                  `json:"gateway_payment_id,omitzero"`
	GatewayTrackingID      *string                  `json:"gateway_tracking_id,omitzero"`
	ID                     *string                  `json:"id,omitzero"`
	IdempotencyKey         *string                  `json:"idempotency_key,omitzero"`
	InvoiceNumber          *string                  `json:"invoice_number,omitzero"`
	Metadata               map[string]string        `json:"metadata,omitzero"`
	PaymentGateway         *string                  `json:"payment_gateway,omitzero"`
	PaymentMethodID        *string                  `json:"payment_method_id,omitzero"`
	PaymentMethodType      *PaymentMethodType       `json:"payment_method_type,omitzero"`
	PaymentStatus          *PaymentStatus           `json:"payment_status,omitzero"`
	PaymentURL             *string                  `json:"payment_url,omitzero"`
	RefundedAt             *time.Time               `json:"refunded_at,omitzero"`
	SaveCardAndMakeDefault *bool                    `json:"save_card_and_make_default,omitzero"`
	SucceededAt            *time.Time               `json:"succeeded_at,omitzero"`
	TenantID               *string                  `json:"tenant_id,omitzero"`
	TrackAttempts          *bool                    `json:"track_attempts,omitzero"`
	UpdatedAt              *time.Time               `json:"updated_at,omitzero"`
	UpdatedBy              *string                  `json:"updated_by,omitzero"`
}

func (p PaymentResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PaymentResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PaymentResponse) GetAmount() *string {
	if p == nil {
		return nil
	}
	return p.Amount
}

func (p *PaymentResponse) GetAttempts() []PaymentAttemptResponse {
	if p == nil {
		return nil
	}
	return p.Attempts
}

func (p *PaymentResponse) GetCreatedAt() *time.Time {
	if p == nil {
		return nil
	}
	return p.CreatedAt
}

func (p *PaymentResponse) GetCreatedBy() *string {
	if p == nil {
		return nil
	}
	return p.CreatedBy
}

func (p *PaymentResponse) GetCurrency() *string {
	if p == nil {
		return nil
	}
	return p.Currency
}

func (p *PaymentResponse) GetDestinationID() *string {
	if p == nil {
		return nil
	}
	return p.DestinationID
}

func (p *PaymentResponse) GetDestinationType() *PaymentDestinationType {
	if p == nil {
		return nil
	}
	return p.DestinationType
}

func (p *PaymentResponse) GetErrorMessage() *string {
	if p == nil {
		return nil
	}
	return p.ErrorMessage
}

func (p *PaymentResponse) GetFailedAt() *time.Time {
	if p == nil {
		return nil
	}
	return p.FailedAt
}

func (p *PaymentResponse) GetGatewayMetadata() map[string]string {
	if p == nil {
		return nil
	}
	return p.GatewayMetadata
}

func (p *PaymentResponse) GetGatewayPaymentID() *string {
	if p == nil {
		return nil
	}
	return p.GatewayPaymentID
}

func (p *PaymentResponse) GetGatewayTrackingID() *string {
	if p == nil {
		return nil
	}
	return p.GatewayTrackingID
}

func (p *PaymentResponse) GetID() *string {
	if p == nil {
		return nil
	}
	return p.ID
}

func (p *PaymentResponse) GetIdempotencyKey() *string {
	if p == nil {
		return nil
	}
	return p.IdempotencyKey
}

func (p *PaymentResponse) GetInvoiceNumber() *string {
	if p == nil {
		return nil
	}
	return p.InvoiceNumber
}

func (p *PaymentResponse) GetMetadata() map[string]string {
	if p == nil {
		return nil
	}
	return p.Metadata
}

func (p *PaymentResponse) GetPaymentGateway() *string {
	if p == nil {
		return nil
	}
	return p.PaymentGateway
}

func (p *PaymentResponse) GetPaymentMethodID() *string {
	if p == nil {
		return nil
	}
	return p.PaymentMethodID
}

func (p *PaymentResponse) GetPaymentMethodType() *PaymentMethodType {
	if p == nil {
		return nil
	}
	return p.PaymentMethodType
}

func (p *PaymentResponse) GetPaymentStatus() *PaymentStatus {
	if p == nil {
		return nil
	}
	return p.PaymentStatus
}

func (p *PaymentResponse) GetPaymentURL() *string {
	if p == nil {
		return nil
	}
	return p.PaymentURL
}

func (p *PaymentResponse) GetRefundedAt() *time.Time {
	if p == nil {
		return nil
	}
	return p.RefundedAt
}

func (p *PaymentResponse) GetSaveCardAndMakeDefault() *bool {
	if p == nil {
		return nil
	}
	return p.SaveCardAndMakeDefault
}

func (p *PaymentResponse) GetSucceededAt() *time.Time {
	if p == nil {
		return nil
	}
	return p.SucceededAt
}

func (p *PaymentResponse) GetTenantID() *string {
	if p == nil {
		return nil
	}
	return p.TenantID
}

func (p *PaymentResponse) GetTrackAttempts() *bool {
	if p == nil {
		return nil
	}
	return p.TrackAttempts
}

func (p *PaymentResponse) GetUpdatedAt() *time.Time {
	if p == nil {
		return nil
	}
	return p.UpdatedAt
}

func (p *PaymentResponse) GetUpdatedBy() *string {
	if p == nil {
		return nil
	}
	return p.UpdatedBy
}
