// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

type PaymentMethodType string

const (
	PaymentMethodTypeCard        PaymentMethodType = "CARD"
	PaymentMethodTypeAch         PaymentMethodType = "ACH"
	PaymentMethodTypeOffline     PaymentMethodType = "OFFLINE"
	PaymentMethodTypeCredits     PaymentMethodType = "CREDITS"
	PaymentMethodTypePaymentLink PaymentMethodType = "PAYMENT_LINK"
)

func (e PaymentMethodType) ToPointer() *PaymentMethodType {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *PaymentMethodType) IsExact() bool {
	if e != nil {
		switch *e {
		case "CARD", "ACH", "OFFLINE", "CREDITS", "PAYMENT_LINK":
			return true
		}
	}
	return false
}
