// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

type PaymentActionType string

const (
	PaymentActionTypeCheckoutURL PaymentActionType = "checkout_url"
	PaymentActionTypePaymentLink PaymentActionType = "payment_link"
)

func (e PaymentActionType) ToPointer() *PaymentActionType {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *PaymentActionType) IsExact() bool {
	if e != nil {
		switch *e {
		case "checkout_url", "payment_link":
			return true
		}
	}
	return false
}
