// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/tirdad-billing/go-sdk/v2/internal/utils"
	"time"
)

type PlanChangeScheduleResult struct {
	ChangeType    *string    `json:"change_type,omitzero"`
	EffectiveDate *time.Time `json:"effective_date,omitzero"`
	FromPlanID    *string    `json:"from_plan_id,omitzero"`
	// previous_subscription_id is set when the change replaced the subscription with a new one
	PreviousSubscriptionID *string `json:"previous_subscription_id,omitzero"`
	SubscriptionID         *string `json:"subscription_id,omitzero"`
	ToPlanID               *string `json:"to_plan_id,omitzero"`
}

func (p PlanChangeScheduleResult) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PlanChangeScheduleResult) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PlanChangeScheduleResult) GetChangeType() *string {
	if p == nil {
		return nil
	}
	return p.ChangeType
}

func (p *PlanChangeScheduleResult) GetEffectiveDate() *time.Time {
	if p == nil {
		return nil
	}
	return p.EffectiveDate
}

func (p *PlanChangeScheduleResult) GetFromPlanID() *string {
	if p == nil {
		return nil
	}
	return p.FromPlanID
}

func (p *PlanChangeScheduleResult) GetPreviousSubscriptionID() *string {
	if p == nil {
		return nil
	}
	return p.PreviousSubscriptionID
}

func (p *PlanChangeScheduleResult) GetSubscriptionID() *string {
	if p == nil {
		return nil
	}
	return p.SubscriptionID
}

func (p *PlanChangeScheduleResult) GetToPlanID() *string {
	if p == nil {
		return nil
	}
	return p.ToPlanID
}
