// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/tirdad-billing/go-sdk/v2/internal/utils"
	"time"
)

type Plan struct {
	CreatedAt     *time.Time        `json:"created_at,omitzero"`
	CreatedBy     *string           `json:"created_by,omitzero"`
	Description   *string           `json:"description,omitzero"`
	DisplayOrder  *int64            `json:"display_order,omitzero"`
	EnvironmentID *string           `json:"environment_id,omitzero"`
	ID            *string           `json:"id,omitzero"`
	LookupKey     *string           `json:"lookup_key,omitzero"`
	Metadata      map[string]string `json:"metadata,omitzero"`
	Name          *string           `json:"name,omitzero"`
	Status        *Status           `json:"status,omitzero"`
	TenantID      *string           `json:"tenant_id,omitzero"`
	UpdatedAt     *time.Time        `json:"updated_at,omitzero"`
	UpdatedBy     *string           `json:"updated_by,omitzero"`
}

func (p Plan) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *Plan) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *Plan) GetCreatedAt() *time.Time {
	if p == nil {
		return nil
	}
	return p.CreatedAt
}

func (p *Plan) GetCreatedBy() *string {
	if p == nil {
		return nil
	}
	return p.CreatedBy
}

func (p *Plan) GetDescription() *string {
	if p == nil {
		return nil
	}
	return p.Description
}

func (p *Plan) GetDisplayOrder() *int64 {
	if p == nil {
		return nil
	}
	return p.DisplayOrder
}

func (p *Plan) GetEnvironmentID() *string {
	if p == nil {
		return nil
	}
	return p.EnvironmentID
}

func (p *Plan) GetID() *string {
	if p == nil {
		return nil
	}
	return p.ID
}

func (p *Plan) GetLookupKey() *string {
	if p == nil {
		return nil
	}
	return p.LookupKey
}

func (p *Plan) GetMetadata() map[string]string {
	if p == nil {
		return nil
	}
	return p.Metadata
}

func (p *Plan) GetName() *string {
	if p == nil {
		return nil
	}
	return p.Name
}

func (p *Plan) GetStatus() *Status {
	if p == nil {
		return nil
	}
	return p.Status
}

func (p *Plan) GetTenantID() *string {
	if p == nil {
		return nil
	}
	return p.TenantID
}

func (p *Plan) GetUpdatedAt() *time.Time {
	if p == nil {
		return nil
	}
	return p.UpdatedAt
}

func (p *Plan) GetUpdatedBy() *string {
	if p == nil {
		return nil
	}
	return p.UpdatedBy
}
