// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/tirdad-billing/go-sdk/v2/internal/utils"
	"github.com/tirdad-billing/go-sdk/v2/optionalnullable"
	"time"
)

type PricePrice struct {
	// Amount stored in main currency units (e.g., dollars, not cents)
	// For USD: 12.50 means $12.50
	Amount         *string         `json:"amount,omitzero"`
	BillingCadence *BillingCadence `json:"billing_cadence,omitzero"`
	BillingModel   *BillingModel   `json:"billing_model,omitzero"`
	BillingPeriod  *BillingPeriod  `json:"billing_period,omitzero"`
	// BillingPeriodCount is the count of the billing period ex 1, 3, 6, 12
	BillingPeriodCount *int64 `json:"billing_period_count,omitzero"`
	// ConversionRate is the conversion rate of the price unit to the fiat currency
	ConversionRate *string    `json:"conversion_rate,omitzero"`
	CreatedAt      *time.Time `json:"created_at,omitzero"`
	CreatedBy      *string    `json:"created_by,omitzero"`
	// Currency 3 digit ISO currency code in lowercase ex usd, eur, gbp
	Currency *string `json:"currency,omitzero"`
	// Description of the price
	Description *string `json:"description,omitzero"`
	// DisplayAmount is the formatted amount with currency symbol
	// For USD: $12.50
	DisplayAmount *string `json:"display_amount,omitzero"`
	// DisplayName is the name of the price
	DisplayName *string `json:"display_name,omitzero"`
	// DisplayPriceUnitAmount is the formatted amount of the price unit
	DisplayPriceUnitAmount *string `json:"display_price_unit_amount,omitzero"`
	// EndDate is the end date of the price
	EndDate *time.Time `json:"end_date,omitzero"`
	// EntityID holds the value of the "entity_id" field.
	EntityID   *string          `json:"entity_id,omitzero"`
	EntityType *PriceEntityType `json:"entity_type,omitzero"`
	// EnvironmentID is the environment identifier for the price
	EnvironmentID *string `json:"environment_id,omitzero"`
	// GroupID references the group this price belongs to
	GroupID *string `json:"group_id,omitzero"`
	// ID uuid identifier for the price
	ID             *string         `json:"id,omitzero"`
	InvoiceCadence *InvoiceCadence `json:"invoice_cadence,omitzero"`
	// LookupKey used for looking up the price in the database
	LookupKey *string           `json:"lookup_key,omitzero"`
	Metadata  map[string]string `json:"metadata,omitzero"`
	// MeterID is the id of the meter for usage based pricing
	MeterID *string `json:"meter_id,omitzero"`
	// MinQuantity is the minimum quantity of the price
	MinQuantity optionalnullable.OptionalNullable[string] `json:"min_quantity,omitzero"`
	// ParentPriceID references the root price (always set for price lineage tracking)
	ParentPriceID *string `json:"parent_price_id,omitzero"`
	// PriceUnit is the code of the price unit (e.g., 'btc', 'eth')
	PriceUnit *string `json:"price_unit,omitzero"`
	// PriceUnitAmount is the amount of the price unit
	PriceUnitAmount *string `json:"price_unit_amount,omitzero"`
	// PriceUnitID is the id of the price unit (for CUSTOM type)
	PriceUnitID *string `json:"price_unit_id,omitzero"`
	// PriceUnitTiers are the tiers for the price unit when BillingModel is TIERED
	PriceUnitTiers []PricePriceTier `json:"price_unit_tiers,omitzero"`
	PriceUnitType  *PriceUnitType   `json:"price_unit_type,omitzero"`
	// Sequence is the monotonic stamp bumped on every state change that
	// subscription line items need to react to. Read by the plan-price sync;
	// set by the database (DEFAULT nextval) on create and by the price
	// repository on termination / compatibility-affecting edits.
	Sequence *int64 `json:"sequence,omitzero"`
	// StartDate is the start date of the price
	StartDate         *time.Time                   `json:"start_date,omitzero"`
	Status            *Status                      `json:"status,omitzero"`
	TenantID          *string                      `json:"tenant_id,omitzero"`
	TierMode          *BillingTier                 `json:"tier_mode,omitzero"`
	Tiers             []PricePriceTier             `json:"tiers,omitzero"`
	TransformQuantity *PriceJSONBTransformQuantity `json:"transform_quantity,omitzero"`
	// TrialPeriodDays is the number of days for the trial period
	// Note: This is only applicable for recurring prices (BILLING_CADENCE_RECURRING)
	TrialPeriodDays *int64     `json:"trial_period_days,omitzero"`
	Type            *PriceType `json:"type,omitzero"`
	UpdatedAt       *time.Time `json:"updated_at,omitzero"`
	UpdatedBy       *string    `json:"updated_by,omitzero"`
}

func (p PricePrice) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PricePrice) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PricePrice) GetAmount() *string {
	if p == nil {
		return nil
	}
	return p.Amount
}

func (p *PricePrice) GetBillingCadence() *BillingCadence {
	if p == nil {
		return nil
	}
	return p.BillingCadence
}

func (p *PricePrice) GetBillingModel() *BillingModel {
	if p == nil {
		return nil
	}
	return p.BillingModel
}

func (p *PricePrice) GetBillingPeriod() *BillingPeriod {
	if p == nil {
		return nil
	}
	return p.BillingPeriod
}

func (p *PricePrice) GetBillingPeriodCount() *int64 {
	if p == nil {
		return nil
	}
	return p.BillingPeriodCount
}

func (p *PricePrice) GetConversionRate() *string {
	if p == nil {
		return nil
	}
	return p.ConversionRate
}

func (p *PricePrice) GetCreatedAt() *time.Time {
	if p == nil {
		return nil
	}
	return p.CreatedAt
}

func (p *PricePrice) GetCreatedBy() *string {
	if p == nil {
		return nil
	}
	return p.CreatedBy
}

func (p *PricePrice) GetCurrency() *string {
	if p == nil {
		return nil
	}
	return p.Currency
}

func (p *PricePrice) GetDescription() *string {
	if p == nil {
		return nil
	}
	return p.Description
}

func (p *PricePrice) GetDisplayAmount() *string {
	if p == nil {
		return nil
	}
	return p.DisplayAmount
}

func (p *PricePrice) GetDisplayName() *string {
	if p == nil {
		return nil
	}
	return p.DisplayName
}

func (p *PricePrice) GetDisplayPriceUnitAmount() *string {
	if p == nil {
		return nil
	}
	return p.DisplayPriceUnitAmount
}

func (p *PricePrice) GetEndDate() *time.Time {
	if p == nil {
		return nil
	}
	return p.EndDate
}

func (p *PricePrice) GetEntityID() *string {
	if p == nil {
		return nil
	}
	return p.EntityID
}

func (p *PricePrice) GetEntityType() *PriceEntityType {
	if p == nil {
		return nil
	}
	return p.EntityType
}

func (p *PricePrice) GetEnvironmentID() *string {
	if p == nil {
		return nil
	}
	return p.EnvironmentID
}

func (p *PricePrice) GetGroupID() *string {
	if p == nil {
		return nil
	}
	return p.GroupID
}

func (p *PricePrice) GetID() *string {
	if p == nil {
		return nil
	}
	return p.ID
}

func (p *PricePrice) GetInvoiceCadence() *InvoiceCadence {
	if p == nil {
		return nil
	}
	return p.InvoiceCadence
}

func (p *PricePrice) GetLookupKey() *string {
	if p == nil {
		return nil
	}
	return p.LookupKey
}

func (p *PricePrice) GetMetadata() map[string]string {
	if p == nil {
		return nil
	}
	return p.Metadata
}

func (p *PricePrice) GetMeterID() *string {
	if p == nil {
		return nil
	}
	return p.MeterID
}

func (p *PricePrice) GetMinQuantity() optionalnullable.OptionalNullable[string] {
	if p == nil {
		return nil
	}
	return p.MinQuantity
}

func (p *PricePrice) GetParentPriceID() *string {
	if p == nil {
		return nil
	}
	return p.ParentPriceID
}

func (p *PricePrice) GetPriceUnit() *string {
	if p == nil {
		return nil
	}
	return p.PriceUnit
}

func (p *PricePrice) GetPriceUnitAmount() *string {
	if p == nil {
		return nil
	}
	return p.PriceUnitAmount
}

func (p *PricePrice) GetPriceUnitID() *string {
	if p == nil {
		return nil
	}
	return p.PriceUnitID
}

func (p *PricePrice) GetPriceUnitTiers() []PricePriceTier {
	if p == nil {
		return nil
	}
	return p.PriceUnitTiers
}

func (p *PricePrice) GetPriceUnitType() *PriceUnitType {
	if p == nil {
		return nil
	}
	return p.PriceUnitType
}

func (p *PricePrice) GetSequence() *int64 {
	if p == nil {
		return nil
	}
	return p.Sequence
}

func (p *PricePrice) GetStartDate() *time.Time {
	if p == nil {
		return nil
	}
	return p.StartDate
}

func (p *PricePrice) GetStatus() *Status {
	if p == nil {
		return nil
	}
	return p.Status
}

func (p *PricePrice) GetTenantID() *string {
	if p == nil {
		return nil
	}
	return p.TenantID
}

func (p *PricePrice) GetTierMode() *BillingTier {
	if p == nil {
		return nil
	}
	return p.TierMode
}

func (p *PricePrice) GetTiers() []PricePriceTier {
	if p == nil {
		return nil
	}
	return p.Tiers
}

func (p *PricePrice) GetTransformQuantity() *PriceJSONBTransformQuantity {
	if p == nil {
		return nil
	}
	return p.TransformQuantity
}

func (p *PricePrice) GetTrialPeriodDays() *int64 {
	if p == nil {
		return nil
	}
	return p.TrialPeriodDays
}

func (p *PricePrice) GetType() *PriceType {
	if p == nil {
		return nil
	}
	return p.Type
}

func (p *PricePrice) GetUpdatedAt() *time.Time {
	if p == nil {
		return nil
	}
	return p.UpdatedAt
}

func (p *PricePrice) GetUpdatedBy() *string {
	if p == nil {
		return nil
	}
	return p.UpdatedBy
}
