// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

type PriceEntityType string

const (
	PriceEntityTypePlan         PriceEntityType = "PLAN"
	PriceEntityTypeSubscription PriceEntityType = "SUBSCRIPTION"
	PriceEntityTypeAddon        PriceEntityType = "ADDON"
	PriceEntityTypePrice        PriceEntityType = "PRICE"
	PriceEntityTypeCostsheet    PriceEntityType = "COSTSHEET"
)

func (e PriceEntityType) ToPointer() *PriceEntityType {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *PriceEntityType) IsExact() bool {
	if e != nil {
		switch *e {
		case "PLAN", "SUBSCRIPTION", "ADDON", "PRICE", "COSTSHEET":
			return true
		}
	}
	return false
}
