// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

type ProrationBehavior string

const (
	ProrationBehaviorCreateProrations ProrationBehavior = "create_prorations"
	ProrationBehaviorNone             ProrationBehavior = "none"
)

func (e ProrationBehavior) ToPointer() *ProrationBehavior {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *ProrationBehavior) IsExact() bool {
	if e != nil {
		switch *e {
		case "create_prorations", "none":
			return true
		}
	}
	return false
}
