// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"encoding/json"
	"fmt"
	"github.com/tirdad-billing/go-sdk/v2/internal/utils"
)

type QueryFilterOrder string

const (
	QueryFilterOrderAsc  QueryFilterOrder = "asc"
	QueryFilterOrderDesc QueryFilterOrder = "desc"
)

func (e QueryFilterOrder) ToPointer() *QueryFilterOrder {
	return &e
}
func (e *QueryFilterOrder) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "asc":
		fallthrough
	case "desc":
		*e = QueryFilterOrder(v)
		return nil
	default:
		return fmt.Errorf("invalid value for QueryFilterOrder: %v", v)
	}
}

type QueryFilter struct {
	Expand *string           `json:"expand,omitzero"`
	Limit  *int64            `json:"limit,omitzero"`
	Offset *int64            `json:"offset,omitzero"`
	Order  *QueryFilterOrder `json:"order,omitzero"`
	Sort   *string           `json:"sort,omitzero"`
	Status *Status           `json:"status,omitzero"`
}

func (q QueryFilter) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(q, "", false)
}

func (q *QueryFilter) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &q, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (q *QueryFilter) GetExpand() *string {
	if q == nil {
		return nil
	}
	return q.Expand
}

func (q *QueryFilter) GetLimit() *int64 {
	if q == nil {
		return nil
	}
	return q.Limit
}

func (q *QueryFilter) GetOffset() *int64 {
	if q == nil {
		return nil
	}
	return q.Offset
}

func (q *QueryFilter) GetOrder() *QueryFilterOrder {
	if q == nil {
		return nil
	}
	return q.Order
}

func (q *QueryFilter) GetSort() *string {
	if q == nil {
		return nil
	}
	return q.Sort
}

func (q *QueryFilter) GetStatus() *Status {
	if q == nil {
		return nil
	}
	return q.Status
}
