// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

type RefundDestination string

const (
	RefundDestinationGateway   RefundDestination = "GATEWAY"
	RefundDestinationWallet    RefundDestination = "WALLET"
	RefundDestinationOutOfBand RefundDestination = "OUT_OF_BAND"
)

func (e RefundDestination) ToPointer() *RefundDestination {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *RefundDestination) IsExact() bool {
	if e != nil {
		switch *e {
		case "GATEWAY", "WALLET", "OUT_OF_BAND":
			return true
		}
	}
	return false
}
