// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

type RevenueGranularity string

const (
	RevenueGranularityDay    RevenueGranularity = "day"
	RevenueGranularityPeriod RevenueGranularity = "period"
	RevenueGranularityTotal  RevenueGranularity = "total"
)

func (e RevenueGranularity) ToPointer() *RevenueGranularity {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *RevenueGranularity) IsExact() bool {
	if e != nil {
		switch *e {
		case "day", "period", "total":
			return true
		}
	}
	return false
}
