// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

type Shape string

const (
	ShapeTimeseries Shape = "timeseries"
	ShapeBreakdown  Shape = "breakdown"
)

func (e Shape) ToPointer() *Shape {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *Shape) IsExact() bool {
	if e != nil {
		switch *e {
		case "timeseries", "breakdown":
			return true
		}
	}
	return false
}
