// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/tirdad-billing/go-sdk/v2/internal/utils"
)

type StorageExportConfig struct {
	// Storage bucket name
	Bucket      *string            `json:"bucket,omitzero"`
	Compression *S3CompressionType `json:"compression,omitzero"`
	Encryption  *S3EncryptionType  `json:"encryption,omitzero"`
	// If true, use Flexprice-managed storage credentials instead of user-provided
	IsFlexpriceManaged *bool `json:"is_flexprice_managed,omitzero"`
	// Optional prefix for object keys (e.g., "flexprice-exports/")
	KeyPrefix *string `json:"key_prefix,omitzero"`
	// Cloud region (e.g., "us-west-2"); unused for GCS
	Region *string `json:"region,omitzero"`
}

func (s StorageExportConfig) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *StorageExportConfig) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *StorageExportConfig) GetBucket() *string {
	if s == nil {
		return nil
	}
	return s.Bucket
}

func (s *StorageExportConfig) GetCompression() *S3CompressionType {
	if s == nil {
		return nil
	}
	return s.Compression
}

func (s *StorageExportConfig) GetEncryption() *S3EncryptionType {
	if s == nil {
		return nil
	}
	return s.Encryption
}

func (s *StorageExportConfig) GetIsFlexpriceManaged() *bool {
	if s == nil {
		return nil
	}
	return s.IsFlexpriceManaged
}

func (s *StorageExportConfig) GetKeyPrefix() *string {
	if s == nil {
		return nil
	}
	return s.KeyPrefix
}

func (s *StorageExportConfig) GetRegion() *string {
	if s == nil {
		return nil
	}
	return s.Region
}
