// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/tirdad-billing/go-sdk/v2/internal/utils"
	"time"
)

type SubModifyTrialEndRequest struct {
	Action TrialEndAction `json:"action"`
	// NewTrialEnd is the new trial end date. Required when action is "scheduled_date".
	NewTrialEnd *time.Time `json:"new_trial_end,omitzero"`
}

func (s SubModifyTrialEndRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SubModifyTrialEndRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, []string{"action"}); err != nil {
		return err
	}
	return nil
}

func (s *SubModifyTrialEndRequest) GetAction() TrialEndAction {
	if s == nil {
		return TrialEndAction("")
	}
	return s.Action
}

func (s *SubModifyTrialEndRequest) GetNewTrialEnd() *time.Time {
	if s == nil {
		return nil
	}
	return s.NewTrialEnd
}
