// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/tirdad-billing/go-sdk/v2/internal/utils"
	"time"
)

// SubscriptionChangePreviewResponse - Response showing the financial impact of a subscription plan change
type SubscriptionChangePreviewResponse struct {
	ChangeType  *SubscriptionChangeType `json:"change_type,omitzero"`
	CurrentPlan *PlanSummary            `json:"current_plan,omitzero"`
	// effective_date is when the change would take effect
	EffectiveDate *time.Time `json:"effective_date,omitzero"`
	// metadata from the request
	Metadata           map[string]string `json:"metadata,omitzero"`
	NewBillingCycle    *BillingCycleInfo `json:"new_billing_cycle,omitzero"`
	NextInvoicePreview *InvoicePreview   `json:"next_invoice_preview,omitzero"`
	ProrationDetails   *ProrationDetails `json:"proration_details,omitzero"`
	// subscription_id is the ID of the subscription being changed
	SubscriptionID *string      `json:"subscription_id,omitzero"`
	TargetPlan     *PlanSummary `json:"target_plan,omitzero"`
	// warnings contains any warnings about the change
	Warnings []string `json:"warnings,omitzero"`
}

func (s SubscriptionChangePreviewResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SubscriptionChangePreviewResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *SubscriptionChangePreviewResponse) GetChangeType() *SubscriptionChangeType {
	if s == nil {
		return nil
	}
	return s.ChangeType
}

func (s *SubscriptionChangePreviewResponse) GetCurrentPlan() *PlanSummary {
	if s == nil {
		return nil
	}
	return s.CurrentPlan
}

func (s *SubscriptionChangePreviewResponse) GetEffectiveDate() *time.Time {
	if s == nil {
		return nil
	}
	return s.EffectiveDate
}

func (s *SubscriptionChangePreviewResponse) GetMetadata() map[string]string {
	if s == nil {
		return nil
	}
	return s.Metadata
}

func (s *SubscriptionChangePreviewResponse) GetNewBillingCycle() *BillingCycleInfo {
	if s == nil {
		return nil
	}
	return s.NewBillingCycle
}

func (s *SubscriptionChangePreviewResponse) GetNextInvoicePreview() *InvoicePreview {
	if s == nil {
		return nil
	}
	return s.NextInvoicePreview
}

func (s *SubscriptionChangePreviewResponse) GetProrationDetails() *ProrationDetails {
	if s == nil {
		return nil
	}
	return s.ProrationDetails
}

func (s *SubscriptionChangePreviewResponse) GetSubscriptionID() *string {
	if s == nil {
		return nil
	}
	return s.SubscriptionID
}

func (s *SubscriptionChangePreviewResponse) GetTargetPlan() *PlanSummary {
	if s == nil {
		return nil
	}
	return s.TargetPlan
}

func (s *SubscriptionChangePreviewResponse) GetWarnings() []string {
	if s == nil {
		return nil
	}
	return s.Warnings
}
