// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"encoding/json"
	"fmt"
	"github.com/tirdad-billing/go-sdk/v2/internal/utils"
	"time"
)

type SubscriptionLineItemFilterOrder string

const (
	SubscriptionLineItemFilterOrderAsc  SubscriptionLineItemFilterOrder = "asc"
	SubscriptionLineItemFilterOrderDesc SubscriptionLineItemFilterOrder = "desc"
)

func (e SubscriptionLineItemFilterOrder) ToPointer() *SubscriptionLineItemFilterOrder {
	return &e
}
func (e *SubscriptionLineItemFilterOrder) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "asc":
		fallthrough
	case "desc":
		*e = SubscriptionLineItemFilterOrder(v)
		return nil
	default:
		return fmt.Errorf("invalid value for SubscriptionLineItemFilterOrder: %v", v)
	}
}

type SubscriptionLineItemFilter struct {
	ActiveFilter        *bool                            `default:"true" json:"active_filter"`
	AddonAssociationIds []string                         `json:"addon_association_ids,omitzero"`
	BillingPeriods      []string                         `json:"billing_periods,omitzero"`
	Currencies          []string                         `json:"currencies,omitzero"`
	CurrentPeriodStart  *time.Time                       `json:"current_period_start,omitzero"`
	CustomerIds         []string                         `json:"customer_ids,omitzero"`
	EndTime             *time.Time                       `json:"end_time,omitzero"`
	EntityIds           []string                         `json:"entity_ids,omitzero"`
	EntityType          *SubscriptionLineItemEntityType  `json:"entity_type,omitzero"`
	Expand              *string                          `json:"expand,omitzero"`
	Filters             []FilterCondition                `json:"filters,omitzero"`
	Limit               *int64                           `json:"limit,omitzero"`
	MeterIds            []string                         `json:"meter_ids,omitzero"`
	Offset              *int64                           `json:"offset,omitzero"`
	Order               *SubscriptionLineItemFilterOrder `json:"order,omitzero"`
	PriceIds            []string                         `json:"price_ids,omitzero"`
	Sort                []SortCondition                  `json:"sort,omitzero"`
	StartTime           *time.Time                       `json:"start_time,omitzero"`
	Status              *Status                          `json:"status,omitzero"`
	// Specific filters
	SubscriptionIds []string `json:"subscription_ids,omitzero"`
}

func (s SubscriptionLineItemFilter) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SubscriptionLineItemFilter) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *SubscriptionLineItemFilter) GetActiveFilter() *bool {
	if s == nil {
		return nil
	}
	return s.ActiveFilter
}

func (s *SubscriptionLineItemFilter) GetAddonAssociationIds() []string {
	if s == nil {
		return nil
	}
	return s.AddonAssociationIds
}

func (s *SubscriptionLineItemFilter) GetBillingPeriods() []string {
	if s == nil {
		return nil
	}
	return s.BillingPeriods
}

func (s *SubscriptionLineItemFilter) GetCurrencies() []string {
	if s == nil {
		return nil
	}
	return s.Currencies
}

func (s *SubscriptionLineItemFilter) GetCurrentPeriodStart() *time.Time {
	if s == nil {
		return nil
	}
	return s.CurrentPeriodStart
}

func (s *SubscriptionLineItemFilter) GetCustomerIds() []string {
	if s == nil {
		return nil
	}
	return s.CustomerIds
}

func (s *SubscriptionLineItemFilter) GetEndTime() *time.Time {
	if s == nil {
		return nil
	}
	return s.EndTime
}

func (s *SubscriptionLineItemFilter) GetEntityIds() []string {
	if s == nil {
		return nil
	}
	return s.EntityIds
}

func (s *SubscriptionLineItemFilter) GetEntityType() *SubscriptionLineItemEntityType {
	if s == nil {
		return nil
	}
	return s.EntityType
}

func (s *SubscriptionLineItemFilter) GetExpand() *string {
	if s == nil {
		return nil
	}
	return s.Expand
}

func (s *SubscriptionLineItemFilter) GetFilters() []FilterCondition {
	if s == nil {
		return nil
	}
	return s.Filters
}

func (s *SubscriptionLineItemFilter) GetLimit() *int64 {
	if s == nil {
		return nil
	}
	return s.Limit
}

func (s *SubscriptionLineItemFilter) GetMeterIds() []string {
	if s == nil {
		return nil
	}
	return s.MeterIds
}

func (s *SubscriptionLineItemFilter) GetOffset() *int64 {
	if s == nil {
		return nil
	}
	return s.Offset
}

func (s *SubscriptionLineItemFilter) GetOrder() *SubscriptionLineItemFilterOrder {
	if s == nil {
		return nil
	}
	return s.Order
}

func (s *SubscriptionLineItemFilter) GetPriceIds() []string {
	if s == nil {
		return nil
	}
	return s.PriceIds
}

func (s *SubscriptionLineItemFilter) GetSort() []SortCondition {
	if s == nil {
		return nil
	}
	return s.Sort
}

func (s *SubscriptionLineItemFilter) GetStartTime() *time.Time {
	if s == nil {
		return nil
	}
	return s.StartTime
}

func (s *SubscriptionLineItemFilter) GetStatus() *Status {
	if s == nil {
		return nil
	}
	return s.Status
}

func (s *SubscriptionLineItemFilter) GetSubscriptionIds() []string {
	if s == nil {
		return nil
	}
	return s.SubscriptionIds
}
