// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/tirdad-billing/go-sdk/v2/internal/utils"
	"time"
)

// Configuration - configuration contains type-specific configuration (e.g., target_plan_id for plan changes)
type Configuration struct {
}

func (c Configuration) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *Configuration) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

// ExecutionResult - execution_result contains type-specific execution result
type ExecutionResult struct {
}

func (e ExecutionResult) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *ExecutionResult) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, nil); err != nil {
		return err
	}
	return nil
}

// SubscriptionScheduleResponse - Full details of a subscription schedule
type SubscriptionScheduleResponse struct {
	// can_be_cancelled indicates if the schedule can be cancelled
	CanBeCancelled *bool `json:"can_be_cancelled,omitzero"`
	// cancelled_at is when the schedule was cancelled
	CancelledAt *time.Time `json:"cancelled_at,omitzero"`
	// configuration contains type-specific configuration (e.g., target_plan_id for plan changes)
	Configuration *Configuration `json:"configuration,omitzero"`
	// created_at timestamp
	CreatedAt *time.Time `json:"created_at,omitzero"`
	// days_until_execution is the number of days until execution
	DaysUntilExecution *int64 `json:"days_until_execution,omitzero"`
	// error_message contains the error if execution failed
	ErrorMessage *string `json:"error_message,omitzero"`
	// executed_at is when the schedule was executed
	ExecutedAt *time.Time `json:"executed_at,omitzero"`
	// execution_result contains type-specific execution result
	ExecutionResult *ExecutionResult `json:"execution_result,omitzero"`
	// id of the schedule
	ID *string `json:"id,omitzero"`
	// metadata from the schedule
	Metadata     map[string]string               `json:"metadata,omitzero"`
	ScheduleType *SubscriptionScheduleChangeType `json:"schedule_type,omitzero"`
	// scheduled_at is when the schedule will execute
	ScheduledAt *time.Time      `json:"scheduled_at,omitzero"`
	Status      *ScheduleStatus `json:"status,omitzero"`
	// subscription_id is the ID of the subscription
	SubscriptionID *string `json:"subscription_id,omitzero"`
	// updated_at timestamp
	UpdatedAt *time.Time `json:"updated_at,omitzero"`
}

func (s SubscriptionScheduleResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SubscriptionScheduleResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *SubscriptionScheduleResponse) GetCanBeCancelled() *bool {
	if s == nil {
		return nil
	}
	return s.CanBeCancelled
}

func (s *SubscriptionScheduleResponse) GetCancelledAt() *time.Time {
	if s == nil {
		return nil
	}
	return s.CancelledAt
}

func (s *SubscriptionScheduleResponse) GetConfiguration() *Configuration {
	if s == nil {
		return nil
	}
	return s.Configuration
}

func (s *SubscriptionScheduleResponse) GetCreatedAt() *time.Time {
	if s == nil {
		return nil
	}
	return s.CreatedAt
}

func (s *SubscriptionScheduleResponse) GetDaysUntilExecution() *int64 {
	if s == nil {
		return nil
	}
	return s.DaysUntilExecution
}

func (s *SubscriptionScheduleResponse) GetErrorMessage() *string {
	if s == nil {
		return nil
	}
	return s.ErrorMessage
}

func (s *SubscriptionScheduleResponse) GetExecutedAt() *time.Time {
	if s == nil {
		return nil
	}
	return s.ExecutedAt
}

func (s *SubscriptionScheduleResponse) GetExecutionResult() *ExecutionResult {
	if s == nil {
		return nil
	}
	return s.ExecutionResult
}

func (s *SubscriptionScheduleResponse) GetID() *string {
	if s == nil {
		return nil
	}
	return s.ID
}

func (s *SubscriptionScheduleResponse) GetMetadata() map[string]string {
	if s == nil {
		return nil
	}
	return s.Metadata
}

func (s *SubscriptionScheduleResponse) GetScheduleType() *SubscriptionScheduleChangeType {
	if s == nil {
		return nil
	}
	return s.ScheduleType
}

func (s *SubscriptionScheduleResponse) GetScheduledAt() *time.Time {
	if s == nil {
		return nil
	}
	return s.ScheduledAt
}

func (s *SubscriptionScheduleResponse) GetStatus() *ScheduleStatus {
	if s == nil {
		return nil
	}
	return s.Status
}

func (s *SubscriptionScheduleResponse) GetSubscriptionID() *string {
	if s == nil {
		return nil
	}
	return s.SubscriptionID
}

func (s *SubscriptionScheduleResponse) GetUpdatedAt() *time.Time {
	if s == nil {
		return nil
	}
	return s.UpdatedAt
}
