// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/tirdad-billing/go-sdk/v2/internal/utils"
	"time"
)

type SubscriptionPhaseCreateRequest struct {
	// Deprecated: use SubscriptionCoupons instead.
	Coupons []string   `json:"coupons,omitzero"`
	EndDate *time.Time `json:"end_date,omitzero"`
	// Deprecated: use SubscriptionCoupons instead.
	LineItemCoupons map[string][]string `json:"line_item_coupons,omitzero"`
	// LineItems are extra line items to add during this phase, primarily one-time charges.
	// Each item's start_date defaults to the phase's start_date when not provided.
	LineItems []CreateSubscriptionLineItemRequest `json:"line_items,omitzero"`
	Metadata  map[string]string                   `json:"metadata,omitzero"`
	// OverrideLineItems allows customizing specific prices for this phase
	// If not provided, phase will use the same line items as the subscription (plan prices)
	OverrideLineItems []OverrideLineItemRequest `json:"override_line_items,omitzero"`
	StartDate         time.Time                 `json:"start_date"`
	// SubscriptionCoupons is the preferred way to attach coupons to this phase.
	SubscriptionCoupons []SubscriptionCouponInput `json:"subscription_coupons,omitzero"`
}

func (s SubscriptionPhaseCreateRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SubscriptionPhaseCreateRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, []string{"start_date"}); err != nil {
		return err
	}
	return nil
}

func (s *SubscriptionPhaseCreateRequest) GetCoupons() []string {
	if s == nil {
		return nil
	}
	return s.Coupons
}

func (s *SubscriptionPhaseCreateRequest) GetEndDate() *time.Time {
	if s == nil {
		return nil
	}
	return s.EndDate
}

func (s *SubscriptionPhaseCreateRequest) GetLineItemCoupons() map[string][]string {
	if s == nil {
		return nil
	}
	return s.LineItemCoupons
}

func (s *SubscriptionPhaseCreateRequest) GetLineItems() []CreateSubscriptionLineItemRequest {
	if s == nil {
		return nil
	}
	return s.LineItems
}

func (s *SubscriptionPhaseCreateRequest) GetMetadata() map[string]string {
	if s == nil {
		return nil
	}
	return s.Metadata
}

func (s *SubscriptionPhaseCreateRequest) GetOverrideLineItems() []OverrideLineItemRequest {
	if s == nil {
		return nil
	}
	return s.OverrideLineItems
}

func (s *SubscriptionPhaseCreateRequest) GetStartDate() time.Time {
	if s == nil {
		return time.Time{}
	}
	return s.StartDate
}

func (s *SubscriptionPhaseCreateRequest) GetSubscriptionCoupons() []SubscriptionCouponInput {
	if s == nil {
		return nil
	}
	return s.SubscriptionCoupons
}
