// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/tirdad-billing/go-sdk/v2/internal/utils"
	"time"
)

type TaxRateResponse struct {
	Code            *string           `json:"code,omitzero"`
	CreatedAt       *time.Time        `json:"created_at,omitzero"`
	CreatedBy       *string           `json:"created_by,omitzero"`
	Description     *string           `json:"description,omitzero"`
	EnvironmentID   *string           `json:"environment_id,omitzero"`
	FixedValue      *string           `json:"fixed_value,omitzero"`
	ID              *string           `json:"id,omitzero"`
	Metadata        map[string]string `json:"metadata,omitzero"`
	Name            *string           `json:"name,omitzero"`
	PercentageValue *string           `json:"percentage_value,omitzero"`
	Scope           *TaxRateScope     `json:"scope,omitzero"`
	Status          *Status           `json:"status,omitzero"`
	TaxRateStatus   *TaxRateStatus    `json:"tax_rate_status,omitzero"`
	TaxRateType     *TaxRateType      `json:"tax_rate_type,omitzero"`
	TenantID        *string           `json:"tenant_id,omitzero"`
	UpdatedAt       *time.Time        `json:"updated_at,omitzero"`
	UpdatedBy       *string           `json:"updated_by,omitzero"`
}

func (t TaxRateResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *TaxRateResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (t *TaxRateResponse) GetCode() *string {
	if t == nil {
		return nil
	}
	return t.Code
}

func (t *TaxRateResponse) GetCreatedAt() *time.Time {
	if t == nil {
		return nil
	}
	return t.CreatedAt
}

func (t *TaxRateResponse) GetCreatedBy() *string {
	if t == nil {
		return nil
	}
	return t.CreatedBy
}

func (t *TaxRateResponse) GetDescription() *string {
	if t == nil {
		return nil
	}
	return t.Description
}

func (t *TaxRateResponse) GetEnvironmentID() *string {
	if t == nil {
		return nil
	}
	return t.EnvironmentID
}

func (t *TaxRateResponse) GetFixedValue() *string {
	if t == nil {
		return nil
	}
	return t.FixedValue
}

func (t *TaxRateResponse) GetID() *string {
	if t == nil {
		return nil
	}
	return t.ID
}

func (t *TaxRateResponse) GetMetadata() map[string]string {
	if t == nil {
		return nil
	}
	return t.Metadata
}

func (t *TaxRateResponse) GetName() *string {
	if t == nil {
		return nil
	}
	return t.Name
}

func (t *TaxRateResponse) GetPercentageValue() *string {
	if t == nil {
		return nil
	}
	return t.PercentageValue
}

func (t *TaxRateResponse) GetScope() *TaxRateScope {
	if t == nil {
		return nil
	}
	return t.Scope
}

func (t *TaxRateResponse) GetStatus() *Status {
	if t == nil {
		return nil
	}
	return t.Status
}

func (t *TaxRateResponse) GetTaxRateStatus() *TaxRateStatus {
	if t == nil {
		return nil
	}
	return t.TaxRateStatus
}

func (t *TaxRateResponse) GetTaxRateType() *TaxRateType {
	if t == nil {
		return nil
	}
	return t.TaxRateType
}

func (t *TaxRateResponse) GetTenantID() *string {
	if t == nil {
		return nil
	}
	return t.TenantID
}

func (t *TaxRateResponse) GetUpdatedAt() *time.Time {
	if t == nil {
		return nil
	}
	return t.UpdatedAt
}

func (t *TaxRateResponse) GetUpdatedBy() *string {
	if t == nil {
		return nil
	}
	return t.UpdatedBy
}
