// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/tirdad-billing/go-sdk/v2/internal/utils"
	"time"
)

type UpdateCreditGrantRequest struct {
	EndDate  *time.Time        `json:"end_date,omitzero"`
	Metadata map[string]string `json:"metadata,omitzero"`
	Name     *string           `json:"name,omitzero"`
}

func (u UpdateCreditGrantRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdateCreditGrantRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UpdateCreditGrantRequest) GetEndDate() *time.Time {
	if u == nil {
		return nil
	}
	return u.EndDate
}

func (u *UpdateCreditGrantRequest) GetMetadata() map[string]string {
	if u == nil {
		return nil
	}
	return u.Metadata
}

func (u *UpdateCreditGrantRequest) GetName() *string {
	if u == nil {
		return nil
	}
	return u.Name
}
