// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/tirdad-billing/go-sdk/v2/internal/utils"
	"time"
)

type UpdateLineItemRequest struct {
	Amount      *string    `json:"amount,omitzero"`
	Description *string    `json:"description,omitzero"`
	DisplayName *string    `json:"display_name,omitzero"`
	PeriodEnd   *time.Time `json:"period_end,omitzero"`
	PeriodStart *time.Time `json:"period_start,omitzero"`
	Quantity    *string    `json:"quantity,omitzero"`
}

func (u UpdateLineItemRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdateLineItemRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UpdateLineItemRequest) GetAmount() *string {
	if u == nil {
		return nil
	}
	return u.Amount
}

func (u *UpdateLineItemRequest) GetDescription() *string {
	if u == nil {
		return nil
	}
	return u.Description
}

func (u *UpdateLineItemRequest) GetDisplayName() *string {
	if u == nil {
		return nil
	}
	return u.DisplayName
}

func (u *UpdateLineItemRequest) GetPeriodEnd() *time.Time {
	if u == nil {
		return nil
	}
	return u.PeriodEnd
}

func (u *UpdateLineItemRequest) GetPeriodStart() *time.Time {
	if u == nil {
		return nil
	}
	return u.PeriodStart
}

func (u *UpdateLineItemRequest) GetQuantity() *string {
	if u == nil {
		return nil
	}
	return u.Quantity
}
