// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/tirdad-billing/go-sdk/v2/internal/utils"
)

type UpdatePaymentStatusRequest struct {
	// amount is the optional payment amount to record
	Amount        *string       `json:"amount,omitzero"`
	PaymentStatus PaymentStatus `json:"payment_status"`
}

func (u UpdatePaymentStatusRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdatePaymentStatusRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, []string{"payment_status"}); err != nil {
		return err
	}
	return nil
}

func (u *UpdatePaymentStatusRequest) GetAmount() *string {
	if u == nil {
		return nil
	}
	return u.Amount
}

func (u *UpdatePaymentStatusRequest) GetPaymentStatus() PaymentStatus {
	if u == nil {
		return PaymentStatus("")
	}
	return u.PaymentStatus
}
