// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/tirdad-billing/go-sdk/v2/internal/utils"
)

type UpdateAddonRequest struct {
	Description *string        `json:"description,omitzero"`
	Metadata    map[string]any `json:"metadata,omitzero"`
	Name        *string        `json:"name,omitzero"`
}

func (u UpdateAddonRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdateAddonRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UpdateAddonRequest) GetDescription() *string {
	if u == nil {
		return nil
	}
	return u.Description
}

func (u *UpdateAddonRequest) GetMetadata() map[string]any {
	if u == nil {
		return nil
	}
	return u.Metadata
}

func (u *UpdateAddonRequest) GetName() *string {
	if u == nil {
		return nil
	}
	return u.Name
}
