// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/tirdad-billing/go-sdk/v2/internal/utils"
)

type UpdateAlertSettingsRequest struct {
	Config AlertSettings `json:"config"`
}

func (u UpdateAlertSettingsRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdateAlertSettingsRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, []string{"config"}); err != nil {
		return err
	}
	return nil
}

func (u *UpdateAlertSettingsRequest) GetConfig() AlertSettings {
	if u == nil {
		return AlertSettings{}
	}
	return u.Config
}
