// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/tirdad-billing/go-sdk/v2/internal/utils"
)

type UpdateFeatureRequest struct {
	AlertSettings *AlertSettings `json:"alert_settings,omitzero"`
	Description   *string        `json:"description,omitzero"`
	Filters       []MeterFilter  `json:"filters,omitzero"`
	// GroupID is the id of the group to assign the feature to. Pass empty string to clear.
	GroupID       *string           `json:"group_id,omitzero"`
	Metadata      map[string]string `json:"metadata,omitzero"`
	Name          *string           `json:"name,omitzero"`
	ReportingUnit *ReportingUnit    `json:"reporting_unit,omitzero"`
	UnitPlural    *string           `json:"unit_plural,omitzero"`
	UnitSingular  *string           `json:"unit_singular,omitzero"`
}

func (u UpdateFeatureRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdateFeatureRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UpdateFeatureRequest) GetAlertSettings() *AlertSettings {
	if u == nil {
		return nil
	}
	return u.AlertSettings
}

func (u *UpdateFeatureRequest) GetDescription() *string {
	if u == nil {
		return nil
	}
	return u.Description
}

func (u *UpdateFeatureRequest) GetFilters() []MeterFilter {
	if u == nil {
		return nil
	}
	return u.Filters
}

func (u *UpdateFeatureRequest) GetGroupID() *string {
	if u == nil {
		return nil
	}
	return u.GroupID
}

func (u *UpdateFeatureRequest) GetMetadata() map[string]string {
	if u == nil {
		return nil
	}
	return u.Metadata
}

func (u *UpdateFeatureRequest) GetName() *string {
	if u == nil {
		return nil
	}
	return u.Name
}

func (u *UpdateFeatureRequest) GetReportingUnit() *ReportingUnit {
	if u == nil {
		return nil
	}
	return u.ReportingUnit
}

func (u *UpdateFeatureRequest) GetUnitPlural() *string {
	if u == nil {
		return nil
	}
	return u.UnitPlural
}

func (u *UpdateFeatureRequest) GetUnitSingular() *string {
	if u == nil {
		return nil
	}
	return u.UnitSingular
}
