// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/tirdad-billing/go-sdk/v2/internal/utils"
)

// UpdateCustomerRequest - Request object for updating an existing customer. All fields are optional - only provided fields will be updated
type UpdateCustomerRequest struct {
	// address_city is the updated city name with maximum 100 characters
	AddressCity *string `json:"address_city,omitzero"`
	// address_country is the updated two-letter ISO 3166-1 alpha-2 country code
	AddressCountry *string `json:"address_country,omitzero"`
	// address_line1 is the updated primary address line with maximum 255 characters
	AddressLine1 *string `json:"address_line1,omitzero"`
	// address_line2 is the updated secondary address line with maximum 255 characters
	AddressLine2 *string `json:"address_line2,omitzero"`
	// address_postal_code is the updated postal code with maximum 20 characters
	AddressPostalCode *string `json:"address_postal_code,omitzero"`
	// address_state is the updated state, province, or region name with maximum 100 characters
	AddressState *string `json:"address_state,omitzero"`
	// email is the updated email address and must be a valid email format if provided
	Email *string `json:"email,omitzero"`
	// external_id is the updated external identifier for the customer
	ExternalID *string `json:"external_id,omitzero"`
	// integration_entity_mapping contains provider integration mappings for this customer
	IntegrationEntityMapping []CreateEntityIntegrationMappingRequest `json:"integration_entity_mapping,omitzero"`
	// metadata contains updated key-value pairs that will replace existing metadata
	Metadata map[string]string `json:"metadata,omitzero"`
	// name is the updated name or company name for the customer
	Name *string `json:"name,omitzero"`
}

func (u UpdateCustomerRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdateCustomerRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UpdateCustomerRequest) GetAddressCity() *string {
	if u == nil {
		return nil
	}
	return u.AddressCity
}

func (u *UpdateCustomerRequest) GetAddressCountry() *string {
	if u == nil {
		return nil
	}
	return u.AddressCountry
}

func (u *UpdateCustomerRequest) GetAddressLine1() *string {
	if u == nil {
		return nil
	}
	return u.AddressLine1
}

func (u *UpdateCustomerRequest) GetAddressLine2() *string {
	if u == nil {
		return nil
	}
	return u.AddressLine2
}

func (u *UpdateCustomerRequest) GetAddressPostalCode() *string {
	if u == nil {
		return nil
	}
	return u.AddressPostalCode
}

func (u *UpdateCustomerRequest) GetAddressState() *string {
	if u == nil {
		return nil
	}
	return u.AddressState
}

func (u *UpdateCustomerRequest) GetEmail() *string {
	if u == nil {
		return nil
	}
	return u.Email
}

func (u *UpdateCustomerRequest) GetExternalID() *string {
	if u == nil {
		return nil
	}
	return u.ExternalID
}

func (u *UpdateCustomerRequest) GetIntegrationEntityMapping() []CreateEntityIntegrationMappingRequest {
	if u == nil {
		return nil
	}
	return u.IntegrationEntityMapping
}

func (u *UpdateCustomerRequest) GetMetadata() map[string]string {
	if u == nil {
		return nil
	}
	return u.Metadata
}

func (u *UpdateCustomerRequest) GetName() *string {
	if u == nil {
		return nil
	}
	return u.Name
}
