// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/tirdad-billing/go-sdk/v2/internal/utils"
	"time"
)

type UpdateFXRateRequest struct {
	EndDate   *time.Time        `json:"end_date,omitzero"`
	Metadata  map[string]string `json:"metadata,omitzero"`
	Rate      *string           `json:"rate,omitzero"`
	StartDate *time.Time        `json:"start_date,omitzero"`
}

func (u UpdateFXRateRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdateFXRateRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UpdateFXRateRequest) GetEndDate() *time.Time {
	if u == nil {
		return nil
	}
	return u.EndDate
}

func (u *UpdateFXRateRequest) GetMetadata() map[string]string {
	if u == nil {
		return nil
	}
	return u.Metadata
}

func (u *UpdateFXRateRequest) GetRate() *string {
	if u == nil {
		return nil
	}
	return u.Rate
}

func (u *UpdateFXRateRequest) GetStartDate() *time.Time {
	if u == nil {
		return nil
	}
	return u.StartDate
}
