// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/tirdad-billing/go-sdk/v2/internal/utils"
)

type UpdateTenantAddress struct {
	AddressCity       *string `json:"address_city,omitzero"`
	AddressCountry    *string `json:"address_country,omitzero"`
	AddressLine1      *string `json:"address_line1,omitzero"`
	AddressLine2      *string `json:"address_line2,omitzero"`
	AddressPostalCode *string `json:"address_postal_code,omitzero"`
	AddressState      *string `json:"address_state,omitzero"`
}

func (u UpdateTenantAddress) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdateTenantAddress) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UpdateTenantAddress) GetAddressCity() *string {
	if u == nil {
		return nil
	}
	return u.AddressCity
}

func (u *UpdateTenantAddress) GetAddressCountry() *string {
	if u == nil {
		return nil
	}
	return u.AddressCountry
}

func (u *UpdateTenantAddress) GetAddressLine1() *string {
	if u == nil {
		return nil
	}
	return u.AddressLine1
}

func (u *UpdateTenantAddress) GetAddressLine2() *string {
	if u == nil {
		return nil
	}
	return u.AddressLine2
}

func (u *UpdateTenantAddress) GetAddressPostalCode() *string {
	if u == nil {
		return nil
	}
	return u.AddressPostalCode
}

func (u *UpdateTenantAddress) GetAddressState() *string {
	if u == nil {
		return nil
	}
	return u.AddressState
}
