// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"encoding/json"
	"fmt"
	"github.com/tirdad-billing/go-sdk/v2/internal/utils"
)

type WalletFilterOrder string

const (
	WalletFilterOrderAsc  WalletFilterOrder = "asc"
	WalletFilterOrderDesc WalletFilterOrder = "desc"
)

func (e WalletFilterOrder) ToPointer() *WalletFilterOrder {
	return &e
}
func (e *WalletFilterOrder) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "asc":
		fallthrough
	case "desc":
		*e = WalletFilterOrder(v)
		return nil
	default:
		return fmt.Errorf("invalid value for WalletFilterOrder: %v", v)
	}
}

type WalletFilter struct {
	AlertEnabled *bool              `json:"alert_enabled,omitzero"`
	Expand       *string            `json:"expand,omitzero"`
	Limit        *int64             `json:"limit,omitzero"`
	Offset       *int64             `json:"offset,omitzero"`
	Order        *WalletFilterOrder `json:"order,omitzero"`
	Sort         *string            `json:"sort,omitzero"`
	Status       *WalletStatus      `json:"status,omitzero"`
	WalletIds    []string           `json:"wallet_ids,omitzero"`
}

func (w WalletFilter) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(w, "", false)
}

func (w *WalletFilter) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &w, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (w *WalletFilter) GetAlertEnabled() *bool {
	if w == nil {
		return nil
	}
	return w.AlertEnabled
}

func (w *WalletFilter) GetExpand() *string {
	if w == nil {
		return nil
	}
	return w.Expand
}

func (w *WalletFilter) GetLimit() *int64 {
	if w == nil {
		return nil
	}
	return w.Limit
}

func (w *WalletFilter) GetOffset() *int64 {
	if w == nil {
		return nil
	}
	return w.Offset
}

func (w *WalletFilter) GetOrder() *WalletFilterOrder {
	if w == nil {
		return nil
	}
	return w.Order
}

func (w *WalletFilter) GetSort() *string {
	if w == nil {
		return nil
	}
	return w.Sort
}

func (w *WalletFilter) GetStatus() *WalletStatus {
	if w == nil {
		return nil
	}
	return w.Status
}

func (w *WalletFilter) GetWalletIds() []string {
	if w == nil {
		return nil
	}
	return w.WalletIds
}
