// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/tirdad-billing/go-sdk/v2/internal/utils"
)

type WebhookDtoSubscriptionWebhookPayload struct {
	EventType    *WebhookEventName     `json:"event_type,omitzero"`
	Subscription *SubscriptionResponse `json:"subscription,omitzero"`
}

func (w WebhookDtoSubscriptionWebhookPayload) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(w, "", false)
}

func (w *WebhookDtoSubscriptionWebhookPayload) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &w, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (w *WebhookDtoSubscriptionWebhookPayload) GetEventType() *WebhookEventName {
	if w == nil {
		return nil
	}
	return w.EventType
}

func (w *WebhookDtoSubscriptionWebhookPayload) GetSubscription() *SubscriptionResponse {
	if w == nil {
		return nil
	}
	return w.Subscription
}
