// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/tirdad-billing/go-sdk/v2/internal/utils"
	"time"
)

type WebhookDtoCheckoutSession struct {
	Action            *CheckoutAction          `json:"action,omitzero"`
	CancelledAt       *time.Time               `json:"cancelled_at,omitzero"`
	CheckoutInvoiceID *string                  `json:"checkout_invoice_id,omitzero"`
	CheckoutPaymentID *string                  `json:"checkout_payment_id,omitzero"`
	CheckoutStatus    *CheckoutStatus          `json:"checkout_status,omitzero"`
	CompletedAt       *time.Time               `json:"completed_at,omitzero"`
	CustomerID        *string                  `json:"customer_id,omitzero"`
	ExpiresAt         *time.Time               `json:"expires_at,omitzero"`
	FailureReason     *string                  `json:"failure_reason,omitzero"`
	ID                *string                  `json:"id,omitzero"`
	PaymentAction     *PaymentAction           `json:"payment_action,omitzero"`
	PaymentProvider   *CheckoutPaymentProvider `json:"payment_provider,omitzero"`
}

func (w WebhookDtoCheckoutSession) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(w, "", false)
}

func (w *WebhookDtoCheckoutSession) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &w, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (w *WebhookDtoCheckoutSession) GetAction() *CheckoutAction {
	if w == nil {
		return nil
	}
	return w.Action
}

func (w *WebhookDtoCheckoutSession) GetCancelledAt() *time.Time {
	if w == nil {
		return nil
	}
	return w.CancelledAt
}

func (w *WebhookDtoCheckoutSession) GetCheckoutInvoiceID() *string {
	if w == nil {
		return nil
	}
	return w.CheckoutInvoiceID
}

func (w *WebhookDtoCheckoutSession) GetCheckoutPaymentID() *string {
	if w == nil {
		return nil
	}
	return w.CheckoutPaymentID
}

func (w *WebhookDtoCheckoutSession) GetCheckoutStatus() *CheckoutStatus {
	if w == nil {
		return nil
	}
	return w.CheckoutStatus
}

func (w *WebhookDtoCheckoutSession) GetCompletedAt() *time.Time {
	if w == nil {
		return nil
	}
	return w.CompletedAt
}

func (w *WebhookDtoCheckoutSession) GetCustomerID() *string {
	if w == nil {
		return nil
	}
	return w.CustomerID
}

func (w *WebhookDtoCheckoutSession) GetExpiresAt() *time.Time {
	if w == nil {
		return nil
	}
	return w.ExpiresAt
}

func (w *WebhookDtoCheckoutSession) GetFailureReason() *string {
	if w == nil {
		return nil
	}
	return w.FailureReason
}

func (w *WebhookDtoCheckoutSession) GetID() *string {
	if w == nil {
		return nil
	}
	return w.ID
}

func (w *WebhookDtoCheckoutSession) GetPaymentAction() *PaymentAction {
	if w == nil {
		return nil
	}
	return w.PaymentAction
}

func (w *WebhookDtoCheckoutSession) GetPaymentProvider() *CheckoutPaymentProvider {
	if w == nil {
		return nil
	}
	return w.PaymentProvider
}
