// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/tirdad-billing/go-sdk/v2/internal/utils"
	"time"
)

type WebhookDtoPayment struct {
	Amount            *string                 `json:"amount,omitzero"`
	Currency          *string                 `json:"currency,omitzero"`
	DestinationID     *string                 `json:"destination_id,omitzero"`
	DestinationType   *PaymentDestinationType `json:"destination_type,omitzero"`
	ErrorMessage      *string                 `json:"error_message,omitzero"`
	FailedAt          *time.Time              `json:"failed_at,omitzero"`
	ID                *string                 `json:"id,omitzero"`
	InvoiceNumber     *string                 `json:"invoice_number,omitzero"`
	PaymentGateway    *string                 `json:"payment_gateway,omitzero"`
	PaymentMethodType *PaymentMethodType      `json:"payment_method_type,omitzero"`
	PaymentStatus     *PaymentStatus          `json:"payment_status,omitzero"`
	RefundedAt        *time.Time              `json:"refunded_at,omitzero"`
	SucceededAt       *time.Time              `json:"succeeded_at,omitzero"`
	VoidedAt          *time.Time              `json:"voided_at,omitzero"`
}

func (w WebhookDtoPayment) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(w, "", false)
}

func (w *WebhookDtoPayment) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &w, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (w *WebhookDtoPayment) GetAmount() *string {
	if w == nil {
		return nil
	}
	return w.Amount
}

func (w *WebhookDtoPayment) GetCurrency() *string {
	if w == nil {
		return nil
	}
	return w.Currency
}

func (w *WebhookDtoPayment) GetDestinationID() *string {
	if w == nil {
		return nil
	}
	return w.DestinationID
}

func (w *WebhookDtoPayment) GetDestinationType() *PaymentDestinationType {
	if w == nil {
		return nil
	}
	return w.DestinationType
}

func (w *WebhookDtoPayment) GetErrorMessage() *string {
	if w == nil {
		return nil
	}
	return w.ErrorMessage
}

func (w *WebhookDtoPayment) GetFailedAt() *time.Time {
	if w == nil {
		return nil
	}
	return w.FailedAt
}

func (w *WebhookDtoPayment) GetID() *string {
	if w == nil {
		return nil
	}
	return w.ID
}

func (w *WebhookDtoPayment) GetInvoiceNumber() *string {
	if w == nil {
		return nil
	}
	return w.InvoiceNumber
}

func (w *WebhookDtoPayment) GetPaymentGateway() *string {
	if w == nil {
		return nil
	}
	return w.PaymentGateway
}

func (w *WebhookDtoPayment) GetPaymentMethodType() *PaymentMethodType {
	if w == nil {
		return nil
	}
	return w.PaymentMethodType
}

func (w *WebhookDtoPayment) GetPaymentStatus() *PaymentStatus {
	if w == nil {
		return nil
	}
	return w.PaymentStatus
}

func (w *WebhookDtoPayment) GetRefundedAt() *time.Time {
	if w == nil {
		return nil
	}
	return w.RefundedAt
}

func (w *WebhookDtoPayment) GetSucceededAt() *time.Time {
	if w == nil {
		return nil
	}
	return w.SucceededAt
}

func (w *WebhookDtoPayment) GetVoidedAt() *time.Time {
	if w == nil {
		return nil
	}
	return w.VoidedAt
}
