// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/tirdad-billing/go-sdk/v2/internal/utils"
	"time"
)

type WebhookDtoSubscription struct {
	BillingCadence       *BillingCadence     `json:"billing_cadence,omitzero"`
	BillingPeriod        *BillingPeriod      `json:"billing_period,omitzero"`
	BillingPeriodCount   *int64              `json:"billing_period_count,omitzero"`
	CancelAt             *time.Time          `json:"cancel_at,omitzero"`
	CancelAtPeriodEnd    *bool               `json:"cancel_at_period_end,omitzero"`
	CancelledAt          *time.Time          `json:"cancelled_at,omitzero"`
	Currency             *string             `json:"currency,omitzero"`
	CurrentPeriodEnd     *time.Time          `json:"current_period_end,omitzero"`
	CurrentPeriodStart   *time.Time          `json:"current_period_start,omitzero"`
	Customer             *WebhookDtoCustomer `json:"customer,omitzero"`
	CustomerID           *string             `json:"customer_id,omitzero"`
	EndDate              *time.Time          `json:"end_date,omitzero"`
	ID                   *string             `json:"id,omitzero"`
	LookupKey            *string             `json:"lookup_key,omitzero"`
	Metadata             map[string]string   `json:"metadata,omitzero"`
	ParentSubscriptionID *string             `json:"parent_subscription_id,omitzero"`
	PauseStatus          *PauseStatus        `json:"pause_status,omitzero"`
	PlanID               *string             `json:"plan_id,omitzero"`
	StartDate            *time.Time          `json:"start_date,omitzero"`
	SubscriptionStatus   *SubscriptionStatus `json:"subscription_status,omitzero"`
	SubscriptionType     *SubscriptionType   `json:"subscription_type,omitzero"`
	TrialEnd             *time.Time          `json:"trial_end,omitzero"`
	TrialStart           *time.Time          `json:"trial_start,omitzero"`
}

func (w WebhookDtoSubscription) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(w, "", false)
}

func (w *WebhookDtoSubscription) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &w, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (w *WebhookDtoSubscription) GetBillingCadence() *BillingCadence {
	if w == nil {
		return nil
	}
	return w.BillingCadence
}

func (w *WebhookDtoSubscription) GetBillingPeriod() *BillingPeriod {
	if w == nil {
		return nil
	}
	return w.BillingPeriod
}

func (w *WebhookDtoSubscription) GetBillingPeriodCount() *int64 {
	if w == nil {
		return nil
	}
	return w.BillingPeriodCount
}

func (w *WebhookDtoSubscription) GetCancelAt() *time.Time {
	if w == nil {
		return nil
	}
	return w.CancelAt
}

func (w *WebhookDtoSubscription) GetCancelAtPeriodEnd() *bool {
	if w == nil {
		return nil
	}
	return w.CancelAtPeriodEnd
}

func (w *WebhookDtoSubscription) GetCancelledAt() *time.Time {
	if w == nil {
		return nil
	}
	return w.CancelledAt
}

func (w *WebhookDtoSubscription) GetCurrency() *string {
	if w == nil {
		return nil
	}
	return w.Currency
}

func (w *WebhookDtoSubscription) GetCurrentPeriodEnd() *time.Time {
	if w == nil {
		return nil
	}
	return w.CurrentPeriodEnd
}

func (w *WebhookDtoSubscription) GetCurrentPeriodStart() *time.Time {
	if w == nil {
		return nil
	}
	return w.CurrentPeriodStart
}

func (w *WebhookDtoSubscription) GetCustomer() *WebhookDtoCustomer {
	if w == nil {
		return nil
	}
	return w.Customer
}

func (w *WebhookDtoSubscription) GetCustomerID() *string {
	if w == nil {
		return nil
	}
	return w.CustomerID
}

func (w *WebhookDtoSubscription) GetEndDate() *time.Time {
	if w == nil {
		return nil
	}
	return w.EndDate
}

func (w *WebhookDtoSubscription) GetID() *string {
	if w == nil {
		return nil
	}
	return w.ID
}

func (w *WebhookDtoSubscription) GetLookupKey() *string {
	if w == nil {
		return nil
	}
	return w.LookupKey
}

func (w *WebhookDtoSubscription) GetMetadata() map[string]string {
	if w == nil {
		return nil
	}
	return w.Metadata
}

func (w *WebhookDtoSubscription) GetParentSubscriptionID() *string {
	if w == nil {
		return nil
	}
	return w.ParentSubscriptionID
}

func (w *WebhookDtoSubscription) GetPauseStatus() *PauseStatus {
	if w == nil {
		return nil
	}
	return w.PauseStatus
}

func (w *WebhookDtoSubscription) GetPlanID() *string {
	if w == nil {
		return nil
	}
	return w.PlanID
}

func (w *WebhookDtoSubscription) GetStartDate() *time.Time {
	if w == nil {
		return nil
	}
	return w.StartDate
}

func (w *WebhookDtoSubscription) GetSubscriptionStatus() *SubscriptionStatus {
	if w == nil {
		return nil
	}
	return w.SubscriptionStatus
}

func (w *WebhookDtoSubscription) GetSubscriptionType() *SubscriptionType {
	if w == nil {
		return nil
	}
	return w.SubscriptionType
}

func (w *WebhookDtoSubscription) GetTrialEnd() *time.Time {
	if w == nil {
		return nil
	}
	return w.TrialEnd
}

func (w *WebhookDtoSubscription) GetTrialStart() *time.Time {
	if w == nil {
		return nil
	}
	return w.TrialStart
}
