// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

type WebhookEventName string

const (
	WebhookEventNameSubscriptionCreated           WebhookEventName = "subscription.created"
	WebhookEventNameSubscriptionDraftCreated      WebhookEventName = "subscription.draft.created"
	WebhookEventNameSubscriptionActivated         WebhookEventName = "subscription.activated"
	WebhookEventNameSubscriptionUpdated           WebhookEventName = "subscription.updated"
	WebhookEventNameSubscriptionPaused            WebhookEventName = "subscription.paused"
	WebhookEventNameSubscriptionCancelled         WebhookEventName = "subscription.cancelled"
	WebhookEventNameSubscriptionResumed           WebhookEventName = "subscription.resumed"
	WebhookEventNameSubscriptionPhaseCreated      WebhookEventName = "subscription.phase.created"
	WebhookEventNameSubscriptionPhaseUpdated      WebhookEventName = "subscription.phase.updated"
	WebhookEventNameSubscriptionPhaseDeleted      WebhookEventName = "subscription.phase.deleted"
	WebhookEventNameFeatureCreated                WebhookEventName = "feature.created"
	WebhookEventNameFeatureUpdated                WebhookEventName = "feature.updated"
	WebhookEventNameFeatureDeleted                WebhookEventName = "feature.deleted"
	WebhookEventNameFeatureWalletBalanceAlert     WebhookEventName = "feature.wallet_balance.alert"
	WebhookEventNameEntitlementCreated            WebhookEventName = "entitlement.created"
	WebhookEventNameEntitlementUpdated            WebhookEventName = "entitlement.updated"
	WebhookEventNameEntitlementDeleted            WebhookEventName = "entitlement.deleted"
	WebhookEventNameWalletCreated                 WebhookEventName = "wallet.created"
	WebhookEventNameWalletUpdated                 WebhookEventName = "wallet.updated"
	WebhookEventNameWalletTerminated              WebhookEventName = "wallet.terminated"
	WebhookEventNameWalletTransactionCreated      WebhookEventName = "wallet.transaction.created"
	WebhookEventNamePaymentCreated                WebhookEventName = "payment.created"
	WebhookEventNamePaymentUpdated                WebhookEventName = "payment.updated"
	WebhookEventNamePaymentFailed                 WebhookEventName = "payment.failed"
	WebhookEventNamePaymentSuccess                WebhookEventName = "payment.success"
	WebhookEventNamePaymentPending                WebhookEventName = "payment.pending"
	WebhookEventNameCustomerCreated               WebhookEventName = "customer.created"
	WebhookEventNameCustomerUpdated               WebhookEventName = "customer.updated"
	WebhookEventNameCustomerDeleted               WebhookEventName = "customer.deleted"
	WebhookEventNameInvoiceUpdateFinalized        WebhookEventName = "invoice.update.finalized"
	WebhookEventNameInvoiceUpdatePayment          WebhookEventName = "invoice.update.payment"
	WebhookEventNameInvoiceUpdateVoided           WebhookEventName = "invoice.update.voided"
	WebhookEventNameInvoiceUpdate                 WebhookEventName = "invoice.update"
	WebhookEventNameInvoicePaymentOverdue         WebhookEventName = "invoice.payment.overdue"
	WebhookEventNameWalletCreditBalanceDropped    WebhookEventName = "wallet.credit_balance.dropped"
	WebhookEventNameWalletCreditBalanceRecovered  WebhookEventName = "wallet.credit_balance.recovered"
	WebhookEventNameWalletOngoingBalanceDropped   WebhookEventName = "wallet.ongoing_balance.dropped"
	WebhookEventNameWalletOngoingBalanceRecovered WebhookEventName = "wallet.ongoing_balance.recovered"
	WebhookEventNameSubscriptionRenewalDue        WebhookEventName = "subscription.renewal.due"
	WebhookEventNameInvoiceCommunicationTriggered WebhookEventName = "invoice.communication.triggered"
	WebhookEventNameCreditNoteCreated             WebhookEventName = "credit_note.created"
	WebhookEventNameCreditNoteUpdated             WebhookEventName = "credit_note.updated"
)

func (e WebhookEventName) ToPointer() *WebhookEventName {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *WebhookEventName) IsExact() bool {
	if e != nil {
		switch *e {
		case "subscription.created", "subscription.draft.created", "subscription.activated", "subscription.updated", "subscription.paused", "subscription.cancelled", "subscription.resumed", "subscription.phase.created", "subscription.phase.updated", "subscription.phase.deleted", "feature.created", "feature.updated", "feature.deleted", "feature.wallet_balance.alert", "entitlement.created", "entitlement.updated", "entitlement.deleted", "wallet.created", "wallet.updated", "wallet.terminated", "wallet.transaction.created", "payment.created", "payment.updated", "payment.failed", "payment.success", "payment.pending", "customer.created", "customer.updated", "customer.deleted", "invoice.update.finalized", "invoice.update.payment", "invoice.update.voided", "invoice.update", "invoice.payment.overdue", "wallet.credit_balance.dropped", "wallet.credit_balance.recovered", "wallet.ongoing_balance.dropped", "wallet.ongoing_balance.recovered", "subscription.renewal.due", "invoice.communication.triggered", "credit_note.created", "credit_note.updated":
			return true
		}
	}
	return false
}
