// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/tirdad-billing/go-sdk/v2/internal/utils"
)

type WebhookDtoSubscriptionPhaseWebhookPayload struct {
	EventType *WebhookEventName          `json:"event_type,omitzero"`
	Phase     *SubscriptionPhaseResponse `json:"phase,omitzero"`
}

func (w WebhookDtoSubscriptionPhaseWebhookPayload) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(w, "", false)
}

func (w *WebhookDtoSubscriptionPhaseWebhookPayload) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &w, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (w *WebhookDtoSubscriptionPhaseWebhookPayload) GetEventType() *WebhookEventName {
	if w == nil {
		return nil
	}
	return w.EventType
}

func (w *WebhookDtoSubscriptionPhaseWebhookPayload) GetPhase() *SubscriptionPhaseResponse {
	if w == nil {
		return nil
	}
	return w.Phase
}
