// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/tirdad-billing/go-sdk/v2/internal/utils"
	"time"
)

type WebhookDtoSpendAlertEvent struct {
	AlertSettings        *AlertSettings                    `json:"alert_settings,omitzero"`
	AlertStatus          *AlertState                       `json:"alert_status,omitzero"`
	AlertType            *AlertType                        `json:"alert_type,omitzero"`
	CurrentSpend         *string                           `json:"current_spend,omitzero"`
	Group                *GroupResponse                    `json:"group,omitzero"`
	Subscription         *SubscriptionResponse             `json:"subscription,omitzero"`
	SubscriptionLineItem *SubscriptionSubscriptionLineItem `json:"subscription_line_item,omitzero"`
	TriggeredAt          *time.Time                        `json:"triggered_at,omitzero"`
}

func (w WebhookDtoSpendAlertEvent) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(w, "", false)
}

func (w *WebhookDtoSpendAlertEvent) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &w, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (w *WebhookDtoSpendAlertEvent) GetAlertSettings() *AlertSettings {
	if w == nil {
		return nil
	}
	return w.AlertSettings
}

func (w *WebhookDtoSpendAlertEvent) GetAlertStatus() *AlertState {
	if w == nil {
		return nil
	}
	return w.AlertStatus
}

func (w *WebhookDtoSpendAlertEvent) GetAlertType() *AlertType {
	if w == nil {
		return nil
	}
	return w.AlertType
}

func (w *WebhookDtoSpendAlertEvent) GetCurrentSpend() *string {
	if w == nil {
		return nil
	}
	return w.CurrentSpend
}

func (w *WebhookDtoSpendAlertEvent) GetGroup() *GroupResponse {
	if w == nil {
		return nil
	}
	return w.Group
}

func (w *WebhookDtoSpendAlertEvent) GetSubscription() *SubscriptionResponse {
	if w == nil {
		return nil
	}
	return w.Subscription
}

func (w *WebhookDtoSpendAlertEvent) GetSubscriptionLineItem() *SubscriptionSubscriptionLineItem {
	if w == nil {
		return nil
	}
	return w.SubscriptionLineItem
}

func (w *WebhookDtoSpendAlertEvent) GetTriggeredAt() *time.Time {
	if w == nil {
		return nil
	}
	return w.TriggeredAt
}
