// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/tirdad-billing/go-sdk/v2/internal/utils"
)

type WebhookDtoAlertWebhookPayload struct {
	AlertStatus *string `json:"alert_status,omitzero"`
	AlertType   *string `json:"alert_type,omitzero"`
	// Customer response object containing all customer information
	Customer  *CustomerResponse `json:"customer,omitzero"`
	EventType *WebhookEventName `json:"event_type,omitzero"`
	Feature   *FeatureResponse  `json:"feature,omitzero"`
	Wallet    *WalletResponse   `json:"wallet,omitzero"`
}

func (w WebhookDtoAlertWebhookPayload) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(w, "", false)
}

func (w *WebhookDtoAlertWebhookPayload) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &w, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (w *WebhookDtoAlertWebhookPayload) GetAlertStatus() *string {
	if w == nil {
		return nil
	}
	return w.AlertStatus
}

func (w *WebhookDtoAlertWebhookPayload) GetAlertType() *string {
	if w == nil {
		return nil
	}
	return w.AlertType
}

func (w *WebhookDtoAlertWebhookPayload) GetCustomer() *CustomerResponse {
	if w == nil {
		return nil
	}
	return w.Customer
}

func (w *WebhookDtoAlertWebhookPayload) GetEventType() *WebhookEventName {
	if w == nil {
		return nil
	}
	return w.EventType
}

func (w *WebhookDtoAlertWebhookPayload) GetFeature() *FeatureResponse {
	if w == nil {
		return nil
	}
	return w.Feature
}

func (w *WebhookDtoAlertWebhookPayload) GetWallet() *WalletResponse {
	if w == nil {
		return nil
	}
	return w.Wallet
}
