// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/tirdad-billing/go-sdk/v2/internal/utils"
)

type WebhookDtoFeatureWebhookPayload struct {
	EventType *WebhookEventName  `json:"event_type,omitzero"`
	Feature   *WebhookDtoFeature `json:"feature,omitzero"`
}

func (w WebhookDtoFeatureWebhookPayload) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(w, "", false)
}

func (w *WebhookDtoFeatureWebhookPayload) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &w, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (w *WebhookDtoFeatureWebhookPayload) GetEventType() *WebhookEventName {
	if w == nil {
		return nil
	}
	return w.EventType
}

func (w *WebhookDtoFeatureWebhookPayload) GetFeature() *WebhookDtoFeature {
	if w == nil {
		return nil
	}
	return w.Feature
}
