// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/tirdad-billing/go-sdk/v2/internal/utils"
)

type WebhookDtoAlertWebhookPayload struct {
	AlertStatus    *AlertState       `json:"alert_status,omitzero"`
	AlertType      *AlertType        `json:"alert_type,omitzero"`
	CreditBalance  *string           `json:"credit_balance,omitzero"`
	CurrentBalance *string           `json:"current_balance,omitzero"`
	CustomerID     *string           `json:"customer_id,omitzero"`
	EventType      *WebhookEventName `json:"event_type,omitzero"`
	FeatureID      *string           `json:"feature_id,omitzero"`
	WalletID       *string           `json:"wallet_id,omitzero"`
}

func (w WebhookDtoAlertWebhookPayload) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(w, "", false)
}

func (w *WebhookDtoAlertWebhookPayload) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &w, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (w *WebhookDtoAlertWebhookPayload) GetAlertStatus() *AlertState {
	if w == nil {
		return nil
	}
	return w.AlertStatus
}

func (w *WebhookDtoAlertWebhookPayload) GetAlertType() *AlertType {
	if w == nil {
		return nil
	}
	return w.AlertType
}

func (w *WebhookDtoAlertWebhookPayload) GetCreditBalance() *string {
	if w == nil {
		return nil
	}
	return w.CreditBalance
}

func (w *WebhookDtoAlertWebhookPayload) GetCurrentBalance() *string {
	if w == nil {
		return nil
	}
	return w.CurrentBalance
}

func (w *WebhookDtoAlertWebhookPayload) GetCustomerID() *string {
	if w == nil {
		return nil
	}
	return w.CustomerID
}

func (w *WebhookDtoAlertWebhookPayload) GetEventType() *WebhookEventName {
	if w == nil {
		return nil
	}
	return w.EventType
}

func (w *WebhookDtoAlertWebhookPayload) GetFeatureID() *string {
	if w == nil {
		return nil
	}
	return w.FeatureID
}

func (w *WebhookDtoAlertWebhookPayload) GetWalletID() *string {
	if w == nil {
		return nil
	}
	return w.WalletID
}
