// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/tirdad-billing/go-sdk/v2/internal/utils"
)

type WebhookDtoTransactionUpdatedWebhookPayload struct {
	EventType          *WebhookEventName            `json:"event_type,omitzero"`
	UpdatedTransaction *WebhookDtoWalletTransaction `json:"updated_transaction,omitzero"`
}

func (w WebhookDtoTransactionUpdatedWebhookPayload) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(w, "", false)
}

func (w *WebhookDtoTransactionUpdatedWebhookPayload) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &w, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (w *WebhookDtoTransactionUpdatedWebhookPayload) GetEventType() *WebhookEventName {
	if w == nil {
		return nil
	}
	return w.EventType
}

func (w *WebhookDtoTransactionUpdatedWebhookPayload) GetUpdatedTransaction() *WebhookDtoWalletTransaction {
	if w == nil {
		return nil
	}
	return w.UpdatedTransaction
}
