// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/tirdad-billing/go-sdk/v2/internal/utils"
	"time"
)

type WebhookDtoSubscriptionLineItem struct {
	BillingPeriod      *BillingPeriod                  `json:"billing_period,omitzero"`
	BillingPeriodCount *int64                          `json:"billing_period_count,omitzero"`
	Currency           *string                         `json:"currency,omitzero"`
	DisplayName        *string                         `json:"display_name,omitzero"`
	EndDate            *time.Time                      `json:"end_date,omitzero"`
	EntityID           *string                         `json:"entity_id,omitzero"`
	EntityType         *SubscriptionLineItemEntityType `json:"entity_type,omitzero"`
	ID                 *string                         `json:"id,omitzero"`
	InvoiceCadence     *InvoiceCadence                 `json:"invoice_cadence,omitzero"`
	Metadata           map[string]string               `json:"metadata,omitzero"`
	MeterDisplayName   *string                         `json:"meter_display_name,omitzero"`
	MeterID            *string                         `json:"meter_id,omitzero"`
	PlanDisplayName    *string                         `json:"plan_display_name,omitzero"`
	Price              *WebhookDtoPrice                `json:"price,omitzero"`
	PriceID            *string                         `json:"price_id,omitzero"`
	PriceType          *PriceType                      `json:"price_type,omitzero"`
	PriceUnit          *string                         `json:"price_unit,omitzero"`
	Quantity           *string                         `json:"quantity,omitzero"`
	StartDate          *time.Time                      `json:"start_date,omitzero"`
	SubscriptionID     *string                         `json:"subscription_id,omitzero"`
}

func (w WebhookDtoSubscriptionLineItem) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(w, "", false)
}

func (w *WebhookDtoSubscriptionLineItem) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &w, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (w *WebhookDtoSubscriptionLineItem) GetBillingPeriod() *BillingPeriod {
	if w == nil {
		return nil
	}
	return w.BillingPeriod
}

func (w *WebhookDtoSubscriptionLineItem) GetBillingPeriodCount() *int64 {
	if w == nil {
		return nil
	}
	return w.BillingPeriodCount
}

func (w *WebhookDtoSubscriptionLineItem) GetCurrency() *string {
	if w == nil {
		return nil
	}
	return w.Currency
}

func (w *WebhookDtoSubscriptionLineItem) GetDisplayName() *string {
	if w == nil {
		return nil
	}
	return w.DisplayName
}

func (w *WebhookDtoSubscriptionLineItem) GetEndDate() *time.Time {
	if w == nil {
		return nil
	}
	return w.EndDate
}

func (w *WebhookDtoSubscriptionLineItem) GetEntityID() *string {
	if w == nil {
		return nil
	}
	return w.EntityID
}

func (w *WebhookDtoSubscriptionLineItem) GetEntityType() *SubscriptionLineItemEntityType {
	if w == nil {
		return nil
	}
	return w.EntityType
}

func (w *WebhookDtoSubscriptionLineItem) GetID() *string {
	if w == nil {
		return nil
	}
	return w.ID
}

func (w *WebhookDtoSubscriptionLineItem) GetInvoiceCadence() *InvoiceCadence {
	if w == nil {
		return nil
	}
	return w.InvoiceCadence
}

func (w *WebhookDtoSubscriptionLineItem) GetMetadata() map[string]string {
	if w == nil {
		return nil
	}
	return w.Metadata
}

func (w *WebhookDtoSubscriptionLineItem) GetMeterDisplayName() *string {
	if w == nil {
		return nil
	}
	return w.MeterDisplayName
}

func (w *WebhookDtoSubscriptionLineItem) GetMeterID() *string {
	if w == nil {
		return nil
	}
	return w.MeterID
}

func (w *WebhookDtoSubscriptionLineItem) GetPlanDisplayName() *string {
	if w == nil {
		return nil
	}
	return w.PlanDisplayName
}

func (w *WebhookDtoSubscriptionLineItem) GetPrice() *WebhookDtoPrice {
	if w == nil {
		return nil
	}
	return w.Price
}

func (w *WebhookDtoSubscriptionLineItem) GetPriceID() *string {
	if w == nil {
		return nil
	}
	return w.PriceID
}

func (w *WebhookDtoSubscriptionLineItem) GetPriceType() *PriceType {
	if w == nil {
		return nil
	}
	return w.PriceType
}

func (w *WebhookDtoSubscriptionLineItem) GetPriceUnit() *string {
	if w == nil {
		return nil
	}
	return w.PriceUnit
}

func (w *WebhookDtoSubscriptionLineItem) GetQuantity() *string {
	if w == nil {
		return nil
	}
	return w.Quantity
}

func (w *WebhookDtoSubscriptionLineItem) GetStartDate() *time.Time {
	if w == nil {
		return nil
	}
	return w.StartDate
}

func (w *WebhookDtoSubscriptionLineItem) GetSubscriptionID() *string {
	if w == nil {
		return nil
	}
	return w.SubscriptionID
}
